### ISSUE TITLE
If you use a query with alias, the data source is not created.

### ISSUE THREAD

**Issue by eltriny** [metatron-app/metatron-discovery#1079]
**Describe the bug**
데이터소스 생성 시  alias 가 있는 쿼리를 사용할 경우 데이터소스 생성이 되지 않습니다.

**To Reproduce**
1. 데이터베이스를 이용한 데이터소스 생성화면으로 이동합니다.
2. 연결 정보를 입력하고, 쿼리 입력기를 통해서 데이터를 조회합니다. ( ex> select category as "ca" from sales )
3. 데이터소스 생성 완료를 하고, 상세 화면에서 확인하면 생성 실패가 나타납니다.

**Expected behavior**
정상적으로 생성되어야 합니다.

**Screenshots**
![1](https://user-images.githubusercontent.com/3685833/49811931-9d95b500-fda7-11e8-95d6-cd688e10252c.png)
![2](https://user-images.githubusercontent.com/3685833/49811932-9d95b500-fda7-11e8-9c77-7cbf92f0ddcf.png)

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser Chrome
 - Version 70

**Additional context**
```
2018-12-11 15:34:20.305 DEBUG [-] [ingestion-421efc3f-bc89-41f0-aa22-72e6d923fa03-0] a.m.d.d.d.i.job.IngestionJobRunner       : Send Progress Topic : /topic/datasources/421efc3f-bc89-41f0-aa22-72e6d923fa03/progress, ProgressResponse{progress=0, message='START_INGESTION_JOB', results=null}
2018-12-11 15:34:20.315 DEBUG [-] [ingestion-421efc3f-bc89-41f0-aa22-72e6d923fa03-0] a.m.d.d.d.i.job.IngestionJobRunner       : Send Progress Topic : /topic/datasources/421efc3f-bc89-41f0-aa22-72e6d923fa03/progress, ProgressResponse{progress=20, message='PREPARATION_HANDLE_LOCAL_FILE', results=null}
2018-12-11 15:34:20.318 DEBUG [-] [ingestion-421efc3f-bc89-41f0-aa22-72e6d923fa03-0] a.m.d.d.d.c.jdbc.JdbcConnectionService   : Created datasource : jdbc:mysql://localhost:3306/test_collect
2018-12-11 15:34:20.350  INFO [-] [ingestion-421efc3f-bc89-41f0-aa22-72e6d923fa03-0] a.m.d.d.d.c.jdbc.JdbcConnectionService   : Generated SQL Query2: SELECT `product`.`id`, `product`.`제품`, `product`.`가격` FROM product WHERE price > 10 LIMIT 10000000
2018-12-11 15:34:20.362 DEBUG [-] [ingestion-421efc3f-bc89-41f0-aa22-72e6d923fa03-0] a.m.d.d.d.connection.jdbc.JdbcCSVWriter  : Execute query : SELECT `product`.`id`, `product`.`제품`, `product`.`가격` FROM product WHERE price > 10 LIMIT 10000000 
2018-12-11 15:34:20.363 ERROR [-] [ingestion-421efc3f-bc89-41f0-aa22-72e6d923fa03-0] a.m.d.d.d.connection.jdbc.JdbcCSVWriter  : Fail to query for select :  Unknown column 'product.id' in 'field list'
2018-12-11 15:34:20.370 DEBUG [-] [ingestion-421efc3f-bc89-41f0-aa22-72e6d923fa03-0] a.m.d.common.entity.SpecValidator        : Check spec for interface app.metatron.discovery.domain.datasource.ingestion.IngestionInfo : {"dataType":"QUERY","type":"single","rollup":true,"query":"select \nuuid as \"id\",\nname as \"제품\",\nprice as \"가격\"\nfrom product\nwhere price > 10","database":"test_collect","scope":"ALL"}
2018-12-11 15:34:20.372 DEBUG [-] [ingestion-421efc3f-bc89-41f0-aa22-72e6d923fa03-0] a.m.d.d.d.i.job.IngestionJobRunner       : Send Progress Topic : /topic/datasources/421efc3f-bc89-41f0-aa22-72e6d923fa03/progress, ProgressResponse{progress=-1, message='FAIL_INGESTION_JOB', results={history=IngestionHistory{dataSourceId='421efc3f-bc89-41f0-aa22-72e6d923fa03', ingestionId='null', ingestionMethod=null, duration=null, status=FAILED, errorCode=INGESTION_JDBC_QUERY_EXECUTION_ERROR, progress=PREPARATION_HANDLE_LOCAL_FILE, cause='JdbcDataConnectionException: Fail to query : Unknown column 'product.id' in 'field list''} app.metatron.discovery.domain.datasource.ingestion.IngestionHistory@16ae77a8}}
2018-12-11 15:34:20.377 ERROR [-] [ingestion-421efc3f-bc89-41f0-aa22-72e6d923fa03-0] a.m.d.d.d.i.job.IngestionJobRunner       : Fail to ingestion : IngestionHistory{dataSourceId='421efc3f-bc89-41f0-aa22-72e6d923fa03', ingestionId='null', ingestionMethod=null, duration=null, status=FAILED, errorCode=INGESTION_JDBC_QUERY_EXECUTION_ERROR, progress=PREPARATION_HANDLE_LOCAL_FILE, cause='JdbcDataConnectionException: Fail to query : Unknown column 'product.id' in 'field list''} app.metatron.discovery.domain.datasource.ingestion.IngestionHistory@16ae77a8

app.metatron.discovery.domain.datasource.DataSourceIngestionException: Fail to query : Unknown column 'product.id' in 'field list'
	at app.metatron.discovery.domain.datasource.ingestion.job.JdbcIngestionJob.preparation(JdbcIngestionJob.java:118)
	at app.metatron.discovery.domain.datasource.ingestion.job.IngestionJobRunner.ingestion(IngestionJobRunner.java:169)
	at app.metatron.discovery.domain.datasource.DataSourceEventHandler.lambda$checkCreateAuthority$0(DataSourceEventHandler.java:230)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: app.metatron.discovery.domain.datasource.connection.jdbc.JdbcDataConnectionException: Fail to query : Unknown column 'product.id' in 'field list'
	at app.metatron.discovery.domain.datasource.connection.jdbc.JdbcCSVWriter.write(JdbcCSVWriter.java:204)
	at app.metatron.discovery.domain.datasource.connection.jdbc.JdbcConnectionService.selectQueryToCsv(JdbcConnectionService.java:1129)
	at app.metatron.discovery.domain.datasource.connection.jdbc.JdbcConnectionService.selectQueryToCsv(JdbcConnectionService.java:1066)
	at app.metatron.discovery.domain.datasource.connection.jdbc.JdbcConnectionService.selectQueryToCsv(JdbcConnectionService.java:1057)
	at app.metatron.discovery.domain.datasource.connection.jdbc.JdbcConnectionService.selectQueryToCsv(JdbcConnectionService.java:1050)
	at app.metatron.discovery.domain.datasource.ingestion.job.JdbcIngestionJob.preparation(JdbcIngestionJob.java:109)
	... 7 common frames omitted
```

**Comment by steve-kyungjin** [comment]
1. this issue from IBK

**Comment by ufoscw** [comment]
@eltriny  
UI 수정요청이 있습니다.
Linked DataSource Data Preview에서 헤더 정보는 response의 헤더 정보를 사용하지 않는것 같습니다.
<img width="1421" alt="devtools_-_localhost_8180_app_v2_management_storage_datasource_b31eeff4-0f06-46c7-92a8-8dc55920ba96_ _metatron_discovery" src="https://user-images.githubusercontent.com/3770446/49847175-234e4a80-fe12-11e8-98d7-2052a05eff2b.png">

H#1079_datasource_with_query_error 브랜치에 커밋해주시면 됩니다.

**Comment by brandon-wonjune** [comment]
@ufoscw 
해당 브랜치에서 아래와 같이 데이터소스를 생성해보았습니다.
1. 데이터소스 > DB로 데이터소스 생성 > 연결형데이터소스 선택
2. 데이터테이블 선택에서 QUERY로 아래와 같이 작성
```select LOAD_OPTION, PLUGIN_NAME as 'book_name526_', PLUGIN_VERSION as 'book_name', PLUGIN_AUTHOR from ALL_PLUGINS```
3. 데이터소스 생성 > 상세화면으로 이동 > 데이터 화면 클릭
4. 출력 확인
![2018-12-12 3 41 28](https://user-images.githubusercontent.com/42233627/49851461-7fba6580-fe24-11e8-989e-d5a5e47fb513.png)
![2018-12-12 3 41 38](https://user-images.githubusercontent.com/42233627/49851462-8052fc00-fe24-11e8-83c6-8b902dc6451e.png)

위에서 하신 테스트 순서와 다르다면 테스트 하신 순서를 알 수 있을까요?

**Comment by ufoscw** [comment]
@brandon-wonjune 
수정된 코드는 곧 커밋할 예정입니다.
테스트 한 쿼리는 아래처럼 해보시면 됩니다.
```
select LOAD_OPTION, LOAD_OPTION from ALL_PLUGINS
```

**Comment by brandon-wonjune** [comment]
@ufoscw 수정하였습니다.
![2018-12-12 4 39 13](https://user-images.githubusercontent.com/42233627/49854100-8220bd80-fe2c-11e8-8c23-5f2eaeecf806.png)
![2018-12-12 4 39 19](https://user-images.githubusercontent.com/42233627/49854101-8220bd80-fe2c-11e8-8c1b-ff1ce8ce4d18.png)

**Comment by ufoscw** [comment]
@brandon-wonjune 추가적인 요청사항이 있습니다.
데이터베이스 상세보기 화면에서
ingestion.type = link
ingestion.dataType = QUERY 인 경우 쿼리 수정 로직에 문제가 있어 "Edit filters" 버튼을 비활성화 처리 해야 할것 같습니다.
<img width="1652" alt="devtools_-_52_231_184_135_8187_app_v2_workspace_ws-00_ _metatron_discovery" src="https://user-images.githubusercontent.com/3770446/49857474-fad84780-fe35-11e8-92c9-7aebac245e24.png">

**Comment by brandon-wonjune** [comment]
@ufoscw 수정하였습니다.
![2018-12-12 6 02 20](https://user-images.githubusercontent.com/42233627/49858571-9ec2f280-fe38-11e8-9c47-93a63c4656bd.png)
![Uploading 스크린샷 2018-12-12 오후 6.02.29.png…]()

**Comment by ufoscw** [comment]
@metatron-app/design @kyungtaak 
현재 JDBC Query를 통한 데이터 소스 생성시 아래와 같은 문제가 있습니다.
중복컬럼이 존재하는 경우 SubQuery로 감싼 후 쿼리를 수행할 경우 "중복 컬럼" 에러가 발생합니다.

ex)
```
DB : mysql

* Query 정상수행 
SELECT a.book_name, b.book_name
FROM polaris_v2.book a
join polaris_v2.book b on a.type = b.type;

* SubQuery 처리시 에러발생
SELECT * 
FROM (
  SELECT a.book_name, b.book_name
  FROM polaris_v2.book a
  join polaris_v2.book b on a.type = b.type 
) tt;
```

이렇게 SubQuery를 사용해 쿼리문을 처리하는 경우는 현재 2가지입니다.
1. 연결형 DataSource의 필수필터 지정 시
2. 수집형 DataSource의 주기적 수집일 경우

우선 1번째 케이스에 대해서는 임시로 필터지정기능을 막았지만 이는 임시적인 조치이며 기획팀, 개발팀 논의를 통해 해결이 필요한 상황입니다.

**Comment by ufoscw** [comment]
@brandon-wonjune 
Linked DataSource의 필터 설정 버튼을 비활성화하는 수정사항은 임시적인 사항이었으므로 다시 원복해야 할것 같습니다.
fix 브랜치를 하나 생성해서 버튼 비활성화 로직은 제거 해주시고 PR 오픈 부탁드립니다.
