### ISSUE TITLE
Support timezone for field of timestamp type

### ISSUE THREAD

**Issue by kyungtaak** [metatron-app/metatron-discovery#1193]
**Is your feature request related to a problem? Please describe.**
적재되는 데이터 소스내 타임스템프 타입이 포함된 경우, 타임존이 설정되어 있지않아 대시보드 상에서 데이터 조회시 사용자 기준의 타임존 기준 시간을 확인할수 없습니다.

**Describe the solution you'd like**
데이터 소스 생성자는 데이터 소스내 타임스템프 타입에 timezone 을 지정할수 있고,  사용자는 사용자 브라우져 타임존에 맞춘 시간 값을 대시보드를 통해 볼수 있습니다.

The datasource creator can set a timezone to the timestamp type in the data source, and the user can view the time value according to the user's browser timezone through the dashboard.

**Describe alternatives you've considered**
- Support Timezone list (https://en.wikipedia.org/wiki/List_of_tz_database_time_zones)  
- Consider backward backward compatibility

**Additional context**
(N/A)

**Comment by kyungtaak** [comment]
@metatron-app/design @AnnieHwang 위의 요구사항에 의하여 아래 두가지 요건이 필요합니다.
- Timestamp Type 의 필드 적재시 timezone / locale(영어-en,한국어-ko,중국어-zh) 지정, 이 정보를 포함하여 validation 수행
- 위젯 내 선반에 timestamp type 의 dimension (timestamp role 포함) 위치시 브라우저의 timezone / locale 정보를 가져다가 동적으로 전달하여, 해당 timezone 에 맞는 데이터를 보여주게 됩니다. (이건은 별도의 화면 기획은 필요가 없으나, 위젯/대시보드에서 데이터 조회시의 시나리오를 위한 전달 방법입니다.)

**Comment by kyungtaak** [comment]
@deidera08 답변드립니다.
1. 타임존 지원 범위는 모두 나오는게 좋을것 같습니다. (콤보박스에 검색이 있어도 좋을것 같습니다.)
2. Timestamp Role 외 Dimension Role 의 timestamp 타입도 영향을 받습니다.
   그리고 데이터 그리드에서 보여줄때는 위젯에서에서 보는것과 동일한 타임존의 영향을 받게 데이터를 전달할 예정입니다.
3. 수정은 불가능합니다.
4. current time 은 가려지는 값이므로, 설정이 필요없을 것으로 보입니다.

**Comment by deidera08** [comment]
@kyungtaak 
빠른 답변 주셔서 감사합니닷 :)
추가 질문 드립니다.

>Timestamp Role 외 Dimension Role 의 timestamp 타입도 영향을 받습니다.
그리고 데이터 그리드에서 보여줄때는 위젯에서에서 보는것과 동일한 타임존의 영향을 받게 데이터를 전달할 예정입니다.

Timestamp Role이 무엇일까요?
Timestamp로 지정한 컬럼 외에 Dimension > Date/Time 컬럼도 각각의 타임존을 설정할 수 있는건가요?
즉 한 데이터그리드 안에 Date/Time컬럼이 다중일 경우 이는 각각의 타임존을 설정할 수 있나요?

**Comment by minjung-cho** [comment]
@AnnieHwang 대시보드단에서 어느 타임존을 기준으로 시간값이 보여지고 있는지 열람이 가능해야 할것 같습니다. 이건 대시보드 이슈로 따로 진행하겠습니다.

**Comment by deidera08** [comment]
@kyungtaak @AnnieHwang 
다음과 같이 기획하였습니다.

Ingestion Settings > Timestamp Setting에서 타임존 설정을 할 수 있습니다.
![timezone01](https://user-images.githubusercontent.com/42257766/50835087-197c2080-1399-11e9-848a-76757c005a85.PNG)
![timezone02](https://user-images.githubusercontent.com/42257766/50835089-1aad4d80-1399-11e9-97aa-693e2cc4a30a.PNG)

설정한 타임존은 상세화면, 데이터 그리드화면, 컬럼상세 화면에 각각 정보가 노출됩니다.
![timezone03](https://user-images.githubusercontent.com/42257766/50835094-1d0fa780-1399-11e9-8b79-8455f45bacc9.PNG)
![timezone04](https://user-images.githubusercontent.com/42257766/50835096-1e40d480-1399-11e9-9969-8c32eac8b48b.PNG)
![timezone05](https://user-images.githubusercontent.com/42257766/50835098-1f720180-1399-11e9-9b78-07926a3b4907.PNG)

부족한 부분이나 잘못 표현된 부분이 있을 경우 가이드 부탁드립니다.

**Comment by kyungtaak** [comment]
@deidera08 

> Timestamp Role이 무엇일까요?

컬럼의 역할을 measure/dimension/timestamp 이 세가지로 정의하였습니다. timestamp role 은 적재시 반드시지정해야하는 timestamp 타입의 필드를 의미하며, 컬럼중 하나만 지정할수 있습니다.

> Timestamp로 지정한 컬럼 외에 Dimension > Date/Time 컬럼도 각각의 타임존을 설정할 수 있는건가요? 즉 한 데이터그리드 안에 Date/Time컬럼이 다중일 경우 이는 각각의 타임존을 설정할 수 있나요?

네 그렇게 되어야한다고 생각하고 있습니다.

**Comment by kyungtaak** [comment]
@deidera08 보통 TZ database 명은 국가가 아닌 대륙명을 앞에 두고 Asia/Seoul 이렇게 표기합니다.

**Comment by deidera08** [comment]
@kyungtaak @AnnieHwang 
> @deidera08 보통 TZ database 명은 국가가 아닌 대륙명을 앞에 두고 Asia/Seoul 이렇게 표기합니다.

개인적인 경험치로 나라명이 있는 경우를 많이 봤던 터라 자연스럽게 대륙을 빼고 나라명을 노출시켰더랬습니다.
우리 UI에서는 아무래도 직접 (휠을 굴려가며) 선택하기보다는 검색이 주를 이룰듯 합니다.
유저에게 검색어를 다양하게 주기 위해서 나라명, 대륙명 함께 노출시키면 어떨까요?
예) +09:00 Korea/서울/아시아 +09:00 Korea/Seoul/Asia
이런식으로 표현하면 좋을듯 합니다.

수정된 파일입니다.
[#1193TimezoneList_v1.1.xlsx](https://github.com/metatron-app/metatron-discovery/files/2739492/1193TimezoneList_v1.1.xlsx)

**Comment by deidera08** [comment]
@kyungtaak @AnnieHwang 
> > Timestamp로 지정한 컬럼 외에 Dimension > Date/Time 컬럼도 각각의 타임존을 설정할 수 있는건가요? 즉 한 데이터그리드 안에 Date/Time컬럼이 다중일 경우 이는 각각의 타임존을 설정할 수 있나요?
> 
> 네 그렇게 되어야한다고 생각하고 있습니다.

위의 상황에 맞춰 Date/Time type에 각각의 타임존을 설정할 수 있도록 화면 수정하였습니다.

![2019-01-10 9 40 14](https://user-images.githubusercontent.com/42257766/50938501-d8c8f800-14bb-11e9-979b-334f8d0b9686.png)
![2019-01-10 9 40 21](https://user-images.githubusercontent.com/42257766/50938502-d9618e80-14bb-11e9-917b-238850b9e747.png)
![2019-01-10 9 40 30](https://user-images.githubusercontent.com/42257766/50938504-d9618e80-14bb-11e9-8dd9-14c1bd126623.png)
![2019-01-10 9 40 40](https://user-images.githubusercontent.com/42257766/50938505-d9618e80-14bb-11e9-97cd-506ded648ec6.png)
![2019-01-10 9 40 49](https://user-images.githubusercontent.com/42257766/50938506-d9618e80-14bb-11e9-9920-9e5194c0c4ff.png)

---------------------
질문이 있습니다.
대시보드 생성시 데이터간 join이나 필터 지정시 타임존에 대한 데이터값 표현이 영향을 미치지 않는지 궁금합니다.

예를들어 join을 할 경우 join대상의 A,B컬럼에 동일한 2000-01-01 00:00:00의 날짜값이 있다고 가정하고
A컬럼에 00:00의 타임존, B컬럼에 +23:00의 타임존일경우 데이터값 표현은 각각 2000-01-01 00:00:00, 2000-01-01 23:00:00이 됩니다. 이때 A,B 데이터값을 동일한 값으로 보는지요?

또는 타임존에 의해 변형된 시간이 같을 경우를 (위 상황과 반대) 같은 데이터값으로 보는지 궁금합니다.

**Comment by kyungtaak** [comment]
@deidera08 위의 상황이라면, 엔진에서 인식되는 되는시간은 UTC(0시) 기준입니다. 따라서 
- A 컬럼의 경우 적재된 시간은 2000년 1월 1일 0시 
- B 컬럼의 경우 적재된 시간은 1999년 12월 31일 1시 

사용자가 Asia/Seoul (+9) 인경우 보이는 시간값은, 아래처럼 보일거에요.
- A 컬럼의 경우 2000년 1월 1일 9시 
- B 컬럼의 경우 1999년 12월 31일 10시

**Comment by koeun222** [comment]
@AnnieHwang 타임존 추가 관련 디자인 공유드립니다
데이터소스스 > 생성(myfile) > 스키마설정
![image](https://user-images.githubusercontent.com/42256760/50957048-9675da00-1500-11e9-8ea3-96970ab3e655.png)

데이터소스스 > 상세(data grid)
1. data grid > header area 디자인수정
-  header height 50px
- ‘column name’ text size 13pt / Bold
- header line color #d5d5da
2. Time zone 추가
![image](https://user-images.githubusercontent.com/42256760/50957237-07b58d00-1501-11e9-930b-f47b89214f1c.png)

데이터소스스 > 상세(Column details)
![image](https://user-images.githubusercontent.com/42256760/50957086-aab9d700-1500-11e9-86fe-2cd504235a78.png)

**Comment by AnnieHwang** [comment]
@kyungtaak @deidera08 데이터소스 > 상세(data grid) 에서 타임존이 컬럼 헤더(이름열) 전면에 나올정도로 중요한가요? 전 툴팁 정도로만 나오면 될것 같은데.. 어떻게 생각하세요? 너무 여러줄 헤더에 나오면 정신없을것 같아서요

**Comment by deidera08** [comment]
@AnnieHwang 
> @kyungtaak @deidera08 데이터소스 > 상세(data grid) 에서 타임존이 컬럼 헤더(이름열) 전면에 나올정도로 중요한가요? 전 툴팁 정도로만 나오면 될것 같은데.. 어떻게 생각하세요? 너무 여러줄 헤더에 나오면 정신없을것 같아서요

시간타입 컬럼마다 각각 타임존을 설정할 수 있다보니 Data grid화면에서 다중의 시간타입 컬럼이 각각 다른 타임존일 경우 한눈에 인지하기 어렵지 않을까 해서 전면(상단)에 해당 정보를 추가해야겠다고 생각했었는데요
말씀하신대로 컬럼명, logical 컬럼명, 타임존 정보까지 최대 3줄이 노출될 수 있어서 정보과다 노출일 수도 있을 듯 합니다.
시간타입 컬럼에 마우스오버시 툴팁으로 타임존 정보를 노출하는것으로 수정요청 하도록 하겠습니다.

**Comment by koeun222** [comment]
@AnnieHwang @eltriny 수정된 사항 공유드립니다 
**데이터소스 > 상세(data grid)**
- Time zone 추가 : Date/Time 컬럼 호버시 타임존 툴팁 노출로 수정 및 헤더영역 수정
![image](https://user-images.githubusercontent.com/42256760/51455022-013dd580-1d8b-11e9-881f-aed03b89f70c.png)

**Comment by brandon-wonjune** [comment]
@kyungtaak 
데이터소스 생성시 timestamp인 column의 timezone은 어떤 파라메터를 사용하면 되나요?

**Comment by kyungtaak** [comment]
@brandon-wonjune 아래와 같이 입력해주시면 됩니다. 
```
{
  format: {
    ...
    timeZone: "Asia/Seoul",
    locale: "en"
  }
}
```

**Comment by deidera08** [comment]
@AnnieHwang @kyungtaak @brandon-wonjune 
현재 데이터그리드에 툴팁을 추가하는 것이 구조상 어렵기 때문에
타임존 정보를 텍스트로 바로 노출시키는 초안으로 우선 구현 부탁드리겠습니다.

**Comment by kyungtaak** [comment]
@eltriny @brandon-wonjune  쿼리를 수행시 timezone 을 위한 별도로직은 제거해주시고요. 현 브라우져 시간 / timezone 기준 정보를 전달해주세요.

**Comment by brandon-wonjune** [comment]
@kyungtaak 
쿼리를 수행시라고 한다면,
database로 생성> query 로 테이블 선택을 의미하는건가요?

**Comment by brandon-wonjune** [comment]
@kyungtaak 
테스트 중 아래와 같은 상황에서 적재시 에러가 발생합니다.
```
데이터베이스로 데이터소스 생성 > 연결형 선택 > 테이블 선택 > current_time으로 timestamp 선택 > 생성 > 상세화면에서 ingestion시 에러 발생
```

```
// params
{"dsType":"MASTER","srcType":"JDBC","connType":"ENGINE","granularity":"MONTH","segGranularity":"MONTH","name":"test","description":"","ingestion":{"dataType":"TABLE","type":"single","rollup":true,"query":"ALL_PLUGINS","database":"information_schema","scope":"ALL"},"fields":[{"name":"PLUGIN_NAME","alias":"PLUGIN_NAME","type":"STRING","logicalType":"STRING","role":"DIMENSION","aggrType":"NONE","seq":0},{"name":"PLUGIN_VERSION","alias":"PLUGIN_VERSION","type":"STRING","logicalType":"STRING","role":"DIMENSION","aggrType":"NONE","seq":1},{"name":"PLUGIN_STATUS","alias":"PLUGIN_STATUS","type":"STRING","logicalType":"STRING","role":"DIMENSION","aggrType":"NONE","seq":2},{"name":"PLUGIN_TYPE","alias":"PLUGIN_TYPE","type":"STRING","logicalType":"STRING","role":"DIMENSION","aggrType":"NONE","seq":3},{"name":"PLUGIN_TYPE_VERSION","alias":"PLUGIN_TYPE_VERSION","type":"STRING","logicalType":"STRING","role":"DIMENSION","aggrType":"NONE","seq":4},{"name":"PLUGIN_LIBRARY","alias":"PLUGIN_LIBRARY","type":"STRING","logicalType":"STRING","role":"DIMENSION","aggrType":"NONE","seq":5},{"name":"PLUGIN_LIBRARY_VERSION","alias":"PLUGIN_LIBRARY_VERSION","type":"STRING","logicalType":"STRING","role":"DIMENSION","aggrType":"NONE","seq":6},{"name":"PLUGIN_AUTHOR","alias":"PLUGIN_AUTHOR","type":"STRING","logicalType":"STRING","role":"DIMENSION","aggrType":"NONE","seq":7},{"name":"PLUGIN_DESCRIPTION","alias":"PLUGIN_DESCRIPTION","type":"STRING","logicalType":"STRING","role":"DIMENSION","aggrType":"NONE","seq":8},{"name":"PLUGIN_LICENSE","alias":"PLUGIN_LICENSE","type":"STRING","logicalType":"STRING","role":"DIMENSION","aggrType":"NONE","seq":9},{"name":"LOAD_OPTION","alias":"LOAD_OPTION","type":"STRING","logicalType":"STRING","role":"DIMENSION","aggrType":"NONE","seq":10},{"name":"PLUGIN_MATURITY","alias":"PLUGIN_MATURITY","type":"STRING","logicalType":"STRING","role":"DIMENSION","aggrType":"NONE","seq":11},{"name":"PLUGIN_AUTH_VERSION","alias":"PLUGIN_AUTH_VERSION","type":"STRING","logicalType":"STRING","role":"DIMENSION","aggrType":"NONE","seq":12},{"seq":13,"name":"current_datetime","type":"TIMESTAMP","role":"TIMESTAMP","derived":true,"format":{"type":"time_temporary","format":"yyyy-MM-dd HH:mm:ss"}}],"connection":"/api/connections/c10943db-de02-4e75-9eb9-4bd6dad214d6"}

//error
app.metatron.discovery.domain.engine.EngineException: Fail to process response : [{"error":"Instantiation of [simple type, class io.druid.indexing.common.task.IndexTask] value failed: interval empty"}]
	at app.metatron.discovery.domain.engine.AbstractEngineRepository.call(AbstractEngineRepository.java:126)
	at app.metatron.discovery.domain.engine.AbstractEngineRepository.call(AbstractEngineRepository.java:111)
	at app.metatron.discovery.domain.engine.DruidEngineRepository.ingestion(DruidEngineRepository.java:71)
	at app.metatron.discovery.domain.engine.DruidEngineRepository$$FastClassBySpringCGLIB$$7c06ef0f.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:204)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:738)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:157)
	at org.springframework.aop.aspectj.MethodInvocationProceedingJoinPoint.proceed(MethodInvocationProceedingJoinPoint.java:85)
	at app.metatron.discovery.domain.engine.QueryServiceAspect.engineQueryProcessing(QueryServiceAspect.java:119)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.aop.aspectj.AbstractAspectJAdvice.invokeAdviceMethodWithGivenArgs(AbstractAspectJAdvice.java:629)
	at org.springframework.aop.aspectj.AbstractAspectJAdvice.invokeAdviceMethod(AbstractAspectJAdvice.java:618)
	at org.springframework.aop.aspectj.AspectJAroundAdvice.invoke(AspectJAroundAdvice.java:70)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
	at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:92)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:673)
	at app.metatron.discovery.domain.engine.DruidEngineRepository$$EnhancerBySpringCGLIB$$cddeed75.ingestion(<generated>)
	at app.metatron.discovery.domain.datasource.ingestion.job.AbstractIngestionJob.doIngestion(AbstractIngestionJob.java:173)
	at app.metatron.discovery.domain.datasource.ingestion.job.JdbcIngestionJob.process(JdbcIngestionJob.java:160)
	at app.metatron.discovery.domain.datasource.ingestion.job.IngestionJobRunner.ingestion(IngestionJobRunner.java:182)
	at app.metatron.discovery.domain.datasource.DataSourceEventHandler.lambda$checkCreateAuthority$0(DataSourceEventHandler.java:230)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: app.metatron.discovery.domain.datasource.data.QueryTimeExcetpion: [{"error":"Instantiation of [simple type, class io.druid.indexing.common.task.IndexTask] value failed: interval empty"}]
	at app.metatron.discovery.domain.engine.DruidEngineRepository$QueryResponseErrorHandler.handleError(DruidEngineRepository.java:115)
	at org.springframework.web.client.RestTemplate.handleResponse(RestTemplate.java:707)
	at org.springframework.web.client.RestTemplate.doExecute(RestTemplate.java:660)
	at org.springframework.web.client.RestTemplate.execute(RestTemplate.java:620)
	at org.springframework.web.client.RestTemplate.exchange(RestTemplate.java:538)
	at app.metatron.discovery.domain.engine.AbstractEngineRepository.call(AbstractEngineRepository.java:120)
	... 29 common frames omitted
```

**Comment by kyungtaak** [comment]
@deidera08 @brandon-wonjune 아래와 같이 millis 타입인 경우 timezone 의미가 없어 설정을 제거하는것은 어떠실런지요? 확인 부탁드립니다.
![image](https://user-images.githubusercontent.com/822255/51885189-cad90980-23cd-11e9-8365-8b2f0eeaa507.png)

**Comment by deidera08** [comment]
@kyungtaak @AnnieHwang @brandon-wonjune 
가이드주신대로 Unix time일 경우 timezone 설정이 무의미하므로 설정 자체를 노출안시키는게 좋을듯 합니다.
(밀리세컨, 세컨드 모두 해당할 듯 합니다.)

@brandon-wonjune 
Unix time을 체크할 경우 timezone 설정이 노출되지 않도록 부탁드려요
더불어 Data grid 화면에서 타임존 정보가 노출되는 부분에 Unix time으로 표기해주시면 될 듯 합니다.

**Comment by brandon-wonjune** [comment]
@kyungtaak @deidera08 
unix type의 경우 timezone 을 제거하였습니다.
적용된 화면은 아래와 같습니다.
![2019-01-29 3 02 26](https://user-images.githubusercontent.com/42233627/51887516-82264e00-23d7-11e9-8ee7-94c010ff73ae.png)
![2019-01-29 3 02 29](https://user-images.githubusercontent.com/42233627/51887528-881c2f00-23d7-11e9-8f8a-b504f5ae3cd1.png)
![2019-01-29 3 02 31](https://user-images.githubusercontent.com/42233627/51887529-881c2f00-23d7-11e9-8fa5-32cb463df52d.png)

@kyungtaak 
데이터소스 생성시 field가 unix_time으로 지정되어있는 경우 
기존에 전달되던 `timezone`과 `locale`을 제거하도록 수정하였습니다.

**Comment by kyungtaak** [comment]
@deidera08 그리드 화면에서 너무 많은 타임존 정보가 노출되는게 아닌가 생각됩니다. 
+9:00 또는 Asia/Seoul 또는 +9:00 Seoul 이런시긍로 축약하면 어떨런지요? 검토부탁드립니다.

**Comment by deidera08** [comment]
@kyungtaak @AnnieHwang 
> +9:00 또는 Asia/Seoul 또는 +9:00 Seoul 이런시긍로 축약하면 어떨런지요?

'+9:00 Asia/Seoul'와 같이 노출되게 된 이유는 Seoul과 같은 도시값이 전부 존재하지 않는데, 그렇다면 노출되어야 하는 값은 Asia와 같은 대륙값입니다. 그러나 대륙값 속에 시차 폭이 너무 커서 두 값 모두 노출하게 되었습니다.
(부득이하게 도시값이 없을 경우만 대륙값만 노출)

때문에 그리드화면에서 굳이 1개 정보만 남긴다면 +09:00와 같은 시간값이여야 할 듯 합니다.
그러나 **일반 유저가 00:00 숫자를 봤을때 이것이 타임존 정보인지 잘 모를것 같아 라벨과 함께 표기해야 할 듯 합니다.**
노출 예시:  UTC 00:00

@brandon-wonjune 
데이터 그리드 화면에서만 타임존 노출 정보를 'UTC + 시간값'으로 수정 부탁드립니다.

**Comment by brandon-wonjune** [comment]
@deidera08 @kyungtaak 수정하였습니다.
![2019-01-29 5 29 53](https://user-images.githubusercontent.com/42233627/51894643-b6a40500-23eb-11e9-8d87-a2340741df5e.png)

**Comment by kyungtaak** [comment]
> timezone 관련 UI 로직 제거를 위해 테스트 하는 과정에서 API 오류가 발생하여 확인 요청드립니다.

긴급하게 Field 617 라인에 아래와 같이 수정후 확인 부탁드립니다.
```
fieldFormat = new CustomDateTimeFormat(format);
```

**Comment by kyungtaak** [comment]
@brandon-wonjune @eltriny 위 두건의 오류를 해결하여 올려두었습니다. 확인 부탁드립니다.

**Comment by kyungtaak** [comment]
@deidera08 그리드에서 timezone 표시가 뭔가 어색하는데요. 혹시 timezone 표시 글자를 조금 줄이는 방법이나.. 다른 방법이 없을까요...?

**Comment by brandon-wonjune** [comment]
@kyungtaak current_time으로 ingestion이 정상적으로 되는것 확인했습니다.

**Comment by deidera08** [comment]
@kyungtaak 
> @deidera08 그리드에서 timezone 표시가 뭔가 어색하는데요. 혹시 timezone 표시 글자를 조금 줄이는 방법이나.. 다른 방법이 없을까요...?

더 줄인다면 다음과 같이 표기하면 어떨까 합니다.
**예시값: UTC+9, UTC-11, UTC+9:30**

그리고 폰트 사이즈를 한사이즈 더 작게 표현하면 어떨까 싶네요
@koeun222 검토 부탁드려요

**Comment by koeun222** [comment]
네에 타임존 text size 11pt로 퍼블 적용 부탁드려요-

**Comment by eltriny** [comment]
@kyungtaak
위에 문의드렸던 대시보드 정보 조회하는 API 에서 추가적으로 오류가 발생하여 문의드립니다.
API : /api/dashboards/{dashboardId}?projection=forDetailView

API 결과
<img width="1055" alt="2019-01-29 6 31 42" src="https://user-images.githubusercontent.com/3685833/51898474-4f3e8300-23f4-11e9-8e4d-038556d16b6f.png">

필드의 foramt 값이 위 이미지와 같이 내려와서 json parsing이 되지 않습니다.

**Comment by brandon-wonjune** [comment]
@kyungtaak @deidera08 
> 더 줄인다면 다음과 같이 표기하면 어떨까 합니다.
예시값: UTC+9, UTC-11, UTC+9:30

수정하였습니다.

**Comment by kyungtaak** [comment]
@eltriny 죄송합니다. 제가 답변이 늦었네요. 위 오류는 수정하였습니다.
