### ISSUE TITLE
Fix NPE in expression dimension spec for null value

### ISSUE THREAD

**Issue by navis** [metatron-app/metatron-discovery#1360]
```
java.lang.NullPointerException: null value in entry: partial_null_column=null
	at com.google.common.collect.CollectPreconditions.checkEntryNotNull(CollectPreconditions.java:33) ~[guava-16.0.1.jar:?]
	at com.google.common.collect.SingletonImmutableBiMap.<init>(SingletonImmutableBiMap.java:39) ~[guava-16.0.1.jar:?]
	at com.google.common.collect.ImmutableBiMap.of(ImmutableBiMap.java:57) ~[guava-16.0.1.jar:?]
	at com.google.common.collect.ImmutableMap.of(ImmutableMap.java:80) ~[guava-16.0.1.jar:?]
	at io.druid.query.dimension.ExpressionDimensionSpec$2.lookupName(ExpressionDimensionSpec.java:132) ~[classes/:?]
```

Immutable map does not allow null value.

**Comment by navis** [comment]
Fixed
