### ISSUE TITLE
An error occurs when using reserved words for field names.

### ISSUE THREAD

**Issue by ufoscw** [metatron-app/metatron-discovery#1495]
**Describe the bug**
An error occurs when using reserved words for field names.
(ex: count)

**To Reproduce**
1. create datasource > database > mysql
2. input simple query
* query 1
```
select 1 as count;
```
* query 2
```
select '1' as count;
```
Both of these cases should be tested.
3. create datasource with "count" field name
```
2019-02-21T04:36:15,403 ERROR [task-runner-0-priority-0] io.druid.indexing.overlord.ThreadPoolTaskRunner - Exception while running task[IndexTask{id=index_cnt_test2_2019-02-21T04:36:09.567Z, type=index, dataSource=cnt_test2}] 
com.metamx.common.IAE: Cannot have overlapping dimensions and metrics of the same name. Please change the name of the metric. Overlap: [count] 
at io.druid.segment.indexing.DataSchema.createInputRowParser(DataSchema.java:160) ~[druid-server-0.9.1-SNAPSHOT.jar:0.9.1-SNAPSHOT] 
at io.druid.segment.indexing.DataSchema.getParser(DataSchema.java:125) ~[druid-server-0.9.1-SNAPSHOT.jar:0.9.1-SNAPSHOT] 
at io.druid.segment.indexing.IngestionSpec.getParser(IngestionSpec.java:66) ~[druid-server-0.9.1-SNAPSHOT.jar:0.9.1-SNAPSHOT] 
at io.druid.indexing.common.task.IndexTask.getDataIntervals(IndexTask.java:243) ~[druid-indexing-service-0.9.1-SNAPSHOT.jar:0.9.1-SNAPSHOT] 
at io.druid.indexing.common.task.IndexTask.run(IndexTask.java:201) ~[druid-indexing-service-0.9.1-SNAPSHOT.jar:0.9.1-SNAPSHOT] 
at io.druid.indexing.overlord.ThreadPoolTaskRunner$ThreadPoolTaskRunnerCallable.call(ThreadPoolTaskRunner.java:458) [druid-indexing-service-0.9.1-SNAPSHOT.jar:0.9.1-SNAPSHOT] 
at io.druid.indexing.overlord.ThreadPoolTaskRunner$ThreadPoolTaskRunnerCallable.call(ThreadPoolTaskRunner.java:430) [druid-indexing-service-0.9.1-SNAPSHOT.jar:0.9.1-SNAPSHOT] 
at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_171] 
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_171] 
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_171] 
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_171] 
```
or
```
2019-02-21T04:29:34,265 ERROR [task-runner-0-priority-0] io.druid.indexing.overlord.ThreadPoolTaskRunner - Exception while running task[IndexTask{id=index_cnt_test_2019-02-21T04:29:28.178Z, type=index, dataSource=cnt_test}] 
java.lang.IndexOutOfBoundsException: Index: 1, Size: 1 
at java.util.ArrayList.rangeCheck(ArrayList.java:657) ~[?:1.8.0_171] 
at java.util.ArrayList.get(ArrayList.java:433) ~[?:1.8.0_171] 
at io.druid.segment.IndexMergerV9.mergeIndexesAndWriteColumns(IndexMergerV9.java:662) ~[druid-processing-0.9.1-SNAPSHOT.jar:0.9.1-SNAPSHOT] 
at io.druid.segment.IndexMergerV9.makeIndexFiles(IndexMergerV9.java:220) ~[druid-processing-0.9.1-SNAPSHOT.jar:0.9.1-SNAPSHOT] 
at io.druid.segment.IndexMerger.merge(IndexMerger.java:492) ~[druid-processing-0.9.1-SNAPSHOT.jar:0.9.1-SNAPSHOT] 
at io.druid.segment.IndexMerger.persist(IndexMerger.java:205) ~[druid-processing-0.9.1-SNAPSHOT.jar:0.9.1-SNAPSHOT] 
at io.druid.segment.IndexMerger.persist(IndexMerger.java:171) ~[druid-processing-0.9.1-SNAPSHOT.jar:0.9.1-SNAPSHOT] 
at io.druid.segment.IndexMerger.persist(IndexMerger.java:149) ~[druid-processing-0.9.1-SNAPSHOT.jar:0.9.1-SNAPSHOT] 
at io.druid.indexing.common.index.YeOldePlumberSchool$1.spillIfSwappable(YeOldePlumberSchool.java:236) ~[druid-indexing-service-0.9.1-SNAPSHOT.jar:0.9.1-SNAPSHOT] 
at io.druid.indexing.common.index.YeOldePlumberSchool$1.persist(YeOldePlumberSchool.java:165) ~[druid-indexing-service-0.9.1-SNAPSHOT.jar:0.9.1-SNAPSHOT] 
at io.druid.indexing.common.task.IndexTask.generateSegment(IndexTask.java:434) ~[druid-indexing-service-0.9.1-SNAPSHOT.jar:0.9.1-SNAPSHOT] 
at io.druid.indexing.common.task.IndexTask.run(IndexTask.java:222) ~[druid-indexing-service-0.9.1-SNAPSHOT.jar:0.9.1-SNAPSHOT] 
at io.druid.indexing.overlord.ThreadPoolTaskRunner$ThreadPoolTaskRunnerCallable.call(ThreadPoolTaskRunner.java:458) [druid-indexing-service-0.9.1-SNAPSHOT.jar:0.9.1-SNAPSHOT] 
at io.druid.indexing.overlord.ThreadPoolTaskRunner$ThreadPoolTaskRunnerCallable.call(ThreadPoolTaskRunner.java:430) [druid-indexing-service-0.9.1-SNAPSHOT.jar:0.9.1-SNAPSHOT] 
at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_171] 
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_171] 
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_171] 
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_171] 
```
**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Additional context**

**Comment by kyungtaak** [comment]
@AnnieHwang @metatron-app/design 위의 내용을 해결하기위해서는 적재 시점에 필드명을 수정하는 기능이 필요할것으로 보입니다. (기획후 별도이슈로 진행 부탁드립니다.)

@ufoscw 이건은, 예약어일 경우 임의로 "_" 를 붙이는등 별도 우회경로가 필요할것 같네요. 이건은 릴리즈 계획을 별도로 수립하여 진행했으면 합니다.

**Comment by deidera08** [comment]
@kyungtaak @ufoscw @AnnieHwang 
데이터소스 적재 시점에서 컬럼명을 수정하는 이슈가 등록되어 있습니다.

#1202 스키마 설정시 컬럼명 수정
#1175 쿼리로 데이터소스 생성시 유효하지 않는 컬럼명일 경우 경고 띄움

참고 부탁드립니다

**Comment by ufoscw** [comment]
이 이슈에서는 워크벤치를 통한 임시 데이터 소스 생성시 예약어를 임의로 수정하는 부분을 처리하도록 하겠습니다.

@eltriny 
임시데이터 소스 생성 후 response에 dataSourceId가 포함되어 있습니다.
해당 dataSourceId로 datasource 상세 조회하여 datasource.fields 정보를 받아와서 차트 선반을 구성해야 합니다.
```
(GET) /api/datasources/{dataSourceId}?projection=forDetailView
```
