### ISSUE TITLE
Ordering of metric from aggregator should be considered whether it's finalized or not

### ISSUE THREAD

**Issue by navis** [metatron-app/metatron-discovery#1552]
Order by on cardinality aggregator throws exception like this
```
java.lang.ClassCastException: java.lang.Long cannot be cast to io.druid.query.aggregation.hyperloglog.HyperLogLogCollector
	at io.druid.query.aggregation.cardinality.CardinalityAggregatorFactory$2.compare(CardinalityAggregatorFactory.java:146) ~[classes/:?]
	at com.google.common.collect.ComparatorOrdering.compare(ComparatorOrdering.java:38) ~[guava-16.0.1.jar:?]
	at com.google.common.collect.NullsFirstOrdering.compare(NullsFirstOrdering.java:44) ~[guava-16.0.1.jar:?]
	at io.druid.query.groupby.orderby.WindowingProcessor$5.compare(WindowingProcessor.java:304) ~[classes/:?]
	at com.google.common.collect.ReverseOrdering.compare(ReverseOrdering.java:38) ~[guava-16.0.1.jar:?]
	at io.druid.query.ordering.Comparators$3.compare(Comparators.java:151) ~[classes/:?]
	at com.google.common.collect.ComparatorOrdering.compare(ComparatorOrdering.java:38) ~[guava-16.0.1.jar:?]
	at java.util.TimSort.countRunAndMakeAscending(TimSort.java:355) ~[?:1.8.0_202]
	at java.util.TimSort.sort(TimSort.java:234) ~[?:1.8.0_202]
	at java.util.ArraysParallelSortHelpers$FJObject$Sorter.compute(ArraysParallelSortHelpers.java:145) ~[?:1.8.0_202]
	at java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:731) ~[?:1.8.0_202]
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289) ~[?:1.8.0_202]
	at java.util.concurrent.ForkJoinTask.doInvoke(ForkJoinTask.java:401) ~[?:1.8.0_202]
	at java.util.concurrent.ForkJoinTask.invoke(ForkJoinTask.java:734) ~[?:1.8.0_202]
	at java.util.Arrays.parallelSort(Arrays.java:1119) ~[?:1.8.0_202]
	at io.druid.query.groupby.orderby.LimitSpec$SortingFn.apply(LimitSpec.java:239) ~[classes/:?]
	at io.druid.query.groupby.orderby.LimitSpec$SortingFn.apply(LimitSpec.java:217) ~[classes/:?]
	at io.druid.query.BaseAggregationQuery.applyLimit(BaseAggregationQuery.java:212) ~[classes/:?]
	at io.druid.query.BaseAggregationQueryToolChest.finalDecoration(BaseAggregationQueryToolChest.java:385) ~[classes/:?]
	at io.druid.query.BaseAggregationQueryToolChest.access$100(BaseAggregationQueryToolChest.java:58) ~[classes/:?]
	at io.druid.query.BaseAggregationQueryToolChest$11.run(BaseAggregationQueryToolChest.java:376) ~[classes/:?]
	at io.druid.query.PostProcessingOperators$1.run(PostProcessingOperators.java:46) ~[classes/:?]
	at io.druid.query.FluentQueryRunnerBuilder$1.run(FluentQueryRunnerBuilder.java:103) ~[classes/:?]
	at io.druid.query.BaseQuery.run(BaseQuery.java:290) ~[classes/:?]
	at io.druid.query.BaseQuery.run(BaseQuery.java:284) ~[classes/:?]

```

**Comment by navis** [comment]
Fixed
