### ISSUE TITLE
Suppress exception when druid-hdfs-module is configured but not used

### ISSUE THREAD

**Issue by navis** [metatron-app/metatron-discovery#1578]
```
1 error
	at com.google.inject.internal.InjectorImpl$2.get(InjectorImpl.java:1028) ~[guice-4.1.0.jar:?]
	at com.google.inject.internal.InjectorImpl.getInstance(InjectorImpl.java:1050) ~[guice-4.1.0.jar:?]
	at io.druid.guice.LifecycleModule$2.start(LifecycleModule.java:153) ~[druid-common-0.9.1-SNAPSHOT.jar:0.9.1-SNAPSHOT]
	at io.druid.cli.GuiceRunnable.initLifecycle(GuiceRunnable.java:97) [druid-services-0.9.1-SNAPSHOT.jar:0.9.1-SNAPSHOT]
	at io.druid.cli.CliPeon.run(CliPeon.java:292) [druid-services-0.9.1-SNAPSHOT.jar:0.9.1-SNAPSHOT]
	at io.druid.cli.Main.main(Main.java:128) [druid-services-0.9.1-SNAPSHOT.jar:0.9.1-SNAPSHOT]
Caused by: java.lang.IllegalArgumentException: Can not create a Path from an empty string
	at org.apache.hadoop.fs.Path.checkPathArg(Path.java:126) ~[?:?]
	at org.apache.hadoop.fs.Path.<init>(Path.java:134) ~[?:?]
	at io.druid.storage.hdfs.HdfsDataSegmentKiller.<init>(HdfsDataSegmentKiller.java:47) ~[?:?]
	at io.druid.storage.hdfs.HdfsDataSegmentKiller$$FastClassByGuice$$2d8e784d.newInstance(<generated>) ~[?:?]
```

**Comment by navis** [comment]
Fixed
