### ISSUE TITLE
TypeResolver in WindowContext returns invalid type for post-aggregated column

### ISSUE THREAD

**Issue by navis** [metatron-app/metatron-discovery#1580]
Regression from #1156 

```
java.lang.NullPointerException
    at io.druid.math.expr.BuiltinFunctions$RunningSum.invoke(BuiltinFunctions.java:2696) ~[druid-common-0.9.1-SNAPSHOT.jar:0.9.1-SNAPSHOT]
    at io.druid.math.expr.BuiltinFunctions$WindowSupport.invoke(BuiltinFunctions.java:2502) ~[druid-common-0.9.1-SNAPSHOT.jar:0.9.1-SNAPSHOT]
    at io.druid.math.expr.BuiltinFunctions$PartitionFunction.apply(BuiltinFunctions.java:2424) ~[druid-common-0.9.1-SNAPSHOT.jar:0.9.1-SNAPSHOT]
    at io.druid.math.expr.FunctionExpr.eval(Expr.java:357) ~[druid-common-0.9.1-SNAPSHOT.jar:0.9.1-SNAPSHOT]
    at io.druid.query.groupby.orderby.WindowContext._evaluate(WindowContext.java:155) ~[druid-processing-0.9.1-SNAPSHOT.jar:0.9.1-SNAPSHOT]
    at io.druid.query.groupby.orderby.WindowContext.evaluate(WindowContext.java:125) ~[druid-processing-0.9.1-SNAPSHOT.jar:0.9.1-SNAPSHOT]
    at io.druid.query.groupby.orderby.PivotSpec$1.finalize(PivotSpec.java:350) ~[druid-processing-0.9.1-SNAPSHOT.jar:0.9.1-SNAPSHOT]
    at io.druid.query.groupby.orderby.WindowingSpec$3.finalize(WindowingSpec.java:380) ~[druid-processing-0.9.1-SNAPSHOT.jar:0.9.1-SNAPSHOT]
    at io.druid.query.groupby.orderby.WindowingProcessor$PartitionDefinition.process(WindowingProcessor.java:158) ~[druid-processing-0.9.1-SNAPSHOT.jar:0.9.1-SNAPSHOT]
    at io.druid.query.groupby.orderby.WindowingProcessor$PartitionDefinition.access$200(WindowingProcessor.java:94) ~[druid-processing-0.9.1-SNAPSHOT.jar:0.9.1-SNAPSHOT]
    at io.druid.query.groupby.orderby.WindowingProcessor.apply(WindowingProcessor.java:88) ~[druid-processing-0.9.1-SNAPSHOT.jar:0.9.1-SNAPSHOT]
    at io.druid.query.groupby.orderby.WindowingProcessor.apply(WindowingProcessor.java:49) ~[druid-processing-0.9.1-SNAPSHOT.jar:0.9.1-SNAPSHOT]
    at com.google.common.base.Functions$FunctionComposition.apply(Functions.java:211) ~[guava-16.0.1.jar:?]
    at com.google.common.base.Functions$FunctionComposition.apply(Functions.java:211) ~[guava-16.0.1.jar:?]
    at io.druid.query.BaseAggregationQuery.applyLimit(BaseAggregationQuery.java:212) ~[druid-processing-0.9.1-SNAPSHOT.jar:0.9.1-SNAPSHOT]
    at io.druid.query.BaseAggregationQueryToolChest.finalDecoration(BaseAggregationQueryToolChest.java:385) ~[druid-processing-0.9.1-SNAPSHOT.jar:0.9.1-SNAPSHOT]
```

**Comment by navis** [comment]
Fixed
