### ISSUE TITLE
Fix test fail of TestShapeQuery

### ISSUE THREAD

**Issue by navis** [metatron-app/metatron-discovery#1692]
I don't know why this happens. Individual running of the test works.
```
Caused by: java.lang.RuntimeException: com.fasterxml.jackson.databind.JsonMappingException: Could not resolve type id 'shape' into a subtype of [simple type, class io.druid.segment.lucene.LuceneIndexingStrategy]
 at [Source: java.io.InputStreamReader@ef60710; line: 28, column: 12] (through reference chain: java.util.LinkedHashMap["geom"]->java.util.ArrayList[0])
	at com.google.common.base.Throwables.propagate(Throwables.java:160)
	at io.druid.segment.TestIndex.loadJson(TestIndex.java:357)
	at io.druid.segment.TestIndex.addIndex(TestIndex.java:236)
	at io.druid.query.TestShapeQuery.<clinit>(TestShapeQuery.java:41)
	... 29 more
Caused by: com.fasterxml.jackson.databind.JsonMappingException: Could not resolve type id 'shape' into a subtype of [simple type, class io.druid.segment.lucene.LuceneIndexingStrategy]
 at [Source: java.io.InputStreamReader@ef60710; line: 28, column: 12] (through reference chain: java.util.LinkedHashMap["geom"]->java.util.ArrayList[0])
	at com.fasterxml.jackson.databind.JsonMappingException.from(JsonMappingException.java:148)
```

**Comment by navis** [comment]
Fixed
