### ISSUE TITLE
Improve java version compatibility

### ISSUE THREAD

**Issue by alchan-lee** [metatron-app/metatron-discovery#1704]
**Is your feature request related to a problem? Please describe.**
We officially suggest jdk 8, but need to support upper versions.

**Describe the solution you'd like**
Need to upgrade libraries and check our java apis

**Additional context**
In the short term testing, I found incompatibility in Lucene as follow

`
Caused by: java.io.IOException: Unable to unmap the mapped buffer: MMapIndexInput(path="/apps/metatron-discovery-3.2.0-rc4-20190321091004/indexes/app.metatron.discovery.domain.user.group.Group/segments_1")
	at org.apache.lucene.store.MMapDirectory$2.freeBuffer(MMapDirectory.java:329)
	at org.apache.lucene.store.ByteBufferIndexInput.freeBuffer(ByteBufferIndexInput.java:376)
	at org.apache.lucene.store.ByteBufferIndexInput.close(ByteBufferIndexInput.java:355)
	at org.apache.lucene.store.BufferedChecksumIndexInput.close(BufferedChecksumIndexInput.java:60)
	at org.apache.lucene.index.SegmentInfos.readCommit(SegmentInfos.java:459)
	at org.apache.lucene.index.StandardDirectoryReader$1.doBody(StandardDirectoryReader.java:53)
	at org.apache.lucene.index.StandardDirectoryReader$1.doBody(StandardDirectoryReader.java:50)
	at org.apache.lucene.index.SegmentInfos$FindSegmentsFile.run(SegmentInfos.java:731)
	at org.apache.lucene.index.StandardDirectoryReader.open(StandardDirectoryReader.java:50)
	at org.apache.lucene.index.DirectoryReader.open(DirectoryReader.java:63)
	at org.hibernate.search.indexes.impl.SharingBufferReaderProvider.readerFactory(SharingBufferReaderProvider.java:131)
	at org.hibernate.search.indexes.impl.SharingBufferReaderProvider$PerDirectoryLatestReader.<init>(SharingBufferReaderProvider.java:206)
	at org.hibernate.search.indexes.impl.SharingBufferReaderProvider.createReader(SharingBufferReaderProvider.java:108)
	... 178 common frames omitted
Caused by: java.lang.IllegalAccessException: class org.apache.lucene.store.MMapDirectory$2$1 cannot access class jdk.internal.ref.Cleaner (in module java.base) because module java.base does not export jdk.internal.ref to unnamed module @e4d2696
	at java.base/jdk.internal.reflect.Reflection.newIllegalAccessException(Reflection.java:361)
	at java.base/java.lang.reflect.AccessibleObject.checkAccess(AccessibleObject.java:591)
	at java.base/java.lang.reflect.Method.invoke(Method.java:558)
	at org.apache.lucene.store.MMapDirectory$2$1.run(MMapDirectory.java:322)
	at org.apache.lucene.store.MMapDirectory$2$1.run(MMapDirectory.java:314)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at org.apache.lucene.store.MMapDirectory$2.freeBuffer(MMapDirectory.java:314)
	... 190 common frames omitted
`

**Comment by alchan-lee** [comment]
Ah... I've resolved the problem with dependencies of 3rd-party libraries.
But I got a result that it has to be preceded to upgrading spring boot to upper 2.1.

It will take longer to resolve than I thought.
