### ISSUE TITLE
Fix NPE in hadoop task

### ISSUE THREAD

**Issue by navis** [metatron-app/metatron-discovery#1765]
Regression from #1703 

```
Error: java.lang.NullPointerException
	at io.druid.indexer.ReduceMergeIndexGeneratorJob$ReducerMergingReducer.reduce(ReduceMergeIndexGeneratorJob.java:610)
	at io.druid.indexer.ReduceMergeIndexGeneratorJob$ReducerMergingReducer.reduce(ReduceMergeIndexGeneratorJob.java:512)
	at org.apache.hadoop.mapreduce.Reducer.run(Reducer.java:171)
	at org.apache.hadoop.mapred.ReduceTask.runNewReducer(ReduceTask.java:627)
	at org.apache.hadoop.mapred.ReduceTask.run(ReduceTask.java:389)
	at org.apache.hadoop.mapred.YarnChild$2.run(YarnChild.java:164)
	at java.security.AccessController.doPrivileged(Native Method)
	at javax.security.auth.Subject.doAs(Subject.java:422)
	at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1698)
	at org.apache.hadoop.mapred.YarnChild.main(YarnChild.java:158)
```

**Comment by ufoscw** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [staging db 데이터소스 생성 시 fail 되는 케이스 문의 (링크포함)](https://trello.com/c/19npqCcV/99-staging-db-%EB%8D%B0%EC%9D%B4%ED%84%B0%EC%86%8C%EC%8A%A4-%EC%83%9D%EC%84%B1-%EC%8B%9C-fail-%EB%90%98%EB%8A%94-%EC%BC%80%EC%9D%B4%EC%8A%A4-%EB%AC%B8%EC%9D%98)

**Comment by navis** [comment]
Fixed
