### ISSUE TITLE
Configure hadoop aware parser in index task using hadoop firehose

### ISSUE THREAD

**Issue by navis** [metatron-app/metatron-discovery#1766]
```
o.druid.data.ParsingFail:  from {1111877, 134177, 1717, 3, 20, 24223.4, 0.1, 0.07, A, F, 1992-01-02, 1992-02-28, 1992-01-07, TAKE BACK RETURN, FOB, re. ideas wake }
	at io.druid.data.ParsingFail.propagate(ParsingFail.java:63) ~[druid-common-0.9.1-SNAPSHOT.jar:0.9.1-SNAPSHOT]
	at io.druid.data.input.orc.OrcHadoopInputRowParser.parse(OrcHadoopInputRowParser.java:163) ~[?:?]
	at io.druid.data.input.orc.OrcHadoopInputRowParser.parse(OrcHadoopInputRowParser.java:86) ~[?:?]
	at io.druid.firehose.hadoop.HadoopFirehoseFactory$2.nextRow(HadoopFirehoseFactory.java:160) ~[?:?]
	at io.druid.indexing.common.task.IndexTask.getDataIntervals(IndexTask.java:284) ~[druid-indexing-service-0.9.1-SNAPSHOT.jar:0.9.1-SNAPSHOT]
	at io.druid.indexing.common.task.IndexTask.run(IndexTask.java:216) ~[druid-indexing-service-0.9.1-SNAPSHOT.jar:0.9.1-SNAPSHOT]
	at io.druid.indexing.overlord.ThreadPoolTaskRunner$ThreadPoolTaskRunnerCallable.call(ThreadPoolTaskRunner.java:458) [druid-indexing-service-0.9.1-SNAPSHOT.jar:0.9.1-SNAPSHOT]
	at io.druid.indexing.overlord.ThreadPoolTaskRunner$ThreadPoolTaskRunnerCallable.call(ThreadPoolTaskRunner.java:430) [druid-indexing-service-0.9.1-SNAPSHOT.jar:0.9.1-SNAPSHOT]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_202]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_202]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_202]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_202]
Caused by: java.lang.NullPointerException
	at io.druid.data.input.orc.OrcHadoopInputRowParser.getObjectInspector(OrcHadoopInputRowParser.java:206) ~[?:?]
	at io.druid.data.input.orc.OrcHadoopInputRowParser.parse(OrcHadoopInputRowParser.java:130) ~[?:?]
	... 10 more
```

**Comment by navis** [comment]
Fixed
