### ISSUE TITLE
Fix NPE in selector filter with null on non-string column

### ISSUE THREAD

**Issue by navis** [metatron-app/metatron-discovery#1797]
Regression from #1703 
```
java.lang.NullPointerException
	at io.druid.segment.filter.SelectorFilter$3.apply(SelectorFilter.java:151) ~[classes/:?]
	at io.druid.segment.filter.Filters$2.matches(Filters.java:193) ~[classes/:?]
	at io.druid.segment.filter.AndFilter$1.matches(AndFilter.java:106) ~[classes/:?]
	at io.druid.segment.filter.OrFilter$1.matches(OrFilter.java:121) ~[classes/:?]
	at io.druid.segment.ColumnSelectorFactories$2$1.hasNext(ColumnSelectorFactories.java:921) ~[classes/:?]
	at io.druid.segment.ColumnSelectorFactories$2$2.advance(ColumnSelectorFactories.java:955) ~[classes/:?]
	at io.druid.query.select.StreamQueryEngine$1$1$1.next(StreamQueryEngine.java:142) ~[classes/:?]
	at io.druid.query.select.StreamQueryEngine$1$1$1.next(StreamQueryEngine.java:125) ~[classes/:?]
	at com.metamx.common.guava.BaseSequence.makeYielder(BaseSequence.java:105) ~[java-util-1.3.3.jar:?]
	at com.metamx.common.guava.BaseSequence.access$100(BaseSequence.java:28) ~[java-util-1.3.3.jar:?]
	at com.metamx.common.guava.BaseSequence$3.next(BaseSequence.java:136) ~[java-util-1.3.3.jar:?]
	at com.metamx.common.guava.ConcatSequence$3.next(ConcatSequence.java:141) ~[java-util-1.3.3.jar:?]
	at io.druid.common.utils.Sequences$7.next(Sequences.java:266) ~[classes/:?]
	at com.google.common.collect.Iterators$PeekingImpl.next(Iterators.java:1145) ~[guava-16.0.1.jar:?]
	at io.druid.common.guava.GuavaUtils$12.next(GuavaUtils.java:564) ~[classes/:?]
	at io.druid.query.XJoinPostProcessor.hashJoin(XJoinPostProcessor.java:604) ~[classes/:?]
	at io.druid.query.XJoinPostProcessor.access$1900(XJoinPostProcessor.java:64) ~[classes/:?]
	at io.druid.query.XJoinPostProcessor$8.next(XJoinPostProcessor.java:408) ~[classes/:?]
	at io.druid.query.XJoinPostProcessor$JoinIterator.hasNext(XJoinPostProcessor.java:470) ~[classes/:?]
	at com.metamx.common.guava.BaseSequence.makeYielder(BaseSequence.java:104) ~[java-util-1.3.3.jar:?]
	at com.metamx.common.guava.BaseSequence.access$100(BaseSequence.java:28) ~[java-util-1.3.3.jar:?]
	at com.metamx.common.guava.BaseSequence$3.next(BaseSequence.java:136) ~[java-util-1.3.3.jar:?]
	at io.druid.common.utils.Sequences$7.next(Sequences.java:266) ~[classes/:?]
	at com.google.common.collect.Iterators$PeekingImpl.peek(Iterators.java:1162) ~[guava-16.0.1.jar:?]
	at io.druid.common.guava.GuavaUtils.peek(GuavaUtils.java:758) ~[classes/:?]
	at io.druid.segment.ColumnSelectorFactories$2$1.hasNext(ColumnSelectorFactories.java:918) ~[classes/:?]
	at io.druid.segment.ColumnSelectorFactories$2$2.advance(ColumnSelectorFactories.java:955) ~[classes/:?]
	at io.druid.query.groupby.GroupByQueryEngine$RowIterator.hasNext(GroupByQueryEngine.java:299) ~[classes/:?]
	at com.metamx.common.guava.BaseSequence.accumulate(BaseSequence.java:66) ~[java-util-1.3.3.jar:?]
	at com.metamx.common.guava.MappedSequence.accumulate(MappedSequence.java:40) ~[java-util-1.3.3.jar:?]
	at com.metamx.common.guava.ConcatSequence$1.accumulate(ConcatSequence.java:46) ~[java-util-1.3.3.jar:?]
	at com.metamx.common.guava.ConcatSequence$1.accumulate(ConcatSequence.java:42) ~[java-util-1.3.3.jar:?]
	at com.metamx.common.guava.MappingAccumulator.accumulate(MappingAccumulator.java:39) ~[java-util-1.3.3.jar:?]
	at com.metamx.common.guava.FilteringAccumulator.accumulate(FilteringAccumulator.java:40) ~[java-util-1.3.3.jar:?]
	at com.metamx.common.guava.MappingAccumulator.accumulate(MappingAccumulator.java:39) ~[java-util-1.3.3.jar:?]
	at com.metamx.common.guava.BaseSequence.accumulate(BaseSequence.java:67) ~[java-util-1.3.3.jar:?]
	at com.metamx.common.guava.MappedSequence.accumulate(MappedSequence.java:40) ~[java-util-1.3.3.jar:?]
	at com.metamx.common.guava.FilteredSequence.accumulate(FilteredSequence.java:42) ~[java-util-1.3.3.jar:?]
	at com.metamx.common.guava.ResourceClosingSequence.accumulate(ResourceClosingSequence.java:38) ~[java-util-1.3.3.jar:?]
	at com.metamx.common.guava.MappedSequence.accumulate(MappedSequence.java:40) ~[java-util-1.3.3.jar:?]
	at com.metamx.common.guava.ConcatSequence.accumulate(ConcatSequence.java:40) ~[java-util-1.3.3.jar:?]
	at com.metamx.common.guava.MappedSequence.accumulate(MappedSequence.java:40) ~[java-util-1.3.3.jar:?]
	at com.metamx.common.guava.MappedSequence.accumulate(MappedSequence.java:40) ~[java-util-1.3.3.jar:?]
	at io.druid.common.utils.Sequences.toList(Sequences.java:122) ~[classes/:?]
```

**Comment by navis** [comment]
Fixed
