### ISSUE TITLE
Fix NPE purging on non-existing table

### ISSUE THREAD

**Issue by navis** [metatron-app/metatron-discovery#1830]
```
2019-04-09T02:52:50,029 WARN [qtp2002534484-80] org.eclipse.jetty.servlet.ServletHandler - /druid/coordinator/v1/datasources/sjdfklsdjfkl/purge
org.skife.jdbi.v2.exceptions.CallbackFailedException: java.lang.NullPointerException
	at org.skife.jdbi.v2.DBI.withHandle(DBI.java:284) ~[jdbi-2.63.1.jar:2.63.1]
	at io.druid.metadata.SQLMetadataSegmentManager.inReadOnlyTransaction(SQLMetadataSegmentManager.java:172) ~[druid-server-0.9.1-SNAPSHOT.jar:0.9.1-SNAPSHOT]
	at io.druid.metadata.SQLMetadataSegmentManager.getUmbrellaInterval(SQLMetadataSegmentManager.java:734) ~[druid-server-0.9.1-SNAPSHOT.jar:0.9.1-SNAPSHOT]
	at io.druid.server.http.DatasourcesResource.purgeDataSource(DatasourcesResource.java:345) ~[druid-server-0.9.1-SNAPSHOT.jar:0.9.1-SNAPSHOT]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_202]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_202]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_202]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_202]
	at com.sun.jersey.spi.container.JavaMethodInvokerFactory$1.invoke(JavaMethodInvokerFactory.java:60) ~[jersey-server-1.19.jar:1.19]
	at com.sun.jersey.server.impl.model.method.dispatch.AbstractResourceMethodDispatchProvider$ResponseOutInvoker._dispatch(AbstractResourceMethodDispatchProvider.java:205) ~[jersey-server-1.19.jar:1.19]


Caused by: java.lang.NullPointerException
	at org.joda.time.format.DateTimeFormatterBuilder$CharacterLiteral.parseInto(DateTimeFormatterBuilder.java:1224) ~[joda-time-2.8.2.jar:2.8.2]
	at org.joda.time.format.DateTimeFormatterBuilder$Composite.parseInto(DateTimeFormatterBuilder.java:2462) ~[joda-time-2.8.2.jar:2.8.2]
	at org.joda.time.format.InternalParserDateTimeParser.parseInto(InternalParserDateTimeParser.java:52) ~[joda-time-2.8.2.jar:2.8.2]
	at org.joda.time.format.DateTimeFormatterBuilder$MatchingParser.parseInto(DateTimeFormatterBuilder.java:2556) ~[joda-time-2.8.2.jar:2.8.2]
	at org.joda.time.format.DateTimeFormatter.parseDateTime(DateTimeFormatter.java:879) ~[joda-time-2.8.2.jar:2.8.2]
	at org.joda.time.DateTime.parse(DateTime.java:160) ~[joda-time-2.8.2.jar:2.8.2]
	at org.joda.time.DateTime.parse(DateTime.java:149) ~[joda-time-2.8.2.jar:2.8.2]
	at io.druid.metadata.SQLMetadataSegmentManager$13$1.mapInternal(SQLMetadataSegmentManager.java:756) ~[druid-server-0.9.1-SNAPSHOT.jar:0.9.1-SNAPSHOT]
	at io.druid.metadata.SQLMetadataSegmentManager$13$1.mapInternal(SQLMetadataSegmentManager.java:751) ~[druid-server-0.9.1-SNAPSHOT.
```

**Comment by navis** [comment]
Fixed
