### ISSUE TITLE
Use classloader of lucene-extension as parent of geotools-extension

### ISSUE THREAD

**Issue by navis** [metatron-app/metatron-discovery#1855]
```
java.lang.ClassCastException: org.locationtech.spatial4j.shape.jts.JtsPoint cannot be cast to org.locationtech.spatial4j.shape.Shape
	at io.druid.query.H3Functions.toGeometry(H3Functions.java:64) ~[?:?]
	at io.druid.query.H3Functions$GeomToH3$1.apply(H3Functions.java:113) ~[?:?]
	at io.druid.math.expr.FunctionExpr.eval(Expr.java:394) ~[druid-common-0.9.1-SNAPSHOT.jar:0.9.1-SNAPSHOT]
	at io.druid.segment.ColumnSelectorFactory$ExprSupport$1.get(ColumnSelectorFactory.java:88) ~[druid-processing-0.9.1-SNAPSHOT.jar:0.9.1-SNAPSHOT]
	at io.druid.segment.ColumnSelectors$15.get(ColumnSelectors.java:284) ~[druid-processing-0.9.1-SNAPSHOT.jar:0.9.1-SNAPSHOT]
	at io.druid.segment.VirtualColumns$2.get(VirtualColumns.java:165) ~[druid-processing-0.9.1-SNAPSHOT.jar:0.9.1-SNAPSHOT]
	at io.druid.segment.VirtualColumns$2.get(VirtualColumns.java:161) ~[druid-processing-0.9.1-SNAPSHOT.jar:0.9.1-SNAPSHOT]
	at io.druid.segment.VirtualColumns$MimicDimension.getRow(VirtualColumns.java:197) ~[druid-processing-0.9.1-SNAPSHOT.jar:0.9.1-SNAPSHOT]
```

Two class loaders are conflicting..

**Comment by navis** [comment]
Fixed
