### ISSUE TITLE
Fix CCE for forwarding on select query

### ISSUE THREAD

**Issue by navis** [metatron-app/metatron-discovery#1886]
```
java.lang.ClassCastException: java.util.LinkedHashMap cannot be cast to io.druid.query.Result
	at io.druid.query.select.SelectQueryQueryToolChest$6.applyAsInt(SelectQueryQueryToolChest.java:298) ~[druid-processing-0.9.1-SNAPSHOT.jar:0.9.1-SNAPSHOT]
	at io.druid.server.QueryResource$1.accumulate(QueryResource.java:272) ~[druid-server-0.9.1-SNAPSHOT.jar:0.9.1-SNAPSHOT]
	at com.metamx.common.guava.BaseSequence.makeYielder(BaseSequence.java:105) ~[java-util-1.3.3.jar:?]
	at com.metamx.common.guava.BaseSequence.toYielder(BaseSequence.java:82) ~[java-util-1.3.3.jar:?]
	at com.metamx.common.guava.ResourceClosingSequence.toYielder(ResourceClosingSequence.java:52) ~[java-util-1.3.3.jar:?]
	at io.druid.server.QueryResource.doPost(QueryResource.java:263) [druid-server-0.9.1-SNAPSHOT.jar:0.9.1-SNAPSHOT]
```

**Comment by kyungtaak** [comment]
We have confirmed this issue. It will be included in the druid binaries distributed with the 3.2.1 release. :)

**Comment by navis** [comment]
Fixed
