### ISSUE TITLE
Remove deprecated methods of guava

### ISSUE THREAD

**Issue by navis** [metatron-app/metatron-discovery#1924]
Related to #1913

```
2019-04-23T04:31:39,154 INFO [main] io.druid.indexer.ReduceMergeIndexGeneratorJob - Flushing index of tpch_10_lineitem_01 (1996-01-01T00:00:00.000Z/1997-01-01T00:00:00.000Z).. 74,267 rows with estimated size 83,175,342 bytes accumulated during 10,056 msec
2019-04-23T04:31:39,154 INFO [main] io.druid.segment.IndexMerger - Starting persist for interval[1996-01-01T00:00:00.000Z/1997-01-01T00:00:00.000Z], rows[74,267]
2019-04-23T04:31:39,330 INFO [main] io.druid.segment.IndexMergerV9 - Start making v9 index files from 1 indices, outDir:/data7/hadoop/yarn/local/usercache/hdfs/appcache/application_1555993786874_0002/container_e04_1555993786874_0002_01_000003/tmp/base674399021063670961flush/index-00002
2019-04-23T04:31:39,331 WARN [main] io.druid.indexer.HadoopDruidIndexerMapper - Ignoring invalid [3]th row [5707461|1014015|89046|2|26|24152.96|0.05|0.01|N|O|1997-06-19|1997-06-30|1997-06-23|TAKE BACK RETURN|RAIL|eans detect slyly: express foxes|] due to parsing error.. 
java.lang.NoSuchMethodError: com.google.common.io.Files.newOutputStreamSupplier(Ljava/io/File;)Lcom/google/common/io/OutputSupplier;
	at io.druid.segment.IndexMergerV9.makeIndexFiles(IndexMergerV9.java:170) ~[druid-processing-0.9.1-SNAPSHOT.jar:0.9.1-SNAPSHOT]
	at io.druid.segment.IndexMerger.merge(IndexMerger.java:491) ~[druid-processing-0.9.1-SNAPSHOT.jar:0.9.1-SNAPSHOT]
	at io.druid.segment.IndexMerger.persist(IndexMerger.java:204) ~[druid-processing-0.9.1-SNAPSHOT.jar:0.9.1-SNAPSHOT]
	at io.druid.indexer.ReduceMergeIndexGeneratorJob$ReducerMergingMapper.persist(ReduceMergeIndexGeneratorJob.java:426) ~[druid-indexing-hadoop-0.9.1-SNAPSHOT.jar:0.9.1-SNAPSHOT]
	at io.druid.indexer.ReduceMergeIndexGeneratorJob$ReducerMergingMapper.persistOneIndex(ReduceMergeIndexGeneratorJob.java:372) ~[druid-indexing-hadoop-0.9.1-SNAPSHOT.jar:0.9.1-SNAPSHOT]
	at io.druid.indexer.ReduceMergeIndexGeneratorJob$ReducerMergingMapper.innerMap(ReduceMergeIndexGeneratorJob.java:276) ~[druid-indexing-hadoop-0.9.1-SNAPSHOT.jar:0.9.1-SNAPSHOT]
	at io.druid.indexer.HadoopDruidIndexerMapper.map(HadoopDruidIndexerMapper.java:102) [druid-indexing-hadoop-0.9.1-SNAPSHOT.jar:0.9.1-SNAPSHOT]
	at io.druid.indexer.ReduceMergeIndexGeneratorJob$ReducerMergingMapper.run(ReduceMergeIndexGeneratorJob.java:188) [druid-indexing-hadoop-0.9.1-SNAPSHOT.jar:0.9.1-SNAPSHOT]
	at org.apache.hadoop.mapred.MapTask.runNewMapper(MapTask.java:799) [hadoop-mapreduce-client-core-3.1.1.3.1.2.0-4.jar:?]
	at org.apache.hadoop.mapred.MapTask.run(MapTask.java:347) [hadoop-mapreduce-client-core-3.1.1.3.1.2.0-4.jar:?]
	at org.apache.hadoop.mapred.YarnChild$2.run(YarnChild.java:174) [hadoop-mapreduce-client-app-3.1.1.3.1.0.0-78.jar:?]
	at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_112]
	at javax.security.auth.Subject.doAs(Subject.java:422) [?:1.8.0_112]
	at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1730) [hadoop-common-3.1.1.3.1.2.0-4.jar:?]
	at org.apache.hadoop.mapred.YarnChild.main(YarnChild.java:168) [hadoop-mapreduce-client-app-3.1.1.3.1.0.0-78.jar:?]
```

**Comment by navis** [comment]
Done
