### ISSUE TITLE
Possible maximum number of rows exception when multiple-indexing in mapper

### ISSUE THREAD

**Issue by navis** [metatron-app/metatron-discovery#1926]
If current index is full, it should be considered first.
```
io.druid.segment.incremental.IndexSizeExceededException: Maximum number of rows [75000] reached
	at io.druid.segment.incremental.OnheapIncrementalIndex.addToFacts(OnheapIncrementalIndex.java:202) ~[druid-processing-0.9.1-SNAPSHOT.jar:0.9.1-SNAPSHOT]
	at io.druid.segment.incremental.IncrementalIndex.addTimeAndDims(IncrementalIndex.java:445) ~[druid-processing-0.9.1-SNAPSHOT.jar:0.9.1-SNAPSHOT]
	at io.druid.segment.incremental.IncrementalIndex.add(IncrementalIndex.java:440) ~[druid-processing-0.9.1-SNAPSHOT.jar:0.9.1-SNAPSHOT]
	at io.druid.indexer.ReduceMergeIndexGeneratorJob$IntervalIndex.addRow(ReduceMergeIndexGeneratorJob.java:507) ~[druid-indexing-hadoop-0.9.1-SNAPSHOT.jar:0.9.1-SNAPSHOT]
	at io.druid.indexer.ReduceMergeIndexGeneratorJob$ReducerMergingMapper.innerMap(ReduceMergeIndexGeneratorJob.java:289) ~[druid-indexing-hadoop-0.9.1-SNAPSHOT.jar:0.9.1-SNAPSHOT]
	at io.druid.indexer.HadoopDruidIndexerMapper.map(HadoopDruidIndexerMapper.java:102) [druid-indexing-hadoop-0.9.1-SNAPSHOT.jar:0.9.1-SNAPSHOT]
	at io.druid.indexer.ReduceMergeIndexGeneratorJob$ReducerMergingMapper.run(ReduceMergeIndexGeneratorJob.java:188) [druid-indexing-hadoop-0.9.1-SNAPSHOT.jar:0.9.1-SNAPSHOT]
```

**Comment by navis** [comment]
Done
