### ISSUE TITLE
Fix CCE when rectangle is given as polygon type

### ISSUE THREAD

**Issue by navis** [metatron-app/metatron-discovery#1994]
```
2019-05-02T08:04:37,966 ERROR [processing-0] io.druid.query.ChainedExecutionQueryRunner - Exception with one of the sequences!
java.lang.ClassCastException: org.locationtech.spatial4j.shape.impl.RectangleImpl cannot be cast to org.locationtech.spatial4j.shape.jts.JtsGeometry
	at io.druid.data.EnvelopeAggregatorFactory$1.aggregate(EnvelopeAggregatorFactory.java:81) ~[?:?]
	at io.druid.query.timeseries.TimeseriesQueryEngine$1.apply(TimeseriesQueryEngine.java:84) ~[druid-processing-0.9.1-SNAPSHOT.jar:0.9.1-SNAPSHOT]
	at io.druid.query.timeseries.TimeseriesQueryEngine$1.apply(TimeseriesQueryEngine.java:68) ~[druid-processing-0.9.1-SNAPSHOT.jar:0.9.1-SNAPSHOT]
	at com.metamx.common.guava.MappingAccumulator.accumulate(MappingAccumulator.java:39) ~[java-util-1.3.3.jar:?]
```

**Comment by navis** [comment]
Fixed
