### ISSUE TITLE
Fix CCE on covariance query

### ISSUE THREAD

**Issue by navis** [metatron-app/metatron-discovery#2026]
```
java.lang.ClassCastException: io.druid.query.aggregation.covariance.CovarianceQuery cannot be cast to io.druid.query.BaseAggregationQuery
        at io.druid.query.BaseAggregationQueryToolChest.numRows(BaseAggregationQueryToolChest.java:59) ~[druid-processing-0.9.1-SNAPSHOT.jar:0.9.1-SNAPSHOT]
        at io.druid.query.QueryToolChest.numRows(QueryToolChest.java:179) ~[druid-processing-0.9.1-SNAPSHOT.jar:0.9.1-SNAPSHOT]
        at io.druid.server.QueryResource$1.<init>(QueryResource.java:267) ~[druid-server-0.9.1-SNAPSHOT.jar:0.9.1-SNAPSHOT]
        at io.druid.server.QueryResource.doPost(QueryResource.java:263) [druid-server-0.9.1-SNAPSHOT.jar:0.9.1-SNAPSHOT]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_202]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_202]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_202]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_202]
```

**Comment by navis** [comment]
Fixed
