### ISSUE TITLE
Fix ArrayStoreException when time column is also a dimension

### ISSUE THREAD

**Issue by navis** [metatron-app/metatron-discovery#2035]
```
2019-05-09T23:55:44,760 INFO [qtp62190059-116] io.druid.segment.IndexMergerV9 - Completed version.bin in 7 millis.
2019-05-09T23:55:44,786 WARN [qtp62190059-116] io.druid.server.QueryResource - Failed loading
java.lang.ArrayStoreException: org.joda.time.DateTime
        at io.druid.segment.incremental.IncrementalIndex$OnHeapDimLookup.<init>(IncrementalIndex.java:1840) ~[druid-processing-0.9.1-SNAPSHOT.jar:0.9.1-SNAPSHOT]
        at io.druid.segment.incremental.IncrementalIndex$OnHeapDimDim.sort(IncrementalIndex.java:1815) ~[druid-processing-0.9.1-SNAPSHOT.jar:0.9.1-SNAPSHOT]
        at io.druid.segment.incremental.IncrementalIndex$OnHeapDimDim.sort(IncrementalIndex.java:1708) ~[druid-processing-0.9.1-SNAPSHOT.jar:0.9.1-SNAPSHOT]
        at io.druid.segment.incremental.IncrementalIndex$NullValueConverterDimDim.sort(IncrementalIndex.java:1345) ~[druid-processing-0.9.1-SNAPSHOT.jar:0.9.1-SNAPSHOT]
        at io.druid.segment.incremental.IncrementalIndexAdapter$DimensionIndexer.getDimLookup(IncrementalIndexAdapter.java:83) ~[druid-processing-0.9.1-SNAPSHOT.jar:0.9.1-SNAPSHOT]
        at io.druid.segment.incremental.IncrementalIndexAdapter$DimensionIndexer.access$300(IncrementalIndexAdapter.java:58) ~[druid-processing-0.9.1-SNAPSHOT.jar:0.9.1-SNAPSHOT]
        at io.druid.segment.incremental.IncrementalIndexAdapter.getDimValueLookup(IncrementalIndexAdapter.java:178) ~[druid-processing-0.9.1-SNAPSHOT.jar:0.9.1-SNAPSHOT]
        at io.druid.segment.IndexMergerV9.writeDimValueAndSetupDimConversion(IndexMergerV9.java:856) ~[druid-processing-0.9.1-SNAPSHOT.jar:0.9.1-SNAPSHOT]
        at io.druid.segment.IndexMergerV9.makeIndexFiles(IndexMergerV9.java:188) ~[druid-processing-0.9.1-SNAPSHOT.jar:0.9.1-SNAPSHOT]
        at io.druid.segment.IndexMerger.merge(IndexMerger.java:493) ~[druid-processing-0.9.1-SNAPSHOT.jar:0.9.1-SNAPSHOT]
        at io.druid.segment.IndexMerger.persist(IndexMerger.java:206) ~[druid-processing-0.9.1-SNAPSHOT.jar:0.9.1-SNAPSHOT]
        at io.druid.segment.IndexMerger.persist(IndexMerger.java:172) ~[druid-processing-0.9.1-SNAPSHOT.jar:0.9.1-SNAPSHOT]
        at io.druid.segment.IndexMerger.persist(IndexMerger.java:150) ~[druid-processing-0.9.1-SNAPSHOT.jar:0.9.1-SNAPSHOT]
        at io.druid.storage.hdfs.HdfsStorageHandler$2.persist(HdfsStorageHandler.java:437) ~[?:?]
        at io.druid.storage.hdfs.HdfsStorageHandler$2.close(HdfsStorageHandler.java:317) ~[?:?]
        at io.druid.storage.hdfs.HdfsStorageHandler.write(HdfsStorageHandler.java:206) ~[?:?]
        at io.druid.server.ForwardHandler$2.run(ForwardHandler.java:160) ~[druid-processing-0.9.1-SNAPSHOT.jar:0.9.1-SNAPSHOT]
        at io.druid.server.BrokerQueryResource.loadToIndex(BrokerQueryResource.java:406) [druid-server-0.9.1-SNAPSHOT.jar:0.9.1-SNAPSHOT]
```

**Comment by navis** [comment]
Fixed
