### ISSUE TITLE
unable to build oracle extension

### ISSUE THREAD

**Issue by ctamietto** [metatron-app/metatron-discovery#2440]
i'm trying to build the oracle extension and i'm following the readme

1) i had setup a maven repository security 
2) added a jar to local maven repository
3) cd to metatron-discovery/discovery-extensions/oracle-connection
4) runned  the command :
   mvn -s settings.xml clean install -DskipTests

i've got this output 

        [INFO] Scanning for projects...
[WARNING]
[WARNING] Some problems were encountered while building the effective model for app.metatron.discovery:oracle-connection:jar:18.3.0.0
[WARNING] 'build.plugins.plugin.version' for org.apache.maven.plugins:maven-compiler-plugin is missing. @ app.metatron.discovery:metatron-discovery:3.3.0-rc3, C:\git\metatron-discovery\pom.xml, line 105, column 21
[WARNING] 'build.plugins.plugin.version' for org.apache.maven.plugins:maven-deploy-plugin is missing. @ line 151, column 21
[WARNING]
[WARNING] It is highly recommended to fix these problems because they threaten the stability of your build.
[WARNING]
[WARNING] For this reason, future Maven versions might no longer support building such malformed projects.
[WARNING]
[INFO]
[INFO] --------------< app.metatron.discovery:oracle-connection >--------------
[INFO] Building oracle-connection extension 18.3.0.0
[INFO] --------------------------------[ jar ]---------------------------------
Downloading from maven.oracle.com: https://maven.oracle.com/app/metatron/discovery/discovery-common/3.3.0-rc3/discovery-common-3.3.0-rc3.pom
Downloading from jboss-maven2-release-repository: https://repository.jboss.org/nexus/content/repositories/releases/app/metatron/discovery/discovery-common/3.3.0-rc3/discovery-common-3.3.0-rc3.pom
Downloading from hortonworks-maven2-release-repository: http://repo.hortonworks.com/content/repositories/releases/app/metatron/discovery/discovery-common/3.3.0-rc3/discovery-common-3.3.0-rc3.pom
Downloading from hortonworks-groups-public-repo: http://repo.hortonworks.com/content/groups/public/app/metatron/discovery/discovery-common/3.3.0-rc3/discovery-common-3.3.0-rc3.pom
Downloading from spring-repo: https://repo.spring.io/release/app/metatron/discovery/discovery-common/3.3.0-rc3/discovery-common-3.3.0-rc3.pom
Downloading from metatron-public: http://52.231.187.35:9081/nexus/content/repositories/metatron-public/app/metatron/discovery/discovery-common/3.3.0-rc3/discovery-common-3.3.0-rc3.pom
Downloading from central: https://repo.maven.apache.org/maven2/app/metatron/discovery/discovery-common/3.3.0-rc3/discovery-common-3.3.0-rc3.pom
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  6.969 s
[INFO] Finished at: 2019-08-09T09:27:06+02:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project oracle-connection: Could not resolve dependencies for project app.metatron.discovery:oracle-connection:jar:18.3.0.0: Failed to collect dependencies at app.metatron.discovery:discovery-common:jar:3.3.0-rc3: Failed to read artifact descriptor for app.metatron.discovery:discovery-common:jar:3.3.0-rc3: Could not transfer artifact app.metatron.discovery:discovery-common:pom:3.3.0-rc3 from/to maven.oracle.com (https://maven.oracle.com): Not authorized -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException

so i had tried a commad with wget 

wget --user=xxx@xxxx --password=yyyy https://maven.oracle.com/app/metatron/discovery/discovery-common/3.3.0-rc3/discovery-common-3.3.0-rc3.pom
and i've got this output 

--2019-08-09 09:28:53--  https://maven.oracle.com/app/metatron/discovery/discovery-common/3.3.0-rc3/discovery-common-3.3.0-rc3.pom
Resolving maven.oracle.com (maven.oracle.com)... 156.151.59.28
Connecting to maven.oracle.com (maven.oracle.com)|156.151.59.28|:443... connected.
HTTP request sent, awaiting response... 301 Moved Permanently
Location: https://www.oracle.com/content/secure/maven/content/app/metatron/discovery/discovery-common/3.3.0-rc3/discovery-common-3.3.0-rc3.pom [following]
--2019-08-09 09:28:54--  https://www.oracle.com/content/secure/maven/content/app/metatron/discovery/discovery-common/3.3.0-rc3/discovery-common-3.3.0-rc3.pom
Resolving www.oracle.com (www.oracle.com)... 104.83.91.195, 2a02:26f0:de:38f::366, 2a02:26f0:de:387::366
Connecting to www.oracle.com (www.oracle.com)|104.83.91.195|:443... connected.
HTTP request sent, awaiting response... 302 Moved Temporarily
Location: https://login.oracle.com:443/oam/server/obrareq.cgi?encquery%3DgqH3qsZ05zL5%2F3381fF4Yaz80UbwVy18G0FylGdX3xVVnR3vgkPBsDXv5vhKlhKTdFiqOz%2Bg2QTNxwk%2BGjnQEU%2FFEbmND86ig8SSRqJbgKx1xkvtTRiLEziaq5p0DVjAmOpBg8YhQSIbIgKOCbFkMMeRlG8I0o0bzbb3hfw0iCVJN%2FxLzTg55t11IA8%2FWCXx5HaSxaPy9iESqwWxScPGNZcJmNJd2f007Zpz3ydueUqFNM2s%2BaCGPlyl6Vnsi3Js4NNJ87M2Ygftz7nmIt0AuYBvrTQK%2Bqbee9e2DwZlsVHycJmEIqfuzy2eFTUXSoiiHBwwELrn2T2vcZRpX2oPw2uQX8eGDXeMdT8i6craAfjh9TfWDRUn1IPY%2F0mGCprmB0%2FftmiMVx5CruRwXjjm2k9UWtTgg8i4Gqh5nW1ZMGh8O1yqvgRF%2FJNhlBFnOt356CV0GeR5UZzosWrKd0zeKpvxFPcqxhUCV4AWXt15K%2F1erGQU7mU9OjzEXqv7zfpYvFhx2hb0OF16uYoP91bEmze%2Bn56%2FfgxDfeyusEOJ7hZUfrI1TwdwS3%2FqmclbP3kp5ut%2B0N0JpK9UKx%2Fo8NE0lw%3D%3D%20agentid%3Dwww.oracle.com%20ver%3D1%20crmethod%3D2&ECID-Context=1.005ZucWRcsm9Lew70F3FEF0005hf000Ylq%3BkXjE [following]
--2019-08-09 09:28:54--  https://login.oracle.com/oam/server/obrareq.cgi?encquery%3DgqH3qsZ05zL5%2F3381fF4Yaz80UbwVy18G0FylGdX3xVVnR3vgkPBsDXv5vhKlhKTdFiqOz%2Bg2QTNxwk%2BGjnQEU%2FFEbmND86ig8SSRqJbgKx1xkvtTRiLEziaq5p0DVjAmOpBg8YhQSIbIgKOCbFkMMeRlG8I0o0bzbb3hfw0iCVJN%2FxLzTg55t11IA8%2FWCXx5HaSxaPy9iESqwWxScPGNZcJmNJd2f007Zpz3ydueUqFNM2s%2BaCGPlyl6Vnsi3Js4NNJ87M2Ygftz7nmIt0AuYBvrTQK%2Bqbee9e2DwZlsVHycJmEIqfuzy2eFTUXSoiiHBwwELrn2T2vcZRpX2oPw2uQX8eGDXeMdT8i6craAfjh9TfWDRUn1IPY%2F0mGCprmB0%2FftmiMVx5CruRwXjjm2k9UWtTgg8i4Gqh5nW1ZMGh8O1yqvgRF%2FJNhlBFnOt356CV0GeR5UZzosWrKd0zeKpvxFPcqxhUCV4AWXt15K%2F1erGQU7mU9OjzEXqv7zfpYvFhx2hb0OF16uYoP91bEmze%2Bn56%2FfgxDfeyusEOJ7hZUfrI1TwdwS3%2FqmclbP3kp5ut%2B0N0JpK9UKx%2Fo8NE0lw%3D%3D%20agentid%3Dwww.oracle.com%20ver%3D1%20crmethod%3D2&ECID-Context=1.005ZucWRcsm9Lew70F3FEF0005hf000Ylq%3BkXjE
Resolving login.oracle.com (login.oracle.com)... 209.17.4.8
Connecting to login.oracle.com (login.oracle.com)|209.17.4.8|:443... connected.
HTTP request sent, awaiting response... 401 Authorization Required
Reusing existing connection to login.oracle.com:443.
HTTP request sent, awaiting response... 302 Moved Temporarily
Location: http://www.oracle.com/obrar.cgi?encreply=lPP0qTj1YfA+xi3Ke5xjWm7gwm2k4U2949OJOvlrX7YAbsQYnmZdjxp+oNNs/A5qUsWxXsIST5nmCBCXC1m9cbxbuHww7Kqi5qOaoolHAgiGIcLKj9KyrqCmX7ks3pUSDlpcbhmQOuG2Xmd9wRIXv2pTVJSjv3DMEBjyJ0e3TnKla+6gLWQjzo3+H/htwWBWlj72hM9RVMeIFi4QpKCRXAdKJ5pUhNpHsYW//HIRtkTigsATxMYWZLqFlSfo1V30MhVVrzVjocj5wHwnOIdBevEdOHpagKkP3pIsitF1yy3DRYjdRZDQh/DfipHf1r9R8LDwzV5/p62WsH+jFm3mn+GQTEsPhUovYM0YnIc8FOntQmi1OV/iOWpK9BJybr05XZFdOaM7YUHm8Fjg6YgFMK+0vOaKkrh3JW4bh1E4cxR4AVL46e0XxpL7xw2O9fv8NBbFxfGk2+OnrMWfkYZ2XY3CBpXV0m44FLPRvsbDDpDtffj0/74Gk59TcYiKeQW6zMjhKRIbfybuGVdg0yRlcid3K7AV+VdTBQ8kYX4UUHbg9BgHH9bjEK7aMh6UzbEIPB8RIczJ5J3osF6R9We+HCWwAb/i709w4p1nnnl8yhmQzm54YaxWGMafAlnyYrjgonQyh4kHL86jA36YI51npKmvkEvYch2bzjSJlPAIdajuuiK55vyI+kCs+jkz3PfM3U6jaVu5Pq9QIMHC7S9ALy+tE0L0rZuClBLfIU+wAmoPIKRRN+6UniwSyVlrDpeROT4k52L3IIjsY3g4EzKfJmdJyyQAuxtJaP8IqDOC9d4bkq+uqqO4B110QCzm3WkgCmLS/Y3mxUVGu8Nq5UzrqZkmJGNIqYvIgbmggQ9zi6OO31PxG0GhUNHB4j+KTQjqLxxKFULdndZ+oaShzm/Ut0gMQVwMEVLdXA+iaSjsRL3MAvf0hDOzfwGUnGf6HYYPokEZCjgL2K8lhLOGfu3bPXu/1toT4gSXDXDpNn9yv7qHyzUdHgylr0uC9AaU3WP/6RbmQiegv3/piT5xXWz4iIbt4a7SNgSkIoWdk9IwhsF95g/M9OTUkq/qQQYptHl2w1Nyq2aJ+QyCXivR/KvJI5/gYH4d/ZkGxgAt9rRw8H3z+R5iSP/7EUuJKaVPWS7wyiFdBSxXz9oX+jkvsfS75Q== [following]
--2019-08-09 09:28:56--  http://www.oracle.com/obrar.cgi?encreply=lPP0qTj1YfA+xi3Ke5xjWm7gwm2k4U2949OJOvlrX7YAbsQYnmZdjxp+oNNs/A5qUsWxXsIST5nmCBCXC1m9cbxbuHww7Kqi5qOaoolHAgiGIcLKj9KyrqCmX7ks3pUSDlpcbhmQOuG2Xmd9wRIXv2pTVJSjv3DMEBjyJ0e3TnKla+6gLWQjzo3+H/htwWBWlj72hM9RVMeIFi4QpKCRXAdKJ5pUhNpHsYW//HIRtkTigsATxMYWZLqFlSfo1V30MhVVrzVjocj5wHwnOIdBevEdOHpagKkP3pIsitF1yy3DRYjdRZDQh/DfipHf1r9R8LDwzV5/p62WsH+jFm3mn+GQTEsPhUovYM0YnIc8FOntQmi1OV/iOWpK9BJybr05XZFdOaM7YUHm8Fjg6YgFMK+0vOaKkrh3JW4bh1E4cxR4AVL46e0XxpL7xw2O9fv8NBbFxfGk2+OnrMWfkYZ2XY3CBpXV0m44FLPRvsbDDpDtffj0/74Gk59TcYiKeQW6zMjhKRIbfybuGVdg0yRlcid3K7AV+VdTBQ8kYX4UUHbg9BgHH9bjEK7aMh6UzbEIPB8RIczJ5J3osF6R9We+HCWwAb/i709w4p1nnnl8yhmQzm54YaxWGMafAlnyYrjgonQyh4kHL86jA36YI51npKmvkEvYch2bzjSJlPAIdajuuiK55vyI+kCs+jkz3PfM3U6jaVu5Pq9QIMHC7S9ALy+tE0L0rZuClBLfIU+wAmoPIKRRN+6UniwSyVlrDpeROT4k52L3IIjsY3g4EzKfJmdJyyQAuxtJaP8IqDOC9d4bkq+uqqO4B110QCzm3WkgCmLS/Y3mxUVGu8Nq5UzrqZkmJGNIqYvIgbmggQ9zi6OO31PxG0GhUNHB4j+KTQjqLxxKFULdndZ+oaShzm/Ut0gMQVwMEVLdXA+iaSjsRL3MAvf0hDOzfwGUnGf6HYYPokEZCjgL2K8lhLOGfu3bPXu/1toT4gSXDXDpNn9yv7qHyzUdHgylr0uC9AaU3WP/6RbmQiegv3/piT5xXWz4iIbt4a7SNgSkIoWdk9IwhsF95g/M9OTUkq/qQQYptHl2w1Nyq2aJ+QyCXivR/KvJI5/gYH4d/ZkGxgAt9rRw8H3z+R5iSP/7EUuJKaVPWS7wyiFdBSxXz9oX+jkvsfS75Q==
Connecting to www.oracle.com (www.oracle.com)|104.83.91.195|:80... connected.
HTTP request sent, awaiting response... 302 Found
Location: /content/secure/maven/content/app/metatron/discovery/discovery-common/3.3.0-rc3/discovery-common-3.3.0-rc3.pom [following]
--2019-08-09 09:28:56--  http://www.oracle.com/content/secure/maven/content/app/metatron/discovery/discovery-common/3.3.0-rc3/discovery-common-3.3.0-rc3.pom
Reusing existing connection to www.oracle.com:80.
HTTP request sent, awaiting response... 301 Moved Permanently
Location: https://www.oracle.com/content/secure/maven/content/app/metatron/discovery/discovery-common/3.3.0-rc3/discovery-common-3.3.0-rc3.pom [following]
--2019-08-09 09:28:56--  https://www.oracle.com/content/secure/maven/content/app/metatron/discovery/discovery-common/3.3.0-rc3/discovery-common-3.3.0-rc3.pom
Connecting to www.oracle.com (www.oracle.com)|104.83.91.195|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
**2019-08-09 09:28:57 ERROR 404: Not Found.**

seem to me that the artifact does not exists on the oracle servers
am i wrong ?

**Comment by ctamietto** [comment]
that is exactly what i have done
the problem is that the artifactory 
https://maven.oracle.com/app/metatron/discovery/discovery-common/3.3.0-rc3/discovery-common-3.3.0-rc3.pom
does not exists on the oracle server

**Comment by ctamietto** [comment]
[INFO]
[INFO] --------------< app.metatron.discovery:oracle-connection >--------------
[INFO] Building oracle-connection extension 18.3.0.0
[INFO] --------------------------------[ jar ]---------------------------------
Downloading from maven.oracle.com: https://maven.oracle.com/app/metatron/discovery/discovery-common/3.3.0-rc3/discovery-common-3.3.0-rc3.pom
[WARNING] The POM for app.metatron.discovery:discovery-common:jar:3.3.0-rc3 is missing, no dependency information available
Downloading from maven.oracle.com: https://maven.oracle.com/app/metatron/discovery/discovery-common/3.3.0-rc3/discovery-common-3.3.0-rc3.jar
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  3.413 s
[INFO] Finished at: 2019-08-09T13:38:22+02:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project oracle-connection: Could not resolve dependencies for project app.metatron.discovery:oracle-connection:jar:18.3.0.0: Could not find artifact app.metatron.discovery:discovery-common:jar:3.3.0-rc3 in maven.oracle.com (https://maven.oracle.com) -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException

**Comment by ufoscw** [comment]
@ctamietto 
In addition to @alchan-lee 's comment.
oracle-connection is a child project of discovery-extensions.
Since some parent project settings are required, errors may occur when building oracle-connection alone.
Build the discovery-extensions project using the cmd below.
```
discovery-extensions $ mvn -P extensions-all clean install
```

**Comment by ctamietto** [comment]
using mvn -P extensions-all clean install
i've got this error 
P.S. : there isn't ant readme for building  mssql-connection extension

[INFO] ------------------------------------------------------------------------
[INFO] Reactor Build Order:
[INFO]
[INFO] discovery-extensions                                               [pom]
[INFO] mssql-connection extension                                         [jar]
[INFO] oracle-connection extension                                        [jar]
[INFO]
[INFO] ------------< app.metatron.discovery:discovery-extensions >-------------
[INFO] Building discovery-extensions 3.3.0-rc3                            [1/3]
[INFO] --------------------------------[ pom ]---------------------------------
[INFO]
[INFO] --- maven-clean-plugin:2.4:clean (default-clean) @ discovery-extensions ---
[INFO] Deleting C:\git\metatron-discovery\discovery-distribution\extensions (includes = [**/*], excludes = [])
[INFO]
[INFO] --- maven-install-plugin:2.4:install (default-install) @ discovery-extensions ---
[INFO] Installing C:\git\metatron-discovery\discovery-extensions\pom.xml to C:\Users\Operatore.Bi\.m2\repository\app\metatron\discovery\discovery-extensions\3.3.0-rc3\discovery-extensions-3.3.0-rc3.pom
[INFO]
[INFO] --------------< app.metatron.discovery:mssql-connection >---------------
[INFO] Building mssql-connection extension 7.3.0                          [2/3]
[INFO] --------------------------------[ jar ]---------------------------------
[WARNING] The POM for app.metatron.discovery:discovery-common:jar:3.3.0-rc3 is missing, no dependency information available
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO]
[INFO] discovery-extensions 3.3.0-rc3 ..................... SUCCESS [  0.367 s]
[INFO] mssql-connection extension 7.3.0 ................... FAILURE [  0.199 s]
[INFO] oracle-connection extension 18.3.0.0 ............... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  1.019 s
[INFO] Finished at: 2019-08-09T15:08:32+02:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project mssql-connection: Could not resolve dependencies for project app.metatron.discovery:mssql-connection:jar:7.3.0: Failure to find app.metatron.discovery:discovery-common:jar:3.3.0-rc3 in https://repository.jboss.org/nexus/content/repositories/releases/ was cached in the local repository, resolution will not be reattempted until the update interval of jboss-maven2-release-repository has elapsed or updates are forced -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException

**Comment by ufoscw** [comment]
The metatron-discovery main project doesn't seem to build properly?
When you build a metatron-discovery main project, using the extensions-all profile will also build the entire extensions.
I'd recommend rebuilding after that.

**Comment by ctamietto** [comment]
i've done this :

**Comment by ctamietto** [comment]
1) git clone https://github.com/metatron-app/metatron-discovery.git
2) cd metatron-discovery
3)  mvn -s ../settings.xml -P extensions-all clean install

i've got this error :
[ERROR]
[ERROR] C:\git\metatron-discovery\discovery-frontend\node_modules\.bin\ng:2
[ERROR] basedir=$(dirname "$(echo "$0" | sed -e 's,\\,/,g')")
[ERROR]           ^^^^^^^
[ERROR]
[ERROR] SyntaxError: missing ) after argument list
[ERROR]     at createScript (vm.js:80:10)
[ERROR]     at Object.runInThisContext (vm.js:139:10)
[ERROR]     at Module._compile (module.js:617:28)
[ERROR]     at Object.Module._extensions..js (module.js:664:10)
[ERROR]     at Module.load (module.js:566:32)
[ERROR]     at tryModuleLoad (module.js:506:12)
[ERROR]     at Function.Module._load (module.js:498:3)
[ERROR]     at Function.Module.runMain (module.js:694:10)
[ERROR]     at startup (bootstrap_node.js:204:16)
[ERROR]     at bootstrap_node.js:625:3
[ERROR] npm ERR! code ELIFECYCLE
[ERROR] npm ERR! errno 1
[ERROR] npm ERR! polaris2-ui@0.0.0 prod: `npm run package-reinstall && node --max_old_space_size=10240 ./node_modules/.bin/ng build --deploy-url /resource/ --output-hashing all --prod --base-href /app/v2/`
[ERROR] npm ERR! Exit status 1
[ERROR] npm ERR!
[ERROR] npm ERR! Failed at the polaris2-ui@0.0.0 prod script.
[ERROR] npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
[ERROR]
[ERROR] npm ERR! A complete log of this run can be found in:
[ERROR] npm ERR!     C:\Users\Operatore.Bi\AppData\Roaming\npm-cache\_logs\2019-08-09T13_55_40_983Z-debug.log
[

**Comment by ctamietto** [comment]
do i need to build the project on linux platform ?

**Comment by ctamietto** [comment]
solved .
i've build from source the release 3.3.0-rc3 with all extension on a linux platform  and maven container with this command :
docker run -it --rm --name build_metatron_discovery -v maven-repo-metatron-discovery:/root/.m2 -v "$(pwd)":/usr/src/mymaven -w /usr/src/mymaven maven:3.6.1-jdk-8 mvn -s /root/.m2/settings.xml -P extensions-all clean install -DskipTests
the istruction for access oracle maven repository does not work for me , so i've downloaded and installed the artifacts manually 
/root/m.2/repository/com/oracle/jdbc/ucp/18.3.0.0/ucp-18.3.0.0.pom
/root/m.2/repository/com/oracle/jdbc/ucp/18.3.0.0/ucp-18.3.0.0.jar
/root/m.2/repository/com/oracle/jdbc/ucp/18.3.0.0/ojdbc8-18.3.0.0
