### ISSUE TITLE
error on ingesting large oracle table

### ISSUE THREAD

**Issue by ctamietto** [metatron-app/metatron-discovery#2441]
i'm trying to ingest a large oracle database .
If I limit the ingest to 10000 row all is gone well .
If i try to ingest all the data table ( about 120.000 ) row i get this error :
Caused by: java.sql.SQLSyntaxErrorException: Statement too complex. Try rewriting the query to remove complexity. Eliminating many duplicate expressions or breaking up the query and storing interim results in a temporary table can often help resolve this error.
is there any way to instruct the ingestion process to manage large amount of data splitting the import in several sql statement ?
if not batch ingestion of large data set is problematic .

**Comment by ufoscw** [comment]
Can you tell me what option you chose when you ingested the data?

1.Select Data
"Table" or "Query"

2. If you chose Query, does it run well in the workbench?

3.ingestion settings
"ingest Once" or "Ingest Periodically"

**Comment by ctamietto** [comment]
1) Select Data
"Table" or "Query"  => Table
2)  I haven't  choose query
3)  ingestion settings
"ingest Once" or "Ingest Periodically"  => Ingest Once

at this point if i limit the ingested row to 10000 it work well
but if i try to ingest all the data table ( about 120000 rows ) i get the error

**Comment by ctamietto** [comment]
the full stack trace follow :

Caused by: org.apache.derby.client.am.SqlException: Statement too complex. Try rewriting the query to remove complexity. Eliminating many duplicate expressions or breaking up the query and storing interim results in a temporary table can often help resolve this error.
        at org.apache.derby.client.am.ClientStatement.completeSqlca(Unknown Source) ~[derbyclient-10.11.1.1.jar:?]
        at org.apache.derby.client.net.NetStatementReply.parsePrepareError(Unknown Source) ~[derbyclient-10.11.1.1.jar:?]
        at org.apache.derby.client.net.NetStatementReply.parsePRPSQLSTTreply(Unknown Source) ~[derbyclient-10.11.1.1.jar:?]
        at org.apache.derby.client.net.NetStatementReply.readPrepareDescribeOutput(Unknown Source) ~[derbyclient-10.11.1.1.jar:?]
        at org.apache.derby.client.net.StatementReply.readPrepareDescribeOutput(Unknown Source) ~[derbyclient-10.11.1.1.jar:?]
        at org.apache.derby.client.net.NetStatement.readPrepareDescribeOutput_(Unknown Source) ~[derbyclient-10.11.1.1.jar:?]
        at org.apache.derby.client.am.ClientStatement.readPrepareDescribeOutput(Unknown Source) ~[derbyclient-10.11.1.1.jar:?]
        at org.apache.derby.client.am.ClientPreparedStatement.readPrepareDescribeInputOutput(Unknown Source) ~[derbyclient-10.11.1.1.jar:?]
        at org.apache.derby.client.am.ClientPreparedStatement.flowPrepareDescribeInputOutput(Unknown Source) ~[derbyclient-10.11.1.1.jar:?]
        at org.apache.derby.client.am.ClientPreparedStatement.prepare(Unknown Source) ~[derbyclient-10.11.1.1.jar:?]
        at org.apache.derby.client.am.ClientConnection.prepareStatementX(Unknown Source) ~[derbyclient-10.11.1.1.jar:?]
        at org.apache.derby.client.am.ClientConnection.prepareStatement(Unknown Source) ~[derbyclient-10.11.1.1.jar:?]
        at org.apache.commons.dbcp2.DelegatingConnection.prepareStatement(DelegatingConnection.java:288) ~[commons-dbcp2-2.0.1.jar:2.0.1]
        at org.apache.commons.dbcp2.DelegatingConnection.prepareStatement(DelegatingConnection.java:288) ~[commons-dbcp2-2.0.1.jar:2.0.1]
        at org.skife.jdbi.v2.DefaultStatementBuilder.create(DefaultStatementBuilder.java:52) ~[jdbi-2.63.1.jar:2.63.1]
        at org.skife.jdbi.v2.SQLStatement.internalExecute(SQLStatement.java:1304) ~[jdbi-2.63.1.jar:2.63.1]
        at org.skife.jdbi.v2.Query.iterator(Query.java:240) ~[jdbi-2.63.1.jar:2.63.1]
        at io.druid.metadata.IndexerSQLMetadataStorageCoordinator.getTimelineForIntervalsWithHandle(IndexerSQLMetadataStorageCoordinator.java:255) ~[druid-server-0.9.1-SNAPSHOT.jar:0.9.1-SNAPSHOT]
        at io.druid.metadata.IndexerSQLMetadataStorageCoordinator.access$000(IndexerSQLMetadataStorageCoordinator.java:80) ~[druid-server-0.9.1-SNAPSHOT.jar:0.9.1-SNAPSHOT]
        at io.druid.metadata.IndexerSQLMetadataStorageCoordinator$1.withHandle(IndexerSQLMetadataStorageCoordinator.java:141) ~[druid-server-0.9.1-SNAPSHOT.jar:0.9.1-SNAPSHOT]
        at io.druid.metadata.IndexerSQLMetadataStorageCoordinator$1.withHandle(IndexerSQLMetadataStorageCoordinator.java:137) ~[druid-server-0.9.1-SNAPSHOT.jar:0.9.1-SNAPSHOT]
        at org.skife.jdbi.v2.DBI.withHandle(DBI.java:281) ~[jdbi-2.63.1.jar:2.63.1]
        ... 63 more
Caused by: org.apache.derby.client.am.SqlException: Java class file format limit(s) exceeded: method:e2 code_length (103011 > 65535) in generated class org.apache.derby.exe.acc2db804dx016cx7c33x2d26x000033111e6020.
        at org.apache.derby.client.am.ClientStatement.completeSqlca(Unknown Source) ~[derbyclient-10.11.1.1.jar:?]
        at org.apache.derby.client.net.NetStatementReply.parsePrepareError(Unknown Source) ~[derbyclient-10.11.1.1.jar:?]
        at org.apache.derby.client.net.NetStatementReply.parsePRPSQLSTTreply(Unknown Source) ~[derbyclient-10.11.1.1.jar:?]
        at org.apache.derby.client.net.NetStatementReply.readPrepareDescribeOutput(Unknown Source) ~[derbyclient-10.11.1.1.jar:?]
        at org.apache.derby.client.net.StatementReply.readPrepareDescribeOutput(Unknown Source) ~[derbyclient-10.11.1.1.jar:?]
        at org.apache.derby.client.net.NetStatement.readPrepareDescribeOutput_(Unknown Source) ~[derbyclient-10.11.1.1.jar:?]
        at org.apache.derby.client.am.ClientStatement.readPrepareDescribeOutput(Unknown Source) ~[derbyclient-10.11.1.1.jar:?]
        at org.apache.derby.client.am.ClientPreparedStatement.readPrepareDescribeInputOutput(Unknown Source) ~[derbyclient-10.11.1.1.jar:?]
        at org.apache.derby.client.am.ClientPreparedStatement.flowPrepareDescribeInputOutput(Unknown Source) ~[derbyclient-10.11.1.1.jar:?]
        at org.apache.derby.client.am.ClientPreparedStatement.prepare(Unknown Source) ~[derbyclient-10.11.1.1.jar:?]
        at org.apache.derby.client.am.ClientConnection.prepareStatementX(Unknown Source) ~[derbyclient-10.11.1.1.jar:?]
        at org.apache.derby.client.am.ClientConnection.prepareStatement(Unknown Source) ~[derbyclient-10.11.1.1.jar:?]
        at org.apache.commons.dbcp2.DelegatingConnection.prepareStatement(DelegatingConnection.java:288) ~[commons-dbcp2-2.0.1.jar:2.0.1]
        at org.apache.commons.dbcp2.DelegatingConnection.prepareStatement(DelegatingConnection.java:288) ~[commons-dbcp2-2.0.1.jar:2.0.1]
        at org.skife.jdbi.v2.DefaultStatementBuilder.create(DefaultStatementBuilder.java:52) ~[jdbi-2.63.1.jar:2.63.1]
        at org.skife.jdbi.v2.SQLStatement.internalExecute(SQLStatement.java:1304) ~[jdbi-2.63.1.jar:2.63.1]
        at org.skife.jdbi.v2.Query.iterator(Query.java:240) ~[jdbi-2.63.1.jar:2.63.1]
        at io.druid.metadata.IndexerSQLMetadataStorageCoordinator.getTimelineForIntervalsWithHandle(IndexerSQLMetadataStorageCoordinator.java:255) ~[druid-server-0.9.1-SNAPSHOT.jar:0.9.1-SNAPSHOT]
        at io.druid.metadata.IndexerSQLMetadataStorageCoordinator.access$000(IndexerSQLMetadataStorageCoordinator.java:80) ~[druid-server-0.9.1-SNAPSHOT.jar:0.9.1-SNAPSHOT]
        at io.druid.metadata.IndexerSQLMetadataStorageCoordinator$1.withHandle(IndexerSQLMetadataStorageCoordinator.java:141) ~[druid-server-0.9.1-SNAPSHOT.jar:0.9.1-SNAPSHOT]
        at io.druid.metadata.IndexerSQLMetadataStorageCoordinator$1.withHandle(IndexerSQLMetadataStorageCoordinator.java:137) ~[druid-server-0.9.1-SNAPSHOT.jar:0.9.1-SNAPSHOT]
        at org.skife.jdbi.v2.DBI.withHandle(DBI.java:281) ~[jdbi-2.63.1.jar:2.63.1]

**Comment by ctamietto** [comment]
any news
