### ISSUE TITLE
Fix ClassCastException at /druid/v2/load/ API 

### ISSUE THREAD

**Issue by seoeun25** [metatron-app/metatron-discovery#2940]
**Describe the bug**

```2019-12-04T08:05:19,430 WARN [processing-1] io.druid.storage.hdfs.HdfsStorageHandler - failed
java.lang.ClassCastException: io.druid.data.input.MapBasedRow cannot be cast to io.druid.data.input.InputRow
	at io.druid.segment.incremental.IncrementalIndex.add(IncrementalIndex.java:394) ~[druid-processing-3.4.0-SNAPSHOT.jar:3.4.0-SNAPSHOT]
	at io.druid.storage.hdfs.HdfsStorageHandler$2.accumulate(HdfsStorageHandler.java:329) ~[?:?]
	at io.druid.storage.hdfs.HdfsStorageHandler$2.accumulate(HdfsStorageHandler.java:303) ~[?:?]
	at io.druid.java.util.common.guava.MappingAccumulator.accumulate(MappingAccumulator.java:37) ~[java-util-3.4.0-SNAPSHOT.jar:3.4.0-SNAPSHOT]
	at io.druid.java.util.common.guava.BaseSequence.accumulate(BaseSequence.java:65) ~[java-util-3.4.0-SNAPSHOT.jar:3.4.0-SNAPSHOT]
	at io.druid.common.utils.Sequences$ProgressingSequence.accumulate(Sequences.java:420) ~[druid-common-3.4.0-SNAPSHOT.jar:3.4.0-SNAPSHOT]
	at io.druid.java.util.common.guava.MappedSequence.accumulate(MappedSequence.java:38) ~[java-util-3.4.0-SNAPSHOT.jar:3.4.0-SNAPSHOT]
	at io.druid.common.utils.Sequences$ProgressingSequence.accumulate(Sequences.java:420) ~[druid-common-3.4.0-SNAPSHOT.jar:3.4.0-SNAPSHOT]
	at io.druid.storage.hdfs.HdfsStorageHandler.write(HdfsStorageHandler.java:236) [druid-hdfs-storage-3.4.0-SNAPSHOT.jar:3.4.0-SNAPSHOT]
	at io.druid.server.ForwardHandler$2.run(ForwardHandler.java:162) [druid-processing-3.4.0-SNAPSHOT.jar:3.4.0-SNAPSHOT]
	at io.druid.query.QueryRunners.run(QueryRunners.java:138) [druid-processing-3.4.0-SNAPSHOT.jar:3.4.0-SNAPSHOT]
	at io.druid.server.BrokerQueryResource$2.call(BrokerQueryResource.java:330) [druid-server-3.4.0-SNAPSHOT.jar:3.4.0-SNAPSHOT]
	at io.druid.server.BrokerQueryResource$2.call(BrokerQueryResource.java:326) [druid-server-3.4.0-SNAPSHOT.jar:3.4.0-SNAPSHOT]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_192]
	at io.druid.query.PrioritizedListenableFutureTask.run(PrioritizedExecutorService.java:273) [druid-processing-3.4.0-SNAPSHOT.jar:3.4.0-SNAPSHOT]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_192]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_192]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_192]```

**Comment by seoeun25** [comment]
@minhyun2 참고하세요.

**Comment by navis** [comment]
Regression from #2906 (typo)
