### ISSUE TITLE
Bump up lucene version from 6.2.0 to 8.3.1

### ISSUE THREAD

**Issue by navis** [metatron-app/metatron-discovery#2970]
Just making it compiled. Let's see what will happen.

**Comment by navis** [comment]
com.vividsolutions.jts-core-1.14.0 --> org.locationtech.jts-core-1.16.1
spatial4j 0.6 --> 0.7
geotools.version 19.0 --> 20.5

**Comment by navis** [comment]
DAMN

```
2019-12-16T02:47:12,726 WARN [qtp1032382137-58[select.stream_87f1fa33-4c7b-4c7d-812a-0c0dcf4687ba]] io.druid.server.QueryResource - Exception occurred on request [select.stream{dataSource='lineitem', querySegmentSpec=MultipleSpecificSegmentSpec{descriptors=[SegmentDescriptor{interval=1992-01-01T00:00:00.000Z/1992-10-01T00:00:00.000Z, version='2019-12-12T10:42:42.110Z', partitionNumber=0}]}, filter=LuceneQueryFilter{field='L_COMMENT', analyzer='standard', expression=''breach''}, columns=[L_COMMENT], limitSpec=LimitSpec{columns=[], limit=10}, finalize=false}]
java.lang.RuntimeException: org.apache.lucene.index.IndexFormatTooOldException: Format version is not supported (resource BufferedChecksumIndexInput(LuceneIndex(name=segments_1))): 6 (needs to be between 7 and 9). This version of Lucene only supports indexes created with release 6.0 and later.
	at com.google.common.base.Throwables.propagate(Throwables.java:160) ~[guava-16.0.1.jar:?]
	at io.druid.segment.lucene.Lucenes.readFrom(Lucenes.java:315) ~[druid-processing-3.4.0-SNAPSHOT.jar:3.4.0-SNAPSHOT]
	at io.druid.segment.serde.ComplexColumnSerializer$LuceneIndexPartSerDe$2$1.get(ComplexColumnSerializer.java:277) ~[druid-processing-3.4.0-SNAPSHOT.jar:3.4.0-SNAPSHOT]
	at io.druid.segment.serde.ComplexColumnSerializer$LuceneIndexPartSerDe$2$1.get(ComplexColumnSerializer.java:261) ~[druid-processing-3.4.0-SNAPSHOT.jar:3.4.0-SNAPSHOT]
	at io.druid.segment.column.SimpleColumn.getLuceneIndex(SimpleColumn.java:254) ~[druid-processing-3.4.0-SNAPSHOT.jar:3.4.0-SNAPSHOT]
	at io.druid.segment.ColumnSelectorBitmapIndexSelector.getLuceneIndex(ColumnSelectorBitmapIndexSelector.java:193) ~[druid-processing-3.4.0-SNAPSHOT.jar:3.4.0-SNAPSHOT]
	at io.druid.query.filter.LuceneQueryFilter$1.getBitmapIndex(LuceneQueryFilter.java:126) ~[druid-processing-3.4.0-SNAPSHOT.jar:3.4.0-SNAPSHOT]
	at io.druid.segment.filter.Filters.leafToBitmap(Filters.java:648) ~[druid-processing-3.4.0-SNAPSHOT.jar:3.4.0-SNAPSHOT]
	at io.druid.segment.filter.Filters.access$100(Filters.java:102) ~[druid-processing-3.4.0-SNAPSHOT.jar:3.4.0-SNAPSHOT]
	at io.druid.segment.filter.Filters$FilterContext.createBitmap(Filters.java:532) ~[druid-processing-3.4.0-SNAPSHOT.jar:3.4.0-SNAPSHOT]
	at io.druid.segment.filter.Filters$9.createBitmap(Filters.java:495) ~[druid-processing-3.4.0-SNAPSHOT.jar:3.4.0-SNAPSHOT]
	at io.druid.segment.filter.Filters.toBitmapHolderRecurse(Filters.java:630) ~[druid-processing-3.4.0-SNAPSHOT.jar:3.4.0-SNAPSHOT]
	at io.druid.segment.filter.Filters.toBitmapHolder(Filters.java:585) ~[druid-processing-3.4.0-SNAPSHOT.jar:3.4.0-SNAPSHOT]
	at io.druid.query.filter.DimFilters.extractBitmaps(DimFilters.java:139) ~[druid-processing-3.4.0-SNAPSHOT.jar:3.4.0-SNAPSHOT]
	at io.druid.segment.QueryableIndexStorageAdapter.makeCursors(QueryableIndexStorageAdapter.java:272) ~[druid-processing-3.4.0-SNAPSHOT.jar:3.4.0-SNAPSHOT]
	at io.druid.segment.CursorFactory$Abstract.makeCursors(CursorFactory.java:52) ~[druid-processing-3.4.0-SNAPSHOT.jar:3.4.0-SNAPSHOT]
	at io.druid.query.QueryRunnerHelper.makeCursorBasedQuery(QueryRunnerHelper.java:54) ~[druid-processing-3.4.0-SNAPSHOT.jar:3.4.0-SNAPSHOT]
	at io.druid.query.select.StreamQueryEngine.processRaw(StreamQueryEngine.java:80) ~[druid-processing-3.4.0-SNAPSHOT.jar:3.4.0-SNAPSHOT]
	at io.druid.query.select.StreamQueryEngine.process(StreamQueryEngine.java:55) ~[druid-processing-3.4.0-SNAPSHOT.jar:3.4.0-SNAPSHOT]
	at io.druid.query.select.StreamQueryRunnerFactory$1.run(StreamQueryRunnerFactory.java:211) ~[druid-processing-3.4.0-SNAPSHOT.jar:3.4.0-SNAPSHOT]
	at io.druid.query.ReferenceCountingSegmentQueryRunner.run(ReferenceCountingSegmentQueryRunner.java:60) ~[druid-processing-3.4.0-SNAPSHOT.jar:3.4.0-SNAPSHOT]
	at io.druid.query.MetricsEmittingQueryRunner$2.get(MetricsEmittingQueryRunner.java:97) ~[druid-processing-3.4.0-SNAPSHOT.jar:3.4.0-SNAPSHOT]
	at io.druid.query.MetricsEmittingQueryRunner$2.get(MetricsEmittingQueryRunner.java:93) ~[druid-processing-3.4.0-SNAPSHOT.jar:3.4.0-SNAPSHOT]
	at io.druid.java.util.common.guava.LazySequence.toYielder(LazySequence.java:41) ~[java-util-3.4.0-SNAPSHOT.jar:3.4.0-SNAPSHOT]
	at io.druid.java.util.common.guava.WrappingSequence$2.get(WrappingSequence.java:87) ~[java-util-3.4.0-SNAPSHOT.jar:3.4.0-SNAPSHOT]
	at io.druid.java.util.common.guava.WrappingSequence$2.get(WrappingSequence.java:83) ~[java-util-3.4.0-SNAPSHOT.jar:3.4.0-SNAPSHOT]
	at io.druid.java.util.common.guava.SequenceWrapper.wrap(SequenceWrapper.java:55) ~[java-util-3.4.0-SNAPSHOT.jar:3.4.0-SNAPSHOT]
	at io.druid.java.util.common.guava.WrappingSequence.toYielder(WrappingSequence.java:82) ~[java-util-3.4.0-SNAPSHOT.jar:3.4.0-SNAPSHOT]
	at io.druid.java.util.common.guava.LazySequence.toYielder(LazySequence.java:41) ~[java-util-3.4.0-SNAPSHOT.jar:3.4.0-SNAPSHOT]
	at io.druid.java.util.common.guava.WrappingSequence$2.get(WrappingSequence.java:87) ~[java-util-3.4.0-SNAPSHOT.jar:3.4.0-SNAPSHOT]
	at io.druid.java.util.common.guava.WrappingSequence$2.get(WrappingSequence.java:83) ~[java-util-3.4.0-SNAPSHOT.jar:3.4.0-SNAPSHOT]
	at io.druid.java.util.common.guava.SequenceWrapper.wrap(SequenceWrapper.java:55) ~[java-util-3.4.0-SNAPSHOT.jar:3.4.0-SNAPSHOT]
	at io.druid.java.util.common.guava.WrappingSequence.toYielder(WrappingSequence.java:82) ~[java-util-3.4.0-SNAPSHOT.jar:3.4.0-SNAPSHOT]
	at io.druid.query.spec.SpecificSegmentQueryRunner$2$2.call(SpecificSegmentQueryRunner.java:129) ~[druid-processing-3.4.0-SNAPSHOT.jar:3.4.0-SNAPSHOT]
	at io.druid.query.spec.SpecificSegmentQueryRunner$2$2.call(SpecificSegmentQueryRunner.java:125) ~[druid-processing-3.4.0-SNAPSHOT.jar:3.4.0-SNAPSHOT]
	at io.druid.query.spec.SpecificSegmentQueryRunner.doNamed(SpecificSegmentQueryRunner.java:185) ~[druid-processing-3.4.0-SNAPSHOT.jar:3.4.0-SNAPSHOT]
	at io.druid.query.spec.SpecificSegmentQueryRunner.access$300(SpecificSegmentQueryRunner.java:41) ~[druid-processing-3.4.0-SNAPSHOT.jar:3.4.0-SNAPSHOT]
	at io.druid.query.spec.SpecificSegmentQueryRunner$2.doItNamed(SpecificSegmentQueryRunner.java:176) ~[druid-processing-3.4.0-SNAPSHOT.jar:3.4.0-SNAPSHOT]
	at io.druid.query.spec.SpecificSegmentQueryRunner$2.toYielder(SpecificSegmentQueryRunner.java:123) ~[druid-processing-3.4.0-SNAPSHOT.jar:3.4.0-SNAPSHOT]
	at io.druid.java.util.common.guava.WrappingSequence$2.get(WrappingSequence.java:87) ~[java-util-3.4.0-SNAPSHOT.jar:3.4.0-SNAPSHOT]
	at io.druid.java.util.common.guava.WrappingSequence$2.get(WrappingSequence.java:83) ~[java-util-3.4.0-SNAPSHOT.jar:3.4.0-SNAPSHOT]
	at io.druid.query.CPUTimeMetricQueryRunner$1.wrap(CPUTimeMetricQueryRunner.java:77) ~[druid-processing-3.4.0-SNAPSHOT.jar:3.4.0-SNAPSHOT]
	at io.druid.java.util.common.guava.WrappingSequence.toYielder(WrappingSequence.java:82) ~[java-util-3.4.0-SNAPSHOT.jar:3.4.0-SNAPSHOT]
	at io.druid.java.util.common.guava.LimitedSequence.toYielder(LimitedSequence.java:48) ~[java-util-3.4.0-SNAPSHOT.jar:3.4.0-SNAPSHOT]
	at io.druid.java.util.common.guava.MappedSequence.toYielder(MappedSequence.java:44) ~[java-util-3.4.0-SNAPSHOT.jar:3.4.0-SNAPSHOT]
	at io.druid.java.util.common.guava.ConcatSequence.makeYielder(ConcatSequence.java:94) ~[java-util-3.4.0-SNAPSHOT.jar:3.4.0-SNAPSHOT]
	at io.druid.java.util.common.guava.ConcatSequence.toYielder(ConcatSequence.java:73) ~[java-util-3.4.0-SNAPSHOT.jar:3.4.0-SNAPSHOT]
	at io.druid.java.util.common.guava.WrappingSequence$2.get(WrappingSequence.java:87) ~[java-util-3.4.0-SNAPSHOT.jar:3.4.0-SNAPSHOT]
	at io.druid.java.util.common.guava.WrappingSequence$2.get(WrappingSequence.java:83) ~[java-util-3.4.0-SNAPSHOT.jar:3.4.0-SNAPSHOT]
	at io.druid.query.CPUTimeMetricQueryRunner$1.wrap(CPUTimeMetricQueryRunner.java:77) ~[druid-processing-3.4.0-SNAPSHOT.jar:3.4.0-SNAPSHOT]
	at io.druid.java.util.common.guava.WrappingSequence.toYielder(WrappingSequence.java:82) ~[java-util-3.4.0-SNAPSHOT.jar:3.4.0-SNAPSHOT]
	at io.druid.java.util.common.guava.ResourceClosingSequence.toYielder(ResourceClosingSequence.java:50) ~[java-util-3.4.0-SNAPSHOT.jar:3.4.0-SNAPSHOT]
	at io.druid.server.QueryResource.doPost(QueryResource.java:287) [druid-server-3.4.0-SNAPSHOT.jar:3.4.0-SNAPSHOT]
```

**Comment by navis** [comment]
#2990 Later..
