### ISSUE TITLE
Fix exception getting object detail from S3

### ISSUE THREAD

**Issue by navis** [metatron-app/metatron-discovery#3146]
Fix for..
```
Failed to load segment for dataSource: {class=io.druid.server.coordination.ZkCoordinator, exceptionType=class io.druid.segment.loading.SegmentLoadingException, exceptionMessage=Exception loading segment[sales_s3_01_2011-01-01T00:00:00.000Z_2012-01-01T00:00:00.000Z_2020-03-20T13:05:44.392Z], segment=DataSegment{size=381630, shardSpec=NoneShardSpec, metrics=[count, Discount, Profit, Sales, DaystoShipActual, SalesForecast, DaystoShipScheduled, SalesperCustomer, ProfitRatio], dimensions=[Category, City, Country, CustomerName, OrderID, PostalCode, ProductName, Quantity, Region, Segment, ShipDate, ShipMode, State, Sub-Category, ShipStatus, OrderProfitable, SalesaboveTarget, latitude, longitude], version='2020-03-20T13:05:44.392Z', loadSpec={type=s3_zip, bucket=skt-metatron, key=druid/segments/sales_s3_01/2011-01-01T00:00:00.000Z_2012-01-01T00:00:00.000Z/2020-03-20T13:05:44.392Z/0/index.zip}, interval=2011-01-01T00:00:00.000Z/2012-01-01T00:00:00.000Z, dataSource='sales_s3_01', binaryVersion='9'}}
io.druid.segment.loading.SegmentLoadingException: Exception loading segment[sales_s3_01_2011-01-01T00:00:00.000Z_2012-01-01T00:00:00.000Z_2020-03-20T13:05:44.392Z]
	at io.druid.server.coordination.ZkCoordinator.loadSegment(ZkCoordinator.java:349) ~[druid-server-0.9.1-SNAPSHOT.jar:0.9.1-SNAPSHOT]
	at io.druid.server.coordination.ZkCoordinator.addSegment(ZkCoordinator.java:427) [druid-server-0.9.1-SNAPSHOT.jar:0.9.1-SNAPSHOT]
	at io.druid.server.coordination.SegmentChangeRequestLoad.go(SegmentChangeRequestLoad.java:44) [druid-server-0.9.1-SNAPSHOT.jar:0.9.1-SNAPSHOT]
	at io.druid.server.coordination.ZkCoordinator$1.childEvent(ZkCoordinator.java:164) [druid-server-0.9.1-SNAPSHOT.jar:0.9.1-SNAPSHOT]
	at org.apache.curator.framework.recipes.cache.PathChildrenCache$5.apply(PathChildrenCache.java:522) [curator-recipes-2.10.0.jar:?]
	at org.apache.curator.framework.recipes.cache.PathChildrenCache$5.apply(PathChildrenCache.java:516) [curator-recipes-2.10.0.jar:?]
	at org.apache.curator.framework.listen.ListenerContainer$1.run(ListenerContainer.java:93) [curator-framework-2.10.0.jar:?]
	at com.google.common.util.concurrent.MoreExecutors$SameThreadExecutorService.execute(MoreExecutors.java:297) [guava-16.0.1.jar:?]
	at org.apache.curator.framework.listen.ListenerContainer.forEach(ListenerContainer.java:85) [curator-framework-2.10.0.jar:?]
	at org.apache.curator.framework.recipes.cache.PathChildrenCache.callListeners(PathChildrenCache.java:514) [curator-recipes-2.10.0.jar:?]
	at org.apache.curator.framework.recipes.cache.EventOperation.invoke(EventOperation.java:35) [curator-recipes-2.10.0.jar:?]
	at org.apache.curator.framework.recipes.cache.PathChildrenCache$9.run(PathChildrenCache.java:772) [curator-recipes-2.10.0.jar:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_242]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_242]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_242]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_242]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_242]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_242]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_242]
Caused by: java.lang.RuntimeException: org.jets3t.service.ServiceException: Request Error. -- ResponseCode: 400, ResponseStatus: Bad Request, RequestId: 574E8779DFAD2304, HostId: NdUd0fdUU7MNTNHU006Ej+ju1dDylcHe1xKxzpUThj/yGt2WmFapwFWELZf0wkF8lBsea90jS+k=
	at com.google.common.base.Throwables.propagate(Throwables.java:160) ~[guava-16.0.1.jar:?]
	at io.druid.storage.s3.S3DataSegmentPuller.isObjectInBucket(S3DataSegmentPuller.java:341) ~[?:?]
	at io.druid.storage.s3.S3DataSegmentPuller.getSegmentFiles(S3DataSegmentPuller.java:174) ~[?:?]
	at io.druid.storage.s3.S3LoadSpec.loadSegment(S3LoadSpec.java:62) ~[?:?]
	at io.druid.segment.loading.SegmentLoaderLocalCacheManager.getSegmentFiles(SegmentLoaderLocalCacheManager.java:143) ~[druid-server-0.9.1-SNAPSHOT.jar:0.9.1-SNAPSHOT]
	at io.druid.segment.loading.SegmentLoaderLocalCacheManager.getSegment(SegmentLoaderLocalCacheManager.java:95) ~[druid-server-0.9.1-SNAPSHOT.jar:0.9.1-SNAPSHOT]
	at io.druid.server.coordination.ServerManager.loadSegment(ServerManager.java:196) ~[druid-server-0.9.1-SNAPSHOT.jar:0.9.1-SNAPSHOT]
	at io.druid.server.coordination.ZkCoordinator.loadSegment(ZkCoordinator.java:344) ~[druid-server-0.9.1-SNAPSHOT.jar:0.9.1-SNAPSHOT]
	... 18 more
Caused by: org.jets3t.service.ServiceException: Request Error.
	at org.jets3t.service.impl.rest.httpclient.RestStorageService.performRequest(RestStorageService.java:426) ~[jets3t-0.9.4.jar:0.9.4]
	at org.jets3t.service.impl.rest.httpclient.RestStorageService.performRequest(RestStorageService.java:279) ~[jets3t-0.9.4.jar:0.9.4]
	at org.jets3t.service.impl.rest.httpclient.RestStorageService.performRestHead(RestStorageService.java:1052) ~[jets3t-0.9.4.jar:0.9.4]
	at org.jets3t.service.impl.rest.httpclient.RestStorageService.getObjectImpl(RestStorageService.java:2264) ~[jets3t-0.9.4.jar:0.9.4]
	at org.jets3t.service.impl.rest.httpclient.RestStorageService.getObjectDetailsImpl(RestStorageService.java:2193) ~[jets3t-0.9.4.jar:0.9.4]
	at org.jets3t.service.StorageService.getObjectDetails(StorageService.java:1120) ~[jets3t-0.9.4.jar:0.9.4]
	at org.jets3t.service.StorageService.getObjectDetails(StorageService.java:575) ~[jets3t-0.9.4.jar:0.9.4]
	at io.druid.storage.s3.S3Utils.isObjectInBucket(S3Utils.java:92) ~[?:?]
	at io.druid.storage.s3.S3DataSegmentPuller$4.call(S3DataSegmentPuller.java:332) ~[?:?]
	at io.druid.storage.s3.S3DataSegmentPuller$4.call(S3DataSegmentPuller.java:328) ~[?:?]
	at com.metamx.common.RetryUtils.retry(RetryUtils.java:60) ~[java-util-1.3.3.jar:?]
	at com.metamx.common.RetryUtils.retry(RetryUtils.java:78) ~[java-util-1.3.3.jar:?]
	at io.druid.storage.s3.S3Utils.retryS3Operation(S3Utils.java:85) ~[?:?]
	at io.druid.storage.s3.S3DataSegmentPuller.isObjectInBucket(S3DataSegmentPuller.java:326) ~[?:?]
	at io.druid.storage.s3.S3DataSegmentPuller.getSegmentFiles(S3DataSegmentPuller.java:174) ~[?:?]
	at io.druid.storage.s3.S3LoadSpec.loadSegment(S3LoadSpec.java:62) ~[?:?]
	at io.druid.segment.loading.SegmentLoaderLocalCacheManager.getSegmentFiles(SegmentLoaderLocalCacheManager.java:143) ~[druid-server-0.9.1-SNAPSHOT.jar:0.9.1-SNAPSHOT]
	at io.druid.segment.loading.SegmentLoaderLocalCacheManager.getSegment(SegmentLoaderLocalCacheManager.java:95) ~[druid-server-0.9.1-SNAPSHOT.jar:0.9.1-SNAPSHOT]
	at io.druid.server.coordination.ServerManager.loadSegment(ServerManager.java:196) ~[druid-server-0.9.1-SNAPSHOT.jar:0.9.1-SNAPSHOT]
	at io.druid.server.coordination.ZkCoordinator.loadSegment(ZkCoordinator.java:344) ~[druid-server-0.9.1-SNAPSHOT.jar:0.9.1-SNAPSHOT]
	... 18 more
Caused by: org.jets3t.service.impl.rest.HttpException: 400 Bad Request
	at org.jets3t.service.impl.rest.httpclient.RestStorageService.performRequest(RestStorageService.java:425) ~[jets3t-0.9.4.jar:0.9.4]
	at org.jets3t.service.impl.rest.httpclient.RestStorageService.performRequest(RestStorageService.java:279) ~[jets3t-0.9.4.jar:0.9.4]
	at org.jets3t.service.impl.rest.httpclient.RestStorageService.performRestHead(RestStorageService.java:1052) ~[jets3t-0.9.4.jar:0.9.4]
	at org.jets3t.service.impl.rest.httpclient.RestStorageService.getObjectImpl(RestStorageService.java:2264) ~[jets3t-0.9.4.jar:0.9.4]
	at org.jets3t.service.impl.rest.httpclient.RestStorageService.getObjectDetailsImpl(RestStorageService.java:2193) ~[jets3t-0.9.4.jar:0.9.4]
	at org.jets3t.service.StorageService.getObjectDetails(StorageService.java:1120) ~[jets3t-0.9.4.jar:0.9.4]
	at org.jets3t.service.StorageService.getObjectDetails(StorageService.java:575) ~[jets3t-0.9.4.jar:0.9.4]
	at io.druid.storage.s3.S3Utils.isObjectInBucket(S3Utils.java:92) ~[?:?]
	at io.druid.storage.s3.S3DataSegmentPuller$4.call(S3DataSegmentPuller.java:332) ~[?:?]
	at io.druid.storage.s3.S3DataSegmentPuller$4.call(S3DataSegmentPuller.java:328) ~[?:?]
	at com.metamx.common.RetryUtils.retry(RetryUtils.java:60) ~[java-util-1.3.3.jar:?]
	at com.metamx.common.RetryUtils.retry(RetryUtils.java:78) ~[java-util-1.3.3.jar:?]
	at io.druid.storage.s3.S3Utils.retryS3Operation(S3Utils.java:85) ~[?:?]
	at io.druid.storage.s3.S3DataSegmentPuller.isObjectInBucket(S3DataSegmentPuller.java:326) ~[?:?]
	at io.druid.storage.s3.S3DataSegmentPuller.getSegmentFiles(S3DataSegmentPuller.java:174) ~[?:?]
	at io.druid.storage.s3.S3LoadSpec.loadSegment(S3LoadSpec.java:62) ~[?:?]
	at io.druid.segment.loading.SegmentLoaderLocalCacheManager.getSegmentFiles(SegmentLoaderLocalCacheManager.java:143) ~[druid-server-0.9.1-SNAPSHOT.jar:0.9.1-SNAPSHOT]
	at io.druid.segment.loading.SegmentLoaderLocalCacheManager.getSegment(SegmentLoaderLocalCacheManager.java:95) ~[druid-server-0.9.1-SNAPSHOT.jar:0.9.1-SNAPSHOT]
	at io.druid.server.coordination.ServerManager.loadSegment(ServerManager.java:196) ~[druid-server-0.9.1-SNAPSHOT.jar:0.9.1-SNAPSHOT]
	at io.druid.server.coordination.ZkCoordinator.loadSegment(ZkCoordinator.java:344) ~[druid-server-0.9.1-SNAPSHOT.jar:0.9.1-SNAPSHOT]
	... 18 more
```

**Comment by navis** [comment]
cause by bug in jets3t
