### ISSUE TITLE
Allow distribution without hadoop coordinates 

### ISSUE THREAD

**Issue by navis** [metatron-app/metatron-discovery#3172]
Cause it's not necessary

**Comment by navis** [comment]
use command to download hadoop dependencies afterward 
```
bin/node.sh tools pull-deps -h org.apache.hadoop:hadoop-client:2.7.3.2.6.5.3015-8 --useHDP
```

**Comment by seoeun25** [comment]
```
$ mvn clean package -DskipTests
$ ls -l distribution/target/druid-3.4.0-SNAPSHOT-bin.tar.gz
$ tar xzvf druid-3.4.0-SNAPSHOT-bin.tar.gz
$ cd druid-3.4.0-SNAPSHOT
$ bin/node.sh tools pull-deps -h org.apache.hadoop:hadoop-client:2.7.3.2.6.5.3015-8 --useHDP
$ ls -l hadoop-dependencies/hadoop-client/2.7.3.2.6.5.3015-8/
```
local 환경에서는 build 후에 pull-deps 으로 hadoop-client/2.7.3.2.6.5.3015-8 을 download 하는 게 잘 되는데,
엑슨투의 azure 테스트 환경에서는 pull-deps 하면 다음과 같은 에러 발생.

```
2020-04-10T13:04:51,938 INFO [main] io.druid.segment.serde.ComplexMetrics - Serde for type [string] is registered with class [class io.druid.segment.serde.StringMetricSerde]
Exception in thread "main" com.google.inject.CreationException: Unable to create injector, see the following errors:

1) Error in custom provider, java.lang.NoSuchMethodError: com.google.common.base.Preconditions.checkArgument(ZLjava/lang/String;I)V
  at io.druid.jackson.JacksonModule.jsonMapper(JacksonModule.java:46)
  at io.druid.jackson.JacksonModule.jsonMapper(JacksonModule.java:46)
  while locating com.fasterxml.jackson.databind.ObjectMapper annotated with interface io.druid.guice.annotations.Json
  while locating com.fasterxml.jackson.databind.ObjectMapper
    for the 1st parameter of io.druid.guice.JsonConfigurator.<init>(JsonConfigurator.java:68)
  at io.druid.guice.ConfigModule.configure(ConfigModule.java:40)
  while locating io.druid.guice.JsonConfigurator
    for the 2nd parameter of io.druid.guice.JsonConfigProvider.inject(JsonConfigProvider.java:274)
  at io.druid.guice.JsonConfigProvider.bind(JsonConfigProvider.java:167)

1 error
	at com.google.inject.internal.Errors.throwCreationExceptionIfErrorsExist(Errors.java:470)
	at com.google.inject.internal.InternalInjectorCreator.injectDynamically(InternalInjectorCreator.java:176)
	at com.google.inject.internal.InternalInjectorCreator.build(InternalInjectorCreator.java:110)
	at com.google.inject.Guice.createInjector(Guice.java:99)
	at com.google.inject.Guice.createInjector(Guice.java:73)
	at io.druid.guice.GuiceInjectors.makeStartupInjector(GuiceInjectors.java:79)
	at io.druid.cli.Main.main(Main.java:106)
Caused by: java.lang.NoSuchMethodError: com.google.common.base.Preconditions.checkArgument(ZLjava/lang/String;I)V
	at io.druid.query.aggregation.DecimalMetricSerde.<init>(DecimalMetricSerde.java:52)
	at io.druid.query.aggregation.DecimalMetricSerde.<init>(DecimalMetricSerde.java:66)
```

이 에러는 엑슨투 azure test 서버에서 hadoop-indexing 실행시 발생하는 에러와 동일.
