### ISSUE TITLE
Fix sporadic failure of hadoop task by guava

### ISSUE THREAD

**Issue by navis** [metatron-app/metatron-discovery#3255]
Something like,
```
2020-06-22 11:09:57,364 ERROR [main] org.apache.hadoop.mapred.YarnChild: Error running child : java.lang.NoSuchMethodError: com.google.common.base.Preconditions.checkArgument(ZLjava/lang/String;I)V
        at io.druid.query.aggregation.DecimalMetricSerde.<init>(DecimalMetricSerde.java:52)
        at io.druid.query.aggregation.DecimalMetricSerde.<init>(DecimalMetricSerde.java:66)
        at io.druid.jackson.AggregatorsModule.<init>(AggregatorsModule.java:113)
        at io.druid.jackson.DefaultObjectMapper.<init>(DefaultObjectMapper.java:57)
        at io.druid.jackson.DefaultObjectMapper.<init>(DefaultObjectMapper.java:42)
        at io.druid.jackson.JacksonModule.jsonMapper(JacksonModule.java:46)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at com.google.inject.internal.ProviderMethod.get(ProviderMethod.java:104)
        at com.google.inject.internal.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:40)
        at com.google.inject.internal.ProviderToInternalFactoryAdapter$1.call(ProviderToInternalFactoryAdapter.java:46)
        at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1031)
        at com.google.inject.internal.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:40)
        at com.google.inject.Scopes$1$1.get(Scopes.java:65)
        at com.google.inject.internal.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:40)
        at com.google.inject.internal.FactoryProxy.get(FactoryProxy.java:54)
        at com.google.inject.internal.SingleParameterInjector.inject(SingleParameterInjector.java:38)
        at com.google.inject.internal.SingleParameterInjector.getAll(SingleParameterInjector.java:62)
        at com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:84)
        at com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:254)
        at com.google.inject.internal.ProviderToInternalFactoryAdapter$1.call(ProviderToInternalFactoryAdapter.java:46)
        at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1031)
        at com.google.inject.internal.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:40)
        at com.google.inject.Scopes$1$1.get(Scopes.java:65)
        at com.google.inject.internal.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:40)
        at com.google.inject.internal.SingleParameterInjector.inject(SingleParameterInjector.java:38)
        at com.google.inject.internal.SingleParameterInjector.getAll(SingleParameterInjector.java:62)
        at com.google.inject.internal.SingleMethodInjector.inject(SingleMethodInjector.java:83)
        at com.google.inject.internal.MembersInjectorImpl.injectMembers(MembersInjectorImpl.java:110)
        at com.google.inject.internal.MembersInjectorImpl$1.call(MembersInjectorImpl.java:75)
        at com.google.inject.internal.MembersInjectorImpl$1.call(MembersInjectorImpl.java:73)
        at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1024)
        at com.google.inject.internal.MembersInjectorImpl.injectAndNotify(MembersInjectorImpl.java:73)
        at com.google.inject.internal.Initializer$InjectableReference.get(Initializer.java:147)
        at com.google.inject.internal.Initializer.injectAll(Initializer.java:92)
        at com.google.inject.internal.InternalInjectorCreator.injectDynamically(InternalInjectorCreator.java:173)
        at com.google.inject.internal.InternalInjectorCreator.build(InternalInjectorCreator.java:109)
        at com.google.inject.Guice.createInjector(Guice.java:95)
        at com.google.inject.Guice.createInjector(Guice.java:72)
        at io.druid.guice.GuiceInjectors.makeStartupInjector(GuiceInjectors.java:79)
        at io.druid.indexer.HadoopDruidIndexerConfig.<clinit>(HadoopDruidIndexerConfig.java:109)
        at io.druid.indexer.HadoopDruidIndexerMapper.setup(HadoopDruidIndexerMapper.java:63)
```

**Comment by navis** [comment]
`java -cp lib/*` 같이 했을때 jar 파일이 인식되는 순서는 OS 별로 다른데, hadoop task 의 classpath 생성 로직에도 이런 부분이 있는 것으로 짐작된다 (한시간 정도의 코드 리뷰에서는 못찾았음). 이땜에 druid-common 보다 guava 가 먼저 인식되는 경우가 있는데, 이를 의도된 순서대로 맞추는 과정이 필요. (mapreduce.job.user.classpath.first 설정과는 무관)

고민하다가 job.jar 를 druid-common 으로 지정하는 것으로 수정. 찜찜하지만 별수 없다 -_-;;

**Comment by navis** [comment]
하는 김에 mapreduce.job.user.classpath.first=true 로 고정했음.
