### ISSUE TITLE
summary query failed 

### ISSUE THREAD

**Issue by seoeun25** [metatron-app/metatron-discovery#3258]
```git history
6f3efb55c4 #3256 Apply timeout to rule runner
4bbf3aa9fe #3255 Fix sporadic failure of hadoop task by guava
752a6a069d #3248 Set numRows in DataSegment apriori
a8cdacefdf #3247 Fix result type of geom_union aggregator and performance improvement of geom_intersection
13a6baf13a #3246 Support EARLIEST / LATEST aggregator for SQL
ddb6c83ff0 #3243 Provide more interesting metrics in server view
dc592b789d #3242 Dedup data segment of curator view by segment manager
9e2ed869c1 #3241 Change repository for geotools
1e5ff7c645 #3240 Remove payload field from table sys.segment
````
hdp-3.1.1.3.1.4.0-315
```
{"queryType":"summary","dataSource":{"type":"table","name":"worldcup"},"dimensions":[],"metrics":[],"intervals":["1900-01-01T00:00:00.0Z/2051-01-01T00:00:00.0Z"],"includeTimeStats":true}
```

```
2020-06-23T08:20:14,188 INFO [qtp367035925-112] io.druid.server.QueryResource - Got query [summary:41857998-0dda-4054-905d-24351483f916]
2020-06-23T08:20:14,199 INFO [qtp367035925-112[summary_41857998-0dda-4054-905d-24351483f916]] io.druid.query.UnionAllQuery - Starting 2 parallel works with 2 threads
2020-06-23T08:20:14,201 WARN [qtp367035925-112[summary_41857998-0dda-4054-905d-24351483f916]] io.druid.server.QueryLifecycle - Exception occurred on request [SummaryQuery{dataSource='worldcup', querySegmentSpec=LegacySegmentSpec{intervals=[1900-01-01T00:00:00.000Z/2051-01-01T00:00:00.000Z]}, includeTimeStats=true, includeCovariance=false]
com.google.common.util.concurrent.UncheckedExecutionException: java.lang.NullPointerException
	at com.google.common.util.concurrent.Futures.wrapAndThrowUnchecked(Futures.java:1387) ~[guava-16.0.1.jar:?]
	at com.google.common.util.concurrent.Futures.getUnchecked(Futures.java:1373) ~[guava-16.0.1.jar:?]
	at io.druid.query.sketch.SummaryPostProcessor$1.run(SummaryPostProcessor.java:395) ~[?:?]
	at io.druid.query.BaseQuery.run(BaseQuery.java:327) ~[druid-processing-3.4.0-SNAPSHOT.jar:3.4.0-SNAPSHOT]
	at io.druid.server.QueryLifecycle.execute(QueryLifecycle.java:212) [druid-server-3.4.0-SNAPSHOT.jar:3.4.0-SNAPSHOT]
	at io.druid.server.QueryResource.doPost(QueryResource.java:274) [druid-server-3.4.0-SNAPSHOT.jar:3.4.0-SNAPSHOT]
	at sun.reflect.GeneratedMethodAccessor60.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_252]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_252]
	at com.sun.jersey.spi.container.JavaMethodInvokerFactory$1.invoke(JavaMethodInvokerFactory.java:60) [jersey-server-1.19.jar:1.19]
	at com.sun.jersey.server.impl.model.method.dispatch.AbstractResourceMethodDispatchProvider$ResponseOutInvoker._dispatch(AbstractResourceMethodDispatchProvider.java:205) [jersey-server-1.19.jar:1.19]
	at com.sun.jersey.server.impl.model.method.dispatch.ResourceJavaMethodDispatcher.dispatch(ResourceJavaMethodDispatcher.java:75) [jersey-server-1.19.jar:1.19]
	at com.sun.jersey.server.impl.uri.rules.HttpMethodRule.accept(HttpMethodRule.java:302) [jersey-server-1.19.jar:1.19]
	at com.sun.jersey.server.impl.uri.rules.ResourceClassRule.accept(ResourceClassRule.java:108) [jersey-server-1.19.jar:1.19]
	at com.sun.jersey.server.impl.uri.rules.RightHandPathRule.accept(RightHandPathRule.java:147) [jersey-server-1.19.jar:1.19]
	at com.sun.jersey.server.impl.uri.rules.RootResourceClassesRule.accept(RootResourceClassesRule.java:84) [jersey-server-1.19.jar:1.19]
	at com.sun.jersey.server.impl.application.WebApplicationImpl._handleRequest(WebApplicationImpl.java:1542) [jersey-server-1.19.jar:1.19]
	at com.sun.jersey.server.impl.application.WebApplicationImpl._handleRequest(WebApplicationImpl.java:1473) [jersey-server-1.19.jar:1.19]
	at com.sun.jersey.server.impl.application.WebApplicationImpl.handleRequest(WebApplicationImpl.java:1419) [jersey-server-1.19.jar:1.19]
	at com.sun.jersey.server.impl.application.WebApplicationImpl.handleRequest(WebApplicationImpl.java:1409) [jersey-server-1.19.jar:1.19]
	at com.sun.jersey.spi.container.servlet.WebComponent.service(WebComponent.java:409) [jersey-servlet-1.19.jar:1.19]
	at com.sun.jersey.spi.container.servlet.ServletContainer.service(ServletContainer.java:558) [jersey-servlet-1.19.jar:1.19]
	at com.sun.jersey.spi.container.servlet.ServletContainer.service(ServletContainer.java:733) [jersey-servlet-1.19.jar:1.19]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790) [javax.servlet-api-3.1.0.jar:3.1.0]
	at com.google.inject.servlet.ServletDefinition.doServiceImpl(ServletDefinition.java:286) [guice-servlet-4.1.0.jar:?]
	at com.google.inject.servlet.ServletDefinition.doService(ServletDefinition.java:276) [guice-servlet-4.1.0.jar:?]
	at com.google.inject.servlet.ServletDefinition.service(ServletDefinition.java:181) [guice-servlet-4.1.0.jar:?]
	at com.google.inject.servlet.ManagedServletPipeline.service(ManagedServletPipeline.java:91) [guice-servlet-4.1.0.jar:?]
	at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:85) [guice-servlet-4.1.0.jar:?]
	at com.google.inject.servlet.ManagedFilterPipeline.dispatch(ManagedFilterPipeline.java:120) [guice-servlet-4.1.0.jar:?]
	at com.google.inject.servlet.DelegatedGuiceFilter.doFilter(DelegatedGuiceFilter.java:86) [druid-services-3.4.0-SNAPSHOT.jar:?]
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1759) [jetty-servlet-9.3.24.v20180605.jar:9.3.24.v20180605]
	at io.druid.server.security.PreResponseAuthorizationCheckFilter.doFilter(PreResponseAuthorizationCheckFilter.java:84) [druid-server-3.4.0-SNAPSHOT.jar:3.4.0-SNAPSHOT]
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1759) [jetty-servlet-9.3.24.v20180605.jar:9.3.24.v20180605]
	at io.druid.server.security.AllowOptionsResourceFilter.doFilter(AllowOptionsResourceFilter.java:75) [druid-server-3.4.0-SNAPSHOT.jar:3.4.0-SNAPSHOT]
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1759) [jetty-servlet-9.3.24.v20180605.jar:9.3.24.v20180605]
	at io.druid.server.security.AllowAllAuthenticator$1.doFilter(AllowAllAuthenticator.java:84) [druid-server-3.4.0-SNAPSHOT.jar:3.4.0-SNAPSHOT]
	at io.druid.server.security.AuthenticationWrappingFilter.doFilter(AuthenticationWrappingFilter.java:59) [druid-server-3.4.0-SNAPSHOT.jar:3.4.0-SNAPSHOT]
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1759) [jetty-servlet-9.3.24.v20180605.jar:9.3.24.v20180605]
	at io.druid.server.security.SecuritySanityCheckFilter.doFilter(SecuritySanityCheckFilter.java:88) [druid-server-3.4.0-SNAPSHOT.jar:3.4.0-SNAPSHOT]
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1759) [jetty-servlet-9.3.24.v20180605.jar:9.3.24.v20180605]
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:582) [jetty-servlet-9.3.24.v20180605.jar:9.3.24.v20180605]
```

**Comment by ufoscw** [comment]
Summary Query
```
{"queryType":"summary","dataSource":{"type":"table","name":"__azmtp"},"dimensions":[],"metrics":[],"intervals":["1900-01-01T00:00:00.0Z/2051-01-01T00:00:00.0Z"],"includeTimeStats":true}
```

Discovery Error Log
```
2020-06-24 06:53:10.992  INFO [211.110.221.82-admin] [http-nio-8281-exec-4] a.m.d.domain.engine.EngineQueryService   : [QUERY-801fe48c-ca09-4471-9776-28ab21e026d4] Generated Druid Query : {"queryType":"summary","dataSource":{"type":"table","name":"__azmtp"},"dimensions":[],"metrics":[],"intervals":["1900-01-01T00:00:00.0Z/2051-01-01T00:00:00.0Z"],"includeTimeStats":true}
2020-06-24 06:53:11.026 ERROR [211.110.221.82-admin] [http-nio-8281-exec-4] a.m.d.d.engine.AbstractEngineRepository  : Fail to process response : [{"error":"Unknown exception","errorMessage":"java.lang.NullPointerException","errorClass":"com.google.common.util.concurrent.UncheckedExecutionException","errorStack":["com.google.common.util.concurrent.Futures.wrapAndThrowUnchecked(Futures.java:1387)","com.google.common.util.concurrent.Futures.getUnchecked(Futures.java:1373)","io.druid.query.sketch.SummaryPostProcessor$1.run(SummaryPostProcessor.java:395)","io.druid.query.BaseQuery.run(BaseQuery.java:327)","io.druid.server.QueryLifecycle.execute(QueryLifecycle.java:212)","io.druid.server.QueryResource.doPost(QueryResource.java:274)","sun.reflect.GeneratedMethodAccessor83.invoke(Unknown Source)","sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)","java.lang.reflect.Method.invoke(Method.java:498)","com.sun.jersey.spi.container.JavaMethodInvokerFactory$1.invoke(JavaMethodInvokerFactory.java:60)","com.sun.jersey.server.impl.model.method.dispatch.AbstractResourceMethodDispatchProvider$ResponseOutInvoker._dispatch(AbstractResourceMethodDispatchProvider.java:205)","com.sun.jersey.server.impl.model.method.dispatch.ResourceJavaMethodDispatcher.dispatch(ResourceJavaMethodDispatcher.java:75)","... more","Caused by: io.druid.query.aggregation.CountAggregatorFactory$1.combine(CountAggregatorFactory.java:121)","io.druid.query.aggregation.CountAggregatorFactory$1.combine(CountAggregatorFactory.java:117)","io.druid.query.groupby.AggregationQueryBinaryFn.apply(AggregationQueryBinaryFn.java:55)","io.druid.query.groupby.AggregationQueryBinaryFn.apply(AggregationQueryBinaryFn.java:31)","io.druid.common.utils.Sequences$2.accumulate(Sequences.java:101)","io.druid.java.util.common.guava.YieldingAccumulators$1.accumulate(YieldingAccumulators.java:30)","io.druid.java.util.common.guava.MappingYieldingAccumulator.accumulate(MappingYieldingAccumulator.java:55)","io.druid.java.util.common.guava.BaseSequence.makeYielder(BaseSequence.java:103)","io.druid.java.util.common.guava.BaseSequence.toYielder(BaseSequence.java:80)","io.druid.java.util.common.guava.MappedSequence.toYielder(MappedSequence.java:44)","io.druid.java.util.common.guava.ConcatSequence.makeYielder(ConcatSequence.java:77)","io.druid.java.util.common.guava.ConcatSequence.toYielder(ConcatSequence.java:60)","... more"],"host":"master2:8082","serviceName":"druid/prod/broker"}]
```

**Comment by seoeun25** [comment]
broker log

```
2020-06-24T06:53:11,015 WARN [qtp367035925-112[summary_d450ffa2-4284-4d6b-9fc0-51f7c59c4f5d]] io.druid.server.QueryLifecycle - Exception occurred on request [SummaryQuery{dataSource='__azmtp', querySegmentSpec=LegacySegmentSpec{intervals=[1900-01-01T00:00:00.000Z/2051-01-01T00:00:00.000Z]}, includeTimeStats=true, includeCovariance=false]
com.google.common.util.concurrent.UncheckedExecutionException: java.lang.NullPointerException
	at com.google.common.util.concurrent.Futures.wrapAndThrowUnchecked(Futures.java:1387) ~[guava-16.0.1.jar:?]
	at com.google.common.util.concurrent.Futures.getUnchecked(Futures.java:1373) ~[guava-16.0.1.jar:?]
	at io.druid.query.sketch.SummaryPostProcessor$1.run(SummaryPostProcessor.java:395) ~[?:?]
	at io.druid.query.BaseQuery.run(BaseQuery.java:327) ~[druid-processing-3.4.0-SNAPSHOT.jar:3.4.0-SNAPSHOT]
	at io.druid.server.QueryLifecycle.execute(QueryLifecycle.java:212) [druid-server-3.4.0-SNAPSHOT.jar:3.4.0-SNAPSHOT]
	at io.druid.server.QueryResource.doPost(QueryResource.java:274) [druid-server-3.4.0-SNAPSHOT.jar:3.4.0-SNAPSHOT]
	at sun.reflect.GeneratedMethodAccessor83.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_252]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_252]
	at com.sun.jersey.spi.container.JavaMethodInvokerFactory$1.invoke(JavaMethodInvokerFactory.java:60) [jersey-server-1.19.jar:1.19]
	at com.sun.jersey.server.impl.model.method.dispatch.AbstractResourceMethodDispatchProvider$ResponseOutInvoker._dispatch(AbstractResourceMethodDispatchProvider.java:205) [jersey-server-1.19.jar:1.19]
	at com.sun.jersey.server.impl.model.method.dispatch.ResourceJavaMethodDispatcher.dispatch(ResourceJavaMethodDispatcher.java:75) [jersey-server-1.19.jar:1.19]
	at com.sun.jersey.server.impl.uri.rules.HttpMethodRule.accept(HttpMethodRule.java:302) [jersey-server-1.19.jar:1.19]
	at com.sun.jersey.server.impl.uri.rules.ResourceClassRule.accept(ResourceClassRule.java:108) [jersey-server-1.19.jar:1.19]
	at com.sun.jersey.server.impl.uri.rules.RightHandPathRule.accept(RightHandPathRule.java:147) [jersey-server-1.19.jar:1.19]
	at com.sun.jersey.server.impl.uri.rules.RootResourceClassesRule.accept(RootResourceClassesRule.java:84) [jersey-server-1.19.jar:1.19]
	at com.sun.jersey.server.impl.application.WebApplicationImpl._handleRequest(WebApplicationImpl.java:1542) [jersey-server-1.19.jar:1.19]
	at com.sun.jersey.server.impl.application.WebApplicationImpl._handleRequest(WebApplicationImpl.java:1473) [jersey-server-1.19.jar:1.19]
	at com.sun.jersey.server.impl.application.WebApplicationImpl.handleRequest(WebApplicationImpl.java:1419) [jersey-server-1.19.jar:1.19]
	at com.sun.jersey.server.impl.application.WebApplicationImpl.handleRequest(WebApplicationImpl.java:1409) [jersey-server-1.19.jar:1.19]
	at com.sun.jersey.spi.container.servlet.WebComponent.service(WebComponent.java:409) [jersey-servlet-1.19.jar:1.19]
	at com.sun.jersey.spi.container.servlet.ServletContainer.service(ServletContainer.java:558) [jersey-servlet-1.19.jar:1.19]
	at com.sun.jersey.spi.container.servlet.ServletContainer.service(ServletContainer.java:733) [jersey-servlet-1.19.jar:1.19]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790) [javax.servlet-api-3.1.0.jar:3.1.0]
	at com.google.inject.servlet.ServletDefinition.doServiceImpl(ServletDefinition.java:286) [guice-servlet-4.1.0.jar:?]
	at com.google.inject.servlet.ServletDefinition.doService(ServletDefinition.java:276) [guice-servlet-4.1.0.jar:?]
	at com.google.inject.servlet.ServletDefinition.service(ServletDefinition.java:181) [guice-servlet-4.1.0.jar:?]
	at com.google.inject.servlet.ManagedServletPipeline.service(ManagedServletPipeline.java:91) [guice-servlet-4.1.0.jar:?]
	at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:85) [guice-servlet-4.1.0.jar:?]
	at com.google.inject.servlet.ManagedFilterPipeline.dispatch(ManagedFilterPipeline.java:120) [guice-servlet-4.1.0.jar:?]
	at com.google.inject.servlet.DelegatedGuiceFilter.doFilter(DelegatedGuiceFilter.java:86) [druid-services-3.4.0-SNAPSHOT.jar:?]
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1759) [jetty-servlet-9.3.24.v20180605.jar:9.3.24.v20180605]
	at io.druid.server.security.PreResponseAuthorizationCheckFilter.doFilter(PreResponseAuthorizationCheckFilter.java:84) [druid-server-3.4.0-SNAPSHOT.jar:3.4.0-SNAPSHOT]
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1759) [jetty-servlet-9.3.24.v20180605.jar:9.3.24.v20180605]
	at io.druid.server.security.AllowOptionsResourceFilter.doFilter(AllowOptionsResourceFilter.java:75) [druid-server-3.4.0-SNAPSHOT.jar:3.4.0-SNAPSHOT]
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1759) [jetty-servlet-9.3.24.v20180605.jar:9.3.24.v20180605]
	at io.druid.server.security.AllowAllAuthenticator$1.doFilter(AllowAllAuthenticator.java:84) [druid-server-3.4.0-SNAPSHOT.jar:3.4.0-SNAPSHOT]
	at io.druid.server.security.AuthenticationWrappingFilter.doFilter(AuthenticationWrappingFilter.java:59) [druid-server-3.4.0-SNAPSHOT.jar:3.4.0-SNAPSHOT]
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1759) [jetty-servlet-9.3.24.v20180605.jar:9.3.24.v20180605]
	at io.druid.server.security.SecuritySanityCheckFilter.doFilter(SecuritySanityCheckFilter.java:88) [druid-server-3.4.0-SNAPSHOT.jar:3.4.0-SNAPSHOT]
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1759) [jetty-servlet-9.3.24.v20180605.jar:9.3.24.v20180605]
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:582) [jetty-servlet-9.3.24.v20180605.jar:9.3.24.v20180605]
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:224) [jetty-server-9.3.24.v20180605.jar:9.3.24.v20180605]
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1180) [jetty-server-9.3.24.v20180605.jar:9.3.24.v20180605]
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:512) [jetty-servlet-9.3.24.v20180605.jar:9.3.24.v20180605]
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:185) [jetty-server-9.3.24.v20180605.jar:9.3.24.v20180605]
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1112) [jetty-server-9.3.24.v20180605.jar:9.3.24.v20180605]
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141) [jetty-server-9.3.24.v20180605.jar:9.3.24.v20180605]
	at org.eclipse.jetty.server.handler.gzip.GzipHandler.handle(GzipHandler.java:493) [jetty-server-9.3.24.v20180605.jar:9.3.24.v20180605]
	at org.eclipse.jetty.server.handler.HandlerList.handle(HandlerList.java:52) [jetty-server-9.3.24.v20180605.jar:9.3.24.v20180605]
	at org.eclipse.jetty.server.handler.StatisticsHandler.handle(StatisticsHandler.java:169) [jetty-server-9.3.24.v20180605.jar:9.3.24.v20180605]
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:134) [jetty-server-9.3.24.v20180605.jar:9.3.24.v20180605]
	at org.eclipse.jetty.server.Server.handle(Server.java:539) [jetty-server-9.3.24.v20180605.jar:9.3.24.v20180605]
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:333) [jetty-server-9.3.24.v20180605.jar:9.3.24.v20180605]
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:251) [jetty-server-9.3.24.v20180605.jar:9.3.24.v20180605]
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:283) [jetty-io-9.3.24.v20180605.jar:9.3.24.v20180605]
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:108) [jetty-io-9.3.24.v20180605.jar:9.3.24.v20180605]
	at org.eclipse.jetty.io.SelectChannelEndPoint$2.run(SelectChannelEndPoint.java:93) [jetty-io-9.3.24.v20180605.jar:9.3.24.v20180605]
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:671) [jetty-util-9.3.24.v20180605.jar:9.3.24.v20180605]
	at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:589) [jetty-util-9.3.24.v20180605.jar:9.3.24.v20180605]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_252]
Caused by: java.lang.NullPointerException
	at io.druid.query.aggregation.CountAggregatorFactory$1.combine(CountAggregatorFactory.java:121) ~[druid-processing-3.4.0-SNAPSHOT.jar:3.4.0-SNAPSHOT]
	at io.druid.query.aggregation.CountAggregatorFactory$1.combine(CountAggregatorFactory.java:117) ~[druid-processing-3.4.0-SNAPSHOT.jar:3.4.0-SNAPSHOT]
	at io.druid.query.groupby.AggregationQueryBinaryFn.apply(AggregationQueryBinaryFn.java:55) ~[druid-processing-3.4.0-SNAPSHOT.jar:3.4.0-SNAPSHOT]
	at io.druid.query.groupby.AggregationQueryBinaryFn.apply(AggregationQueryBinaryFn.java:31) ~[druid-processing-3.4.0-SNAPSHOT.jar:3.4.0-SNAPSHOT]
	at io.druid.common.utils.Sequences$2.accumulate(Sequences.java:101) ~[druid-common-3.4.0-SNAPSHOT.jar:3.4.0-SNAPSHOT]
	at io.druid.java.util.common.guava.YieldingAccumulators$1.accumulate(YieldingAccumulators.java:30) ~[java-util-3.4.0-SNAPSHOT.jar:3.4.0-SNAPSHOT]
	at io.druid.java.util.common.guava.MappingYieldingAccumulator.accumulate(MappingYieldingAccumulator.java:55) ~[java-util-3.4.0-SNAPSHOT.jar:3.4.0-SNAPSHOT]
	at io.druid.java.util.common.guava.BaseSequence.makeYielder(BaseSequence.java:103) ~[java-util-3.4.0-SNAPSHOT.jar:3.4.0-SNAPSHOT]
	at io.druid.java.util.common.guava.BaseSequence.toYielder(BaseSequence.java:80) ~[java-util-3.4.0-SNAPSHOT.jar:3.4.0-SNAPSHOT]
	at io.druid.java.util.common.guava.MappedSequence.toYielder(MappedSequence.java:44) ~[java-util-3.4.0-SNAPSHOT.jar:3.4.0-SNAPSHOT]
	at io.druid.java.util.common.guava.ConcatSequence.makeYielder(ConcatSequence.java:77) ~[java-util-3.4.0-SNAPSHOT.jar:3.4.0-SNAPSHOT]
	at io.druid.java.util.common.guava.ConcatSequence.toYielder(ConcatSequence.java:60) ~[java-util-3.4.0-SNAPSHOT.jar:3.4.0-SNAPSHOT]
	at io.druid.java.util.common.guava.ResourceClosingSequence.toYielder(ResourceClosingSequence.java:50) ~[java-util-3.4.0-SNAPSHOT.jar:3.4.0-SNAPSHOT]
	at io.druid.query.RetryQueryRunner$1.toYielder(RetryQueryRunner.java:92) ~[druid-processing-3.4.0-SNAPSHOT.jar:3.4.0-SNAPSHOT]
	at io.druid.java.util.common.guava.YieldingSequenceBase.accumulate(YieldingSequenceBase.java:32) ~[java-util-3.4.0-SNAPSHOT.jar:3.4.0-SNAPSHOT]
	at io.druid.common.utils.Sequences.accumulate(Sequences.java:96) ~[druid-common-3.4.0-SNAPSHOT.jar:3.4.0-SNAPSHOT]
	at io.druid.common.guava.CombiningSequence$1.get(CombiningSequence.java:51) ~[druid-common-3.4.0-SNAPSHOT.jar:3.4.0-SNAPSHOT]
	at io.druid.common.guava.CombiningSequence$1.get(CombiningSequence.java:47) ~[druid-common-3.4.0-SNAPSHOT.jar:3.4.0-SNAPSHOT]
	at io.druid.java.util.common.guava.LazySequence.accumulate(LazySequence.java:35) ~[java-util-3.4.0-SNAPSHOT.jar:3.4.0-SNAPSHOT]
	at io.druid.java.util.common.guava.MappedSequence.accumulate(MappedSequence.java:38) ~[java-util-3.4.0-SNAPSHOT.jar:3.4.0-SNAPSHOT]
	at io.druid.java.util.common.guava.MappedSequence.accumulate(MappedSequence.java:38) ~[java-util-3.4.0-SNAPSHOT.jar:3.4.0-SNAPSHOT]
	at io.druid.query.CPUTimeMetricQueryRunner$1.accumulate(CPUTimeMetricQueryRunner.java:77) ~[druid-processing-3.4.0-SNAPSHOT.jar:3.4.0-SNAPSHOT]
	at io.druid.common.utils.Sequences$4.accumulate(Sequences.java:213) ~[druid-common-3.4.0-SNAPSHOT.jar:3.4.0-SNAPSHOT]
	at io.druid.common.utils.Sequences.toList(Sequences.java:177) ~[druid-common-3.4.0-SNAPSHOT.jar:3.4.0-SNAPSHOT]
	at io.druid.query.sketch.SummaryPostProcessor$1$2.call(SummaryPostProcessor.java:293) ~[?:?]
	at io.druid.query.sketch.SummaryPostProcessor$1$2.call(SummaryPostProcessor.java:289) ~[?:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_252]
	at io.druid.query.PrioritizedListenableFutureTask.run(PrioritizedExecutorService.java:273) ~[druid-processing-3.4.0-SNAPSHOT.jar:3.4.0-SNAPSHOT]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[?:1.8.0_252]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[?:1.8.0_252]
	... 1 more
2020-06-24T06:53:11,019 INFO [qtp367035925-112[summary_d450ffa2-4284-4d6b-9fc0-51f7c59c4f5d]] io.druid.server.log.RequestLogger - 2020-06-24T06:53:10.990Z	10.2.10.103	{"queryType":"summary","dataSource":{"type":"table","name":"__azmtp"},"intervals":{"type":"LegacySegmentSpec","intervals":["1900-01-01T00:00:00.000Z/2051-01-01T00:00:00.000Z"]},"includeTimeStats":true,"includeCovariance":false,"context":{"queryId":"d450ffa2-4284-4d6b-9fc0-51f7c59c4f5d","timeout":60000},"descending":false}	{"query/time":29,"query/bytes":-1,"query/rows":-1,"success":false,"exception":"com.google.common.util.concurrent.UncheckedExecutionException: java.lang.NullPointerException","interrupted":false}
```
