### ISSUE TITLE
Summary query fails to return row from cache

### ISSUE THREAD

**Issue by navis** [metatron-app/metatron-discovery#3260]
```
java.lang.ClassCastException: [B cannot be cast to io.druid.query.sketch.TypedSketch
	at io.druid.query.sketch.SketchBinaryFn.apply(SketchBinaryFn.java:49) ~[druid-processing-3.4.0-SNAPSHOT.jar:3.4.0-SNAPSHOT]
	at io.druid.query.sketch.SketchBinaryFn.apply(SketchBinaryFn.java:29) ~[druid-processing-3.4.0-SNAPSHOT.jar:3.4.0-SNAPSHOT]
	at io.druid.common.guava.CombiningSequence$CombiningYieldingAccumulator.accumulate(CombiningSequence.java:225) ~[druid-common-3.4.0-SNAPSHOT.jar:3.4.0-SNAPSHOT]
	at io.druid.java.util.common.guava.BaseMergeSequence.makeYielder(BaseMergeSequence.java:51) ~[java-util-3.4.0-SNAPSHOT.jar:3.4.0-SNAPSHOT]
	at io.druid.java.util.common.guava.MergeSequence.toYielder(MergeSequence.java:64) ~[java-util-3.4.0-SNAPSHOT.jar:3.4.0-SNAPSHOT]
	at io.druid.common.guava.CombiningSequence.toYielder(CombiningSequence.java:91) ~[druid-common-3.4.0-SNAPSHOT.jar:3.4.0-SNAPSHOT]
	at io.druid.java.util.common.guava.MappedSequence.toYielder(MappedSequence.java:44) ~[java-util-3.4.0-SNAPSHOT.jar:3.4.0-SNAPSHOT]
	at io.druid.java.util.common.guava.ConcatSequence.makeYielder(ConcatSequence.java:77) ~[java-util-3.4.0-SNAPSHOT.jar:3.4.0-SNAPSHOT]
	at io.druid.java.util.common.guava.ConcatSequence.toYielder(ConcatSequence.java:60) ~[java-util-3.4.0-SNAPSHOT.jar:3.4.0-SNAPSHOT]
	at io.druid.query.CPUTimeMetricQueryRunner$1.toYielder(CPUTimeMetricQueryRunner.java:89) ~[druid-processing-3.4.0-SNAPSHOT.jar:3.4.0-SNAPSHOT]
	at io.druid.common.utils.Sequences$4.toYielder(Sequences.java:221) ~[druid-common-3.4.0-SNAPSHOT.jar:3.4.0-SNAPSHOT]
	at io.druid.java.util.common.guava.ResourceClosingSequence.toYielder(ResourceClosingSequence.java:50) ~[java-util-3.4.0-SNAPSHOT.jar:3.4.0-SNAPSHOT]
	at io.druid.server.QueryResource.doPost(QueryResource.java:280) [druid-server-3.4.0-SNAPSHOT.jar:3.4.0-SNAPSHOT]
	at sun.reflect.GeneratedMethodAccessor105.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_202]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_202]
	at com.sun.jersey.spi.container.JavaMethodInvokerFactory$1.invoke(JavaMethodInvokerFactory.java:60) [jersey-server-1.19.jar:1.19]
	at com.sun.jersey.server.impl.model.method.dispatch.AbstractResourceMethodDispatchProvider$ResponseOutInvoker._dispatch(AbstractResourceMethodDispatchProvider.java:205) [jersey-server-1.19.jar:1.19]
	at com.sun.jersey.server.impl.model.method.dispatch.ResourceJavaMethodDispatcher.dispatch(ResourceJavaMethodDispatcher.java:75) [jersey-server-1.19.jar:1.19]
	at com.sun.jersey.server.impl.uri.rules.HttpMethodRule.accept(HttpMethodRule.java:302) [jersey-server-1.19.jar:1.19]
	at com.sun.jersey.server.impl.uri.rules.ResourceClassRule.accept(ResourceClassRule.java:108) [jersey-server-1.19.jar:1.19]
	at com.sun.jersey.server.impl.uri.rules.RightHandPathRule.accept(RightHandPathRule.java:147) [jersey-server-1.19.jar:1.19]
```

**Comment by navis** [comment]
Regression from #3137
