### ISSUE TITLE
IllegalAccessError calling UDAF of hive

### ISSUE THREAD

**Issue by navis** [metatron-app/metatron-discovery#3287]
```
03:35:32 [qtp1780974980-117[timeseries_0f3c4ffb-f588-4bb2-9b79-f760aa5fbe33]] - Exception occurred on request [TimeseriesQuery{dataSource='rcem_enb_1d', descending=false, granularity=AllGranularity, limitSpec=NoopLimitSpec{}, aggregatorSpecs=[HiveUDAFAggregatorFactory{name='a0', udafName='hdv_sum_cei', fieldNames=[hdv_et, hdv_silence_except_et, hdv_attempt_cnt, hdv_success_cnt, hdv_drop_cnt, hdv_qoe1_kpi3, hdv_qoe2_value, hdv_user_cnt], inputTypes=[double, double, double, double, double, double, double, double], outputType=struct(hdvoiceceivalue:double,hdvoiceqoe1value:double,hdvoiceqoe2value:double,hdvoiceqoe1kpi1:double,hdvoiceqoe1kpi2:double,hdvoiceqoe1kpi3:double,hdvoiceqoe1qos1:double,hdvoiceattempt:double,hdvoicesuccess:double,hdvoicecomplete:double,hdvoicedrop:double,et:double,hdvoicecalculatedet:double,hdvoicebadet:double,hdveusercount:double,hdvsilenceexceptet:double), finalizedType=string, merge=false}], outputColumns=[a0], context={groupby.sort.on.time=false, queryId=0f3c4ffb-f588-4bb2-9b79-f760aa5fbe33, timeout=60000}}]
java.lang.IllegalAccessError: tried to access field org.apache.hadoop.hive.ql.udf.generic.GenericUDAFBridge$GenericUDAFBridgeEvaluator.conversionHelper from class org.apache.hadoop.hive.ql.udf.generic.Hack
        at org.apache.hadoop.hive.ql.udf.generic.Hack.synchronize(Hack.java:38) ~[druid-hive-udf-extensions-3.4.0-SNAPSHOT.jar:2.0.0]
        at io.druid.hive.HiveUDAFAggregatorFactory.prepare(HiveUDAFAggregatorFactory.java:283) ~[druid-hive-udf-extensions-3.4.0-SNAPSHOT.jar:3.4.0-SNAPSHOT]
        at io.druid.hive.HiveUDAFAggregatorFactory.toCombiner(HiveUDAFAggregatorFactory.java:322) ~[druid-hive-udf-extensions-3.4.0-SNAPSHOT.jar:3.4.0-SNAPSHOT]
        at io.druid.hive.HiveUDAFAggregatorFactory.combiner(HiveUDAFAggregatorFactory.java:317) ~[druid-hive-udf-extensions-3.4.0-SNAPSHOT.jar:3.4.0-SNAPSHOT]
        at io.druid.query.aggregation.AggregatorFactory.toCombiner(AggregatorFactory.java:370) ~[druid-processing-3.4.0-SNAPSHOT.jar:3.4.0-SNAPSHOT]
        at io.druid.query.aggregation.AggregatorFactory.toCombinerArray(AggregatorFactory.java:377) ~[druid-processing-3.4.0-SNAPSHOT.jar:3.4.0-SNAPSHOT]
        at io.druid.query.groupby.AggregationQueryBinaryFn.<init>(AggregationQueryBinaryFn.java:39) ~[druid-processing-3.4.0-SNAPSHOT.jar:3.4.0-SNAPSHOT]
        at io.druid.query.BaseAggregationQueryToolChest.getMergeFn(BaseAggregationQueryToolChest.java:97) ~[druid-processing-3.4.0-SNAPSHOT.jar:3.4.0-SNAPSHOT]
        at io.druid.query.BaseAggregationQueryToolChest$1.run(BaseAggregationQueryToolChest.java:78) ~[druid-processing-3.4.0-SNAPSHOT.jar:3.4.0-SNAPSHOT]
        at io.druid.query.FinalizeResultsQueryRunner.run(FinalizeResultsQueryRunner.java:89) ~[druid-processing-3.4.0-SNAPSHOT.jar:3.4.0-SNAPSHOT]
        at io.druid.query.BaseAggregationQueryToolChest$9.run(BaseAggregationQueryToolChest.java:352) ~[druid-processing-3.4.0-SNAPSHOT.jar:3.4.0-SNAPSHOT]
        at io.druid.query.PostProcessingOperators$1.run(PostProcessingOperators.java:49) ~[druid-processing-3.4.0-SNAPSHOT.jar:3.4.0-SNAPSHOT]
        at io.druid.query.CPUTimeMetricQueryRunner.run(CPUTimeMetricQueryRunner.java:68) ~[druid-processing-3.4.0-SNAPSHOT.jar:3.4.0-SNAPSHOT]
        at io.druid.query.BaseQuery.run(BaseQuery.java:327) ~[druid-processing-3.4.0-SNAPSHOT.jar:3.4.0-SNAPSHOT]
        at io.druid.server.QueryLifecycle.execute(QueryLifecycle.java:212) [druid-server-3.4.0-SNAPSHOT.jar:3.4.0-SNAPSHOT]
        at io.druid.server.QueryResource.doPost(QueryResource.java:274) [druid-server-3.4.0-SNAPSHOT.jar:3.4.0-SNAPSHOT]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_202]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_202]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_202]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_202]
        at com.sun.jersey.spi.container.JavaMethodInvokerFactory$1.invoke(JavaMethodInvokerFactory.java:60) [jersey-server-1.19.jar:1.19]
        at com.sun.jersey.server.impl.model.method.dispatch.AbstractResourceMethodDispatchProvider$ResponseOutInvoker._dispatch(AbstractResourceMethodDispatchProvider.java:205) [jersey-server-1.19.jar:1.19]
```

**Comment by navis** [comment]
Regression from #3103
