### ISSUE TITLE
Fix config query

### ISSUE THREAD

**Issue by navis** [metatron-app/metatron-discovery#3318]
It's not working on multiple nodes.
```
java.lang.ClassCastException: java.util.LinkedHashMap cannot be cast to java.lang.Comparable
        at io.druid.common.guava.GuavaUtils$1.compare(GuavaUtils.java:75) ~[druid-common-3.4.0-SNAPSHOT.jar:3.4.0-SNAPSHOT]
        at com.google.common.collect.ComparatorOrdering.compare(ComparatorOrdering.java:38) ~[guava-16.0.1.jar:?]
        at com.google.common.collect.ByFunctionOrdering.compare(ByFunctionOrdering.java:46) ~[guava-16.0.1.jar:?]
        at it.unimi.dsi.fastutil.objects.ObjectHeaps.upHeap(ObjectHeaps.java:106) ~[fastutil-8.2.2.jar:?]
        at it.unimi.dsi.fastutil.objects.ObjectHeapPriorityQueue.enqueue(ObjectHeapPriorityQueue.java:183) ~[fastutil-8.2.2.jar:?]
        at io.druid.java.util.common.guava.BaseMergeSequence.createQueue(BaseMergeSequence.java:32) ~[java-util-3.4.0-SNAPSHOT.jar:3.4.0-SNAPSHOT]
        at io.druid.java.util.common.guava.MergeSequence.toYielder(MergeSequence.java:64) ~[java-util-3.4.0-SNAPSHOT.jar:3.4.0-SNAPSHOT]
        at io.druid.query.RetryQueryRunner$1.toYielder(RetryQueryRunner.java:92) ~[druid-processing-3.4.0-SNAPSHOT.jar:3.4.0-SNAPSHOT]
        at io.druid.java.util.common.guava.MappedSequence.toYielder(MappedSequence.java:44) ~[java-util-3.4.0-SNAPSHOT.jar:3.4.0-SNAPSHOT]
        at io.druid.query.CPUTimeMetricQueryRunner$1.toYielder(CPUTimeMetricQueryRunner.java:89) ~[druid-processing-3.4.0-SNAPSHOT.jar:3.4.0-SNAPSHOT]
        at io.druid.common.utils.Sequences$4.toYielder(Sequences.java:221) ~[druid-common-3.4.0-SNAPSHOT.jar:3.4.0-SNAPSHOT]
        at io.druid.java.util.common.guava.ResourceClosingSequence.toYielder(ResourceClosingSequence.java:52) ~[java-util-3.4.0-SNAPSHOT.jar:3.4.0-SNAPSHOT]
        at io.druid.server.QueryResource.doPost(QueryResource.java:275) [druid-server-3.4.0-SNAPSHOT.jar:3.4.0-SNAPSHOT]
```

**Comment by navis** [comment]
Also added simple config checking REST API
```
curl -X GET "http://localhost:8083/druid/admin/config/druid.query.groupBy"
{
  "singleThreaded" : false,
  "maxResults" : 2000000,
  "sortOnTime" : true,
  "preOrdering" : false,
  "removeOrdering" : false,
  "convertTimeseries" : true,
  "convertFrequency" : false,
  "convertFrequencyCardinality" : 262144,
  "estimateTopNFactor" : -1,
  "useParallelSort" : true,
  "useRawUTF8" : true,
  "useBulkRow" : true,
  "localSplitNum" : -1,
  "localSplitCardinality" : 200000,
  "maxStreamSubQueryPage" : 4
}
```
