### ISSUE TITLE
Remove metamx java-util dependency

### ISSUE THREAD

**Issue by seoeun25** [metatron-app/metatron-discovery#3349]
Currently we have two java-util dependency.
* java-util-1.3.3.jar
* java-util-3.4.0-SNAPSHOT.jar

We need remove metamx java-util-1.3.3.

**Comment by seoeun25** [comment]
`
Caused by: java.lang.NoClassDefFoundError: io/druid/collections/CountingMap
	at io.druid.indexer.hadoop.DatasourceInputFormat.getFrequentLocations(DatasourceInputFormat.java:219) ~[?:?]
	at io.druid.indexer.path.HadoopCombineInputFormat$HadoopSplit.getLocations(HadoopCombineInputFormat.java:217) ~[?:?]
	at org.apache.hadoop.mapreduce.split.JobSplitWriter.writeNewSplits(JobSplitWriter.java:136) ~[?:?]
	at org.apache.hadoop.mapreduce.split.JobSplitWriter.createSplitFiles(JobSplitWriter.java:80) ~[?:?]
	at org.apache.hadoop.mapreduce.JobSubmitter.writeNewSplits(JobSubmitter.java:316) ~[?:?]
	at org.apache.hadoop.mapreduce.JobSubmitter.writeSplits(JobSubmitter.java:327) ~[?:?]
	at org.apache.hadoop.mapreduce.JobSubmitter.submitJobInternal(JobSubmitter.java:200) ~[?:?]
	at org.apache.hadoop.mapreduce.Job$11.run(Job.java:1570) ~[?:?]
	at org.apache.hadoop.mapreduce.Job$11.run(Job.java:1567) ~[?:?]
	at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_252]
	at javax.security.auth.Subject.doAs(Subject.java:422) ~[?:1.8.0_252]
	at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1730) ~[?:?]
	at org.apache.hadoop.mapreduce.Job.submit(Job.java:1567) ~[?:?]
	at io.druid.indexer.ReduceMergeIndexGeneratorJob.run(ReduceMergeIndexGeneratorJob.java:132) ~[?:?]
	at io.druid.indexer.JobHelper.runJobs(JobHelper.java:342) ~[?:?]
	at io.druid.indexer.HadoopDruidIndexerJob.run(HadoopDruidIndexerJob.java:104) ~[?:?]
	at io.druid.indexing.common.task.HadoopIndexTask$HadoopIndexGeneratorInnerProcessing.runTask(HadoopIndexTask.java:349) ~[?:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_252]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_252]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_252]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_252]
	at io.druid.indexing.common.task.HadoopTask.invokeForeignLoader(HadoopTask.java:206) ~[druid-indexing-service-3.4.0-SNAPSHOT.jar:3.4.0-SNAPSHOT]
	... 7 more
`
