### ISSUE TITLE
Ingestion fails to hive table with parquet format

### ISSUE THREAD

**Issue by seoeun25** [metatron-app/metatron-discovery#3380]
Use DruidParquetInputFormat in druid-parquet-extensions.

```
java.lang.ClassCastException: org.apache.hadoop.io.ArrayWritable cannot be cast to org.apache.avro.generic.GenericRecord
	at io.druid.data.input.ParquetHadoopInputRowParser.parse(ParquetHadoopInputRowParser.java:38) ~[druid-parquet-extensions-3.4.0-SNAPSHOT.jar:3.4.0-SNAPSHOT]
	at io.druid.data.input.InputRowParsers$2.parse(InputRowParsers.java:148) [druid-processing-3.4.0-SNAPSHOT.jar:3.4.0-SNAPSHOT]
	at io.druid.indexer.HadoopDruidIndexerMapper.parseInputRow(HadoopDruidIndexerMapper.java:174) [druid-indexing-hadoop-3.4.0-SNAPSHOT.jar:3.4.0-SNAPSHOT]
	at io.druid.indexer.HadoopDruidIndexerMapper.map(HadoopDruidIndexerMapper.java:106) [druid-indexing-hadoop-3.4.0-SNAPSHOT.jar:3.4.0-SNAPSHOT]
	at io.druid.indexer.ReduceMergeIndexGeneratorJob$ReducerMergingMapper.run(ReduceMergeIndexGeneratorJob.java:185) [druid-indexing-hadoop-3.4.0-SNAPSHOT.jar:3.4.0-SNAPSHOT]
	at org.apache.hadoop.mapred.MapTask.runNewMapper(MapTask.java:799) [hadoop-mapreduce-client-core-3.1.1.3.1.4.0-315.jar:?]
	at org.apache.hadoop.mapred.MapTask.run(MapTask.java:347) [hadoop-mapreduce-client-core-3.1.1.3.1.4.0-315.jar:?]
```

**Comment by navis** [comment]
Possibly induces class loader conflict. Should find better way than this.
