### ISSUE TITLE
Reuse previous bound for query splitting

### ISSUE THREAD

**Issue by navis** [metatron-app/metatron-discovery#3499]

**Comment by seoeun25** [comment]
NullPointerException occurs.

broker query
```
2020-11-17T03:01:01,693 INFO [qtp1856662284-126[groupBy_QUERY-7edd47ac-7cb0-4bab-bc43-7828d9081181]] io.druid.server.log.RequestLogger - 2020-11-17T03:01:01.424Z       10.2.10.103     {"queryType":"groupBy","dataSource":{"type":"table","name":"user_reco_impression_daily_raw__tmembership_01"},"intervals":{"type":"LegacySegmentSpec","intervals":["2020-11-01T00:00:00.000Z/2020-11-30T23:59:00.000Z"]},"granularity":{"type":"all"},"virtualColumns":[{"type":"expr","expression":"SUBSTRING( \"dt\"?| ?| , 1, 10 )","outputName":"user_defined.DIMENSION_1"}],"aggregations":[{"type":"cardinality","name":"aggregationfunc_000","fieldNames":["user_id"],"predicate":"\"channel_id\"=='mbr_curation_banner'&&\"funnel\"=='display'","byRow":true,"round":false,"b":11},{"type":"cardinality","name":"aggregationfunc_001","fieldNames":["user_id"],"predicate":"\"channel_id\"=='mbr_curation_banner'&&(\"funnel\"=='click'||\"funnel\"=='impression')","byRow":true,"round":false,"b":11},{"type":"cardinality","name":"aggregationfunc_002","fieldNames":["user_id"],"predicate":"\"channel_id\"=='mbr_curation_banner'&&\"funnel\"=='click'","byRow":true,"round":false,"b":11},{"type":"cardinality","name":"aggregationfunc_003","fieldNames":["user_id"],"predicate":"\"channel_id\"!='mbr_curation_banner'","byRow":true,"round":false,"b":11},{"type":"cardinality","name":"aggregationfunc_004","fieldNames":["user_id"],"predicate":"\"channel_id\"!='mbr_curation_banner'&&\"funnel\"=='click'","byRow":true,"round":false,"b":11},{"type":"cardinality","name":"aggregationfunc_005","fieldNames":["user_id"],"predicate":"\"channel_id\"!='mbr_curation_banner'&&(\"funnel\"=='click'||\"funnel\"=='impression')","byRow":true,"round":false,"b":11},{"type":"cardinality","name":"aggregationfunc_006","fieldNames":["user_id"],"predicate":"\"channel_id\"!='mbr_curation_banner'&&\"funnel\"=='like'","byRow":true,"round":false,"b":11},{"type":"cardinality","name":"aggregationfunc_007","fieldNames":["user_id"],"predicate":"\"channel_id\"!='mbr_curation_banner'&&\"funnel\"=='dislike'","byRow":true,"round":false,"b":11}],"postAggregations":[{"type":"math","name":"Curation 배?~D~H ?~C~]?~D? ?| ?~] ?~H~X","expression":"ROUND(aggregaa  
tionfunc_000)","finalize":true},{"type":"math","name":"Curation 배?~D~H ?~E??~\ ?| ?~] ?~H~X","expression":"ROUND(aggregationn   
func_001)","finalize":true},{"type":"math","name":"Curation 배?~D~H ?~A?릭 ?| ?~] ?~H~X","expression":"ROUND(aggregationfunc__   
002)","finalize":true},{"type":"math","name":"Curation ?~D?~^~E ?| ?~] ?~H~X","expression":"ROUND(aggregationfunc_003)","finall  
ize":true},{"type":"math","name":"Curation ?~A?릭 ?| ?~] ?~H~X","expression":"ROUND(aggregationfunc_004)","finalize":true},{"tt  
ype":"math","name":"Curation ?~E??~\ ?| ?~] ?~H~X","expression":"ROUND(aggregationfunc_005)","finalize":true},{"type":"math",""  
name":"Curation ?~K?~U~D?~Z~T ?| ?~] ?~H~X","expression":"ROUND(aggregationfunc_006)","finalize":true},{"type":"math","name":""  
Curation ?~K??~V??~Z~T ?| ?~] ?~H~X","expression":"ROUND(aggregationfunc_007)","finalize":true}],"limitSpec":{"type":"default",, 
"limit":1000,"windowingSpecs":[{"skipSorting":false,"pivotSpec":{"valueColumns":["Curation 배?~D~H ?~C~]?~D? ?| ?~] ?~H~X","Cuu  
ration 배?~D~H ?~E??~\ ?| ?~] ?~H~X","Curation 배?~D~H ?~A?릭 ?| ?~] ?~H~X","Curation ?~D?~^~E ?| ?~] ?~H~X","Curationn          
 ?~A?릭 ?| ?~] ?~H~X","Curation ?~E??~\ ?| ?~] ?~H~X","Curation ?~K?~U~D?~Z~T ?| ?~] ?~H~X","Curation ?~K??~V??~Z~T ?|           
?~] ?~H~X"],"separator":"?~@~U","partitionExpressions":[{"expression":"#_ = $sum(_)"},{"expression":"concat(_, '.percent') = cass
e(#_ == 0, 0.0, cast(\"_\", 'DOUBLE') / #_ * 100)"}],"tabularFormat":true,"appendValueColumn":true}}]},"context":{"queryId":"QUERY-7edd47ac-7cb0-4bab-bc43-7828d9081181","timeout":60000},"descending":false}       {"query/time":269,"query/bytes":-1,"query/rows":-1,"success":false,"exception":"io.druid.query.QueryInterruptedException","interrupted":true}
```
historical exception
```
2020-11-17T03:01:01,685 INFO [qtp1677960357-97[groupBy_QUERY-7edd47ac-7cb0-4bab-bc43-7828d9081181]] io.druid.server.coordination.ServerManager - Running resolved [QUERY-7edd47ac-7cb0-4bab-bc43-7828d9081181][groupBy:user_reco_impression_daily_raw__tmembership_01] on [6] segments
2020-11-17T03:01:01,690 ERROR [processing-4] io.druid.query.GroupByMergedQueryRunner - Exception with one of the sequences!
java.lang.NullPointerException: null
        at io.druid.segment.filter.Filters.toExprBitmap(Filters.java:789) ~[druid-processing-3.4.0-SNAPSHOT.jar:3.4.0-SNAPSHOT]
        at io.druid.segment.filter.Filters.leafToBitmap(Filters.java:545) ~[druid-processing-3.4.0-SNAPSHOT.jar:3.4.0-SNAPSHOT]
        at io.druid.segment.filter.FilterContext.lambda$createBitmap$0(FilterContext.java:56) ~[druid-processing-3.4.0-SNAPSHOT.jar:3.4.0-SNAPSHOT]
        at io.druid.segment.filter.FilterContext.createBitmap(FilterContext.java:62) ~[druid-processing-3.4.0-SNAPSHOT.jar:3.4.0-SNAPSHOT]
        at io.druid.segment.filter.FilterContext.createBitmap(FilterContext.java:56) ~[druid-processing-3.4.0-SNAPSHOT.jar:3.4.0-SNAPSHOT]
        at io.druid.segment.filter.Filters.toBitmapHolderRecurse(Filters.java:527) ~[druid-processing-3.4.0-SNAPSHOT.jar:3.4.0-SNAPSHOT]
        at io.druid.segment.filter.Filters.toBitmapHolder(Filters.java:498) ~[druid-processing-3.4.0-SNAPSHOT.jar:3.4.0-SNAPSHOT]
        at io.druid.segment.QueryableIndexStorageAdapter$CursorSequenceBuilder$2$1.makePredicateMatcher(QueryableIndexStorageAdapter.java:1021) ~[druid-processing-3.4.0-SNAPSHOT.jar:3.4.0-SNAPSHOT]
        at io.druid.segment.ColumnSelectors.toMatcher(ColumnSelectors.java:309) ~[druid-processing-3.4.0-SNAPSHOT.jar:3.4.0-SNAPSHOT]

```
