### ISSUE TITLE
FIx KafkaIndexTask failures corresponding to sequence_name_prev_id_sha1 unique constraint violations

### ISSUE THREAD

**Issue by seoeun25** [metatron-app/metatron-discovery#3502]
Fix IndexerSQLMetadataStorageCoordinator.allocatePendingSegment() to respect skipSegmentLineageCheck to avoid the unique constraint violation for sequence_name_prev_id_sha1.

Related apache 5805.

```
com.mysql.jdbc.exceptions.jdbc4.MySQLIntegrityConstraintViolationException: Duplicate entry 'AFFB8242EADEB78AA4FFF7C8BF963A3D6767A7AA' for key 'sequence_name_prev_id_sha1'

at io.druid.metadata.SQLMetadataConnector$3.call(SQLMetadataConnector.java:151) ~[druid-server-3.4.0-SNAPSHOT.jar:3.4.0-SNAPSHOT]
        at io.druid.java.util.common.RetryUtils.retry(RetryUtils.java:58) ~[java-util-3.4.0-SNAPSHOT.jar:3.4.0-SNAPSHOT]
        at io.druid.metadata.SQLMetadataConnector.retryTransaction(SQLMetadataConnector.java:155) ~[druid-server-3.4.0-SNAPSHOT.jar:3.4.0-SNAPSHOT]
        at io.druid.metadata.IndexerSQLMetadataStorageCoordinator.allocatePendingSegment(IndexerSQLMetadataStorageCoordinator.java:393) ~[druid-server-3.4.0-SNAPSHOT.jar:3.4.0-SNAPSHOT]
        at io.druid.indexing.common.actions.SegmentAllocateAction.perform(SegmentAllocateAction.java:190) ~[druid-indexing-service-3.4.0-SNAPSHOT.jar:3.4.0-SNAPSHOT]
        at io.druid.indexing.common.actions.SegmentAllocateAction.perform(SegmentAllocateAction.java:53) ~[druid-indexing-service-3.4.0-SNAPSHOT.jar:3.4.0-SNAPSHOT]
```

**Comment by seoeun25** [comment]
@alchan-lee 참고하세요.
