### ISSUE TITLE
K-means tagging query is not woorking

### ISSUE THREAD

**Issue by navis** [metatron-app/metatron-discovery#3575]
```
Caused by: java.lang.ClassCastException: io.druid.query.kmeans.Centroid cannot be cast to [Ljava.lang.Object;
	at io.druid.data.output.GeoJsonDecorator.serialize(GeoJsonDecorator.java:47) ~[?:?]
	at io.druid.server.QueryResource$RequestContext$1.serialize(QueryResource.java:455) ~[druid-server-3.4.0-SNAPSHOT.jar:3.4.0-SNAPSHOT]
	at io.druid.server.QueryResource$RequestContext$1.serialize(QueryResource.java:447) ~[druid-server-3.4.0-SNAPSHOT.jar:3.4.0-SNAPSHOT]
	at com.fasterxml.jackson.databind.ser.DefaultSerializerProvider.serializeValue(DefaultSerializerProvider.java:128) ~[jackson-databind-2.4.6.jar:2.4.6]
	... 62 more
```

**Comment by navis** [comment]
regression from #3536
