### ISSUE TITLE
UnsupportedOperationException thrown by SystemSchema$TasksTable$1TasksEnumerable.iterator

### ISSUE THREAD

**Issue by seoeun25** [metatron-app/metatron-discovery#3581]
**Query**
```
SELECT
  "task_id", "type", "datasource", "created_time",
  CASE WHEN "status" = 'RUNNING' THEN "runner_status" ELSE "status" END AS "status",
  CASE WHEN "status" = 'RUNNING' THEN
   (CASE WHEN "runner_status" = 'RUNNING' THEN 4 WHEN "runner_status" = 'PENDING' THEN 3 ELSE 2 END)
  ELSE 1 END AS "rank",
  "location", "duration", "error_msg"
FROM sys.tasks
LIMIT 10
```

**Exception**
```
java.lang.UnsupportedOperationException: Do not use iterator(), it cannot be closed.
        at io.druid.sql.calcite.schema.SystemSchema$TasksTable$1TasksEnumerable.iterator(SystemSchema.java:510) ~[druid-sql-3.4.0-SNAPSHOT.jar:3.4.0-SNAPSHOT]
        at io.druid.common.utils.Sequences$1.make(Sequences.java:85) ~[druid-common-3.4.0-SNAPSHOT.jar:3.4.0-SNAPSHOT]
        at io.druid.common.guava.BaseSequence.toYielder(BaseSequence.java:70) ~[druid-common-3.4.0-SNAPSHOT.jar:3.4.0-SNAPSHOT]
        at io.druid.common.Yielders.each(Yielders.java:37) ~[druid-common-3.4.0-SNAPSHOT.jar:3.4.0-SNAPSHOT]
        at io.druid.common.utils.Sequences$9.<init>(Sequences.java:481) ~[druid-common-3.4.0-SNAPSHOT.jar:3.4.0-SNAPSHOT]
        at io.druid.common.utils.Sequences.toIterator(Sequences.java:479) ~[druid-common-3.4.0-SNAPSHOT.jar:3.4.0-SNAPSHOT]
        at io.druid.segment.ColumnSelectorFactories.toCursors(ColumnSelectorFactories.java:827) ~[druid-processing-3.4.0-SNAPSHOT.jar:3.4.0-SNAPSHOT]
        at io.druid.segment.ColumnSelectorFactories.toArrayCursors(ColumnSelectorFactories.java:820) ~[druid-processing-3.4.0-SNAPSHOT.jar:3.4.0-SNAPSHOT]
        at io.druid.query.QueryToolChest$SubQueryRunner.runStreaming(QueryToolChest.java:363) ~[druid-processing-3.4.0-SNAPSHOT.jar:3.4.0-SNAPSHOT]
        at io.druid.query.QueryToolChest$StreamingSubQueryRunner.runStreaming(QueryToolChest.java:393) ~[druid-processing-3.4.0-SNAPSHOT.jar:3.4.0-SNAPSHOT]
        at io.druid.query.select.StreamQueryToolChest$3.runStreaming(StreamQueryToolChest.java:167) ~[druid-processing-3.4.0-SNAPSHOT.jar:3.4.0-SNAPSHOT]
        at io.druid.query.QueryToolChest$StreamingSubQueryRunner.run(QueryToolChest.java:403) ~[druid-processing-3.4.0-SNAPSHOT.jar:3.4.0-SNAPSHOT]

```

**Comment by navis** [comment]
regression from #3562
