### ISSUE TITLE
Query block on indexing node

### ISSUE THREAD

**Issue by navis** [metatron-app/metatron-discovery#3607]
```
"qtp923570200-77[select.stream_QUERY-0dbe34b6-6382-4499-900d-23c1941bc6bc_2021-03-02T02:07:44.000Z/2021-03-02T02:17:44.000Z_2021-03-02T00:00:07.569Z_1]" #77 daemon prio=5 os_prio=0 tid=0x00007f09fa65c800 nid=0x6bb waiting on condition [0x00007f08d30ee000]
   java.lang.Thread.State: WAITING (parking)
	at sun.misc.Unsafe.park(Native Method)
	- parking to wait for  <0x00000000fb99e0b0> (a java.util.concurrent.Semaphore$NonfairSync)
	at java.util.concurrent.locks.LockSupport.park(LockSupport.java:175)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer.parkAndCheckInterrupt(AbstractQueuedSynchronizer.java:836)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer.doAcquireSharedInterruptibly(AbstractQueuedSynchronizer.java:997)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer.acquireSharedInterruptibly(AbstractQueuedSynchronizer.java:1304)
	at java.util.concurrent.Semaphore.acquire(Semaphore.java:312)
	at io.druid.concurrent.Execs$Semaphore.acquire(Execs.java:317)
	at io.druid.concurrent.Execs$4.run(Execs.java:396)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at io.druid.common.guava.DirectExecutorService.execute(DirectExecutorService.java:56)
	at java.util.concurrent.AbstractExecutorService.submit(AbstractExecutorService.java:112)
	at com.google.common.util.concurrent.AbstractListeningExecutorService.submit(AbstractListeningExecutorService.java:50)
	at com.google.common.util.concurrent.AbstractListeningExecutorService.submit(AbstractListeningExecutorService.java:37)
	at io.druid.concurrent.Execs.execute(Execs.java:383)
	at io.druid.query.QueryRunners$10.run(QueryRunners.java:247)
	at io.druid.query.BySegmentQueryRunner.run(BySegmentQueryRunner.java:65)
	at io.druid.query.MetricsEmittingQueryRunner.run(MetricsEmittingQueryRunner.java:95)
	at io.druid.query.MetricsEmittingQueryRunner.run(MetricsEmittingQueryRunner.java:95)
	at io.druid.query.CPUTimeMetricQueryRunner.run(CPUTimeMetricQueryRunner.java:68)
	at io.druid.query.spec.SpecificSegmentQueryRunner$1.call(SpecificSegmentQueryRunner.java:84)
	at io.druid.query.spec.SpecificSegmentQueryRunner$1.call(SpecificSegmentQueryRunner.java:80)
	at io.druid.query.spec.SpecificSegmentQueryRunner.doNamed(SpecificSegmentQueryRunner.java:185)
	at io.druid.query.spec.SpecificSegmentQueryRunner.run(SpecificSegmentQueryRunner.java:78)
	at io.druid.query.QueryRunners$8.run(QueryRunners.java:218)
	at io.druid.query.select.StreamQueryToolChest$1.run(StreamQueryToolChest.java:74)
	at io.druid.query.CPUTimeMetricQueryRunner.run(CPUTimeMetricQueryRunner.java:68)
	at io.druid.query.QueryRunners$4.run(QueryRunners.java:120)
	at io.druid.query.BaseQuery.run(BaseQuery.java:376)
	at io.druid.indexing.kafka.KafkaIndexTask$8.run(KafkaIndexTask.java:1365)
	at io.druid.query.BaseQuery.run(BaseQuery.java:376)
	at io.druid.server.QueryLifecycle.execute(QueryLifecycle.java:218)
	at io.druid.server.QueryResource.doPost(QueryResource.java:270)
	at sun.reflect.GeneratedMethodAccessor25.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.sun.jersey.spi.container.JavaMethodInvokerFactory$1.invoke(JavaMethodInvokerFactory.java:60)
```

QueryRunners.executeParallel() should not be called with direct executor.

**Comment by navis** [comment]
regression from #3589
