### ISSUE TITLE
CCE retrieving topN query result from cache

### ISSUE THREAD

**Issue by navis** [metatron-app/metatron-discovery#3667]
```
select L_ORDERKEY, count(*) from lineitem group by L_ORDERKEY limit 100;

Running.. {"queryType":"topN","dataSource":{"type":"table","name":"lineitem"},"dimension":{"type":"default","dimension":"L_ORDERKEY","outputName":"d0"},"metric":{"type":"dimension","previousStop":null,"ordering":"lexicographic"},"threshold":100,"granularity":{"type":"all"},"aggregations":[{"type":"count","name":"a0"}],"outputColumns":["d0","a0"]}
```

resulting..
```
java.lang.ClassCastException: io.druid.query.topn.TopNResultValue cannot be cast to io.druid.query.topn.BySegmentTopNResultValue
        at io.druid.query.topn.TopNQueryQueryToolChest$6.applyAsInt(TopNQueryQueryToolChest.java:281) ~[druid-processing-2021.2-SNAPSHOT.jar:2021.2-SNAPSHOT]
        at io.druid.client.CachingClusteredClient$CacheAccessor.apply(CachingClusteredClient.java:635) ~[druid-server-2021.2-SNAPSHOT.jar:2021.2-SNAPSHOT]
        at io.druid.common.guava.MappingYieldingAccumulator.accumulate(MappingYieldingAccumulator.java:55) ~[druid-common-2021.2-SNAPSHOT.jar:2021.2-SNAPSHOT]
        at io.druid.common.guava.BaseSequence.makeYielder(BaseSequence.java:96) ~[druid-common-2021.2-SNAPSHOT.jar:2021.2-SNAPSHOT]
        at io.druid.common.guava.BaseSequence.toYielder(BaseSequence.java:73) ~[druid-common-2021.2-SNAPSHOT.jar:2021.2-SNAPSHOT]
        at io.druid.common.guava.MappedSequence.toYielder(MappedSequence.java:54) ~[druid-common-2021.2-SNAPSHOT.jar:2021.2-SNAPSHOT]
        at io.druid.common.Yielders.each(Yielders.java:37) ~[druid-common-2021.2-SNAPSHOT.jar:2021.2-SNAPSHOT]
        at io.druid.common.guava.MergeSequence$1.accumulate(MergeSequence.java:64) ~[druid-common-2021.2-SNAPSHOT.jar:2021.2-SNAPSHOT]
        at io.druid.common.guava.MergeSequence$1.accumulate(MergeSequence.java:59) ~[druid-common-2021.2-SNAPSHOT.jar:2021.2-SNAPSHOT]
        at io.druid.common.guava.BaseSequence.accumulate(BaseSequence.java:58) ~[druid-common-2021.2-SNAPSHOT.jar:2021.2-SNAPSHOT]
        at io.druid.common.guava.MergeSequence.toYielder(MergeSequence.java:57) ~[druid-common-2021.2-SNAPSHOT.jar:2021.2-SNAPSHOT]
        at io.druid.query.RetryQueryRunner$1.toYielder(RetryQueryRunner.java:99) ~[druid-processing-2021.2-SNAPSHOT.jar:2021.2-SNAPSHOT]
        at io.druid.common.guava.CombiningSequence.toYielder(CombiningSequence.java:94) ~[druid-common-2021.2-SNAPSHOT.jar:2021.2-SNAPSHOT]
        at io.druid.common.guava.MappedSequence.toYielder(MappedSequence.java:54) ~[druid-common-2021.2-SNAPSHOT.jar:2021.2-SNAPSHOT]
        at io.druid.common.guava.MappedSequence.toYielder(MappedSequence.java:54) ~[druid-common-2021.2-SNAPSHOT.jar:2021.2-SNAPSHOT]
        at io.druid.common.guava.MappedSequence.toYielder(MappedSequence.java:54) ~[druid-common-2021.2-SNAPSHOT.jar:2021.2-SNAPSHOT]
        at io.druid.common.guava.MappedSequence.toYielder(MappedSequence.java:54) ~[druid-common-2021.2-SNAPSHOT.jar:2021.2-SNAPSHOT]
        at io.druid.query.CPUTimeMetricQueryRunner$1.toYielder(CPUTimeMetricQueryRunner.java:89) ~[druid-processing-2021.2-SNAPSHOT.jar:2021.2-SNAPSHOT]
        at io.druid.common.utils.Sequences$5.toYielder(Sequences.java:349) ~[druid-common-2021.2-SNAPSHOT.jar:2021.2-SNAPSHOT]
        at io.druid.common.guava.MappedSequence.toYielder(MappedSequence.java:54) ~[druid-common-2021.2-SNAPSHOT.jar:2021.2-SNAPSHOT]
        at io.druid.common.Yielders.each(Yielders.java:37) ~[druid-common-2021.2-SNAPSHOT.jar:2021.2-SNAPSHOT]
        at io.druid.common.guava.ConcatSequence.toYielder(ConcatSequence.java:69) ~[druid-common-2021.2-SNAPSHOT.jar:2021.2-SNAPSHOT]
        at io.druid.common.guava.ResourceClosingSequence.toYielder(ResourceClosingSequence.java:60) ~[druid-common-2021.2-SNAPSHOT.jar:2021.2-SNAPSHOT]
        at io.druid.common.Yielders.each(Yielders.java:37) ~[druid-common-2021.2-SNAPSHOT.jar:2021.2-SNAPSHOT]
        at io.druid.sql.http.SqlResource.execute(SqlResource.java:206) ~[druid-sql-2021.2-SNAPSHOT.jar:2021.2-SNAPSHOT]
        at io.druid.sql.http.SqlResource.doPost(SqlResource.java:131) ~[druid-sql-2021.2-SNAPSHOT.jar:2021.2-SNAPSHOT]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_202]
```

**Comment by navis** [comment]
Seemed regression from #3657. Should use query specific per segment container type(`TopNResultValue`) instead of generic type (`BySegmentTopNResultValue`)
