### ISSUE TITLE
Block on historical node for huge segment meta query

### ISSUE THREAD

**Issue by navis** [metatron-app/metatron-discovery#3839]
```
"qtp2133547083-116[segmentMetadata_bf575bb5-0bea-484b-999c-49caa7b10492]" #116 daemon prio=5 os_prio=0 tid=0x00007f69efd08000 nid=0xeed9 waiting on condition [0x00007f69a36f3000]
   java.lang.Thread.State: TIMED_WAITING (parking)
        at sun.misc.Unsafe.park(Native Method)
        - parking to wait for  <0x00000006a686e558> (a com.google.common.util.concurrent.ListenableFutureTask)
        at java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:215)
        at java.util.concurrent.FutureTask.awaitDone(FutureTask.java:426)
        at java.util.concurrent.FutureTask.get(FutureTask.java:204)
        at io.druid.query.PrioritizedListenableFutureTask.get(PrioritizedExecutorService.java:303)
        at io.druid.utils.StopWatch.wainOn(StopWatch.java:44)
        at io.druid.query.metadata.SegmentMetadataQueryRunnerFactory$2$1.run(SegmentMetadataQueryRunnerFactory.java:193)
        at io.druid.query.ConcatQueryRunner$1.apply(ConcatQueryRunner.java:51)
        at io.druid.query.ConcatQueryRunner$1.apply(ConcatQueryRunner.java:47)
        at io.druid.common.guava.MappingYieldingAccumulator.accumulate(MappingYieldingAccumulator.java:55)
        at io.druid.common.guava.MappingYieldingAccumulator.accumulate(MappingYieldingAccumulator.java:55)
        at io.druid.common.guava.BaseSequence.makeYielder(BaseSequence.java:96)
        at io.druid.common.guava.BaseSequence.access$100(BaseSequence.java:28)
        at io.druid.common.guava.BaseSequence$2.next(BaseSequence.java:127)
        at io.druid.common.guava.ConcatSequence.wrapYielder(ConcatSequence.java:107)
        at io.druid.common.guava.ConcatSequence.access$100(ConcatSequence.java:31)
        at io.druid.common.guava.ConcatSequence$2.next(ConcatSequence.java:124)
        at io.druid.common.guava.ConcatSequence$2.next(ConcatSequence.java:124)
        at io.druid.common.guava.ExecuteWhenDoneYielder.next(ExecuteWhenDoneYielder.java:47)
        at io.druid.common.guava.ResourceClosingYielder.next(ResourceClosingYielder.java:42)
        at io.druid.jackson.DruidDefaultSerializersModule$5.serialize(DruidDefaultSerializersModule.java:153)
        at io.druid.jackson.DruidDefaultSerializersModule$5.serialize(DruidDefaultSerializersModule.java:140)
        at com.fasterxml.jackson.databind.ser.DefaultSerializerProvider.serializeValue(DefaultSerializerProvider.java:128)
        at com.fasterxml.jackson.databind.ObjectWriter._configAndWriteValue(ObjectWriter.java:800)
        at com.fasterxml.jackson.databind.ObjectWriter.writeValue(ObjectWriter.java:642)
        at io.druid.server.QueryResource$3.write(QueryResource.java:316)
        at com.sun.jersey.core.impl.provider.entity.StreamingOutputProvider.writeTo(StreamingOutputProvider.java:71)
        at com.sun.jersey.core.impl.provider.entity.StreamingOutputProvider.writeTo(StreamingOutputProvider.java:57)
```

**Comment by navis** [comment]
```
"processing-14[segmentMetadata_bf575bb5-0bea-484b-999c-49caa7b10492_2020-11-20T00:00:00.000Z/2020-11-21T00:00:00.000Z_2020-11-20T00:00:06.870Z_1]" #166 daemon prio=5 os_prio=0 tid=0x00007f67e412b000 nid=0xf3e0 runnable [0x00007f6796fb0000]
   java.lang.Thread.State: RUNNABLE
        at java.io.RandomAccessFile.close0(Native Method)
        at java.io.RandomAccessFile.access$000(RandomAccessFile.java:59)
        at java.io.RandomAccessFile$1.close(RandomAccessFile.java:619)
        at java.io.FileDescriptor.closeAll(FileDescriptor.java:212)
        - locked <0x00000006a73896a0> (a java.io.FileDescriptor)
        at java.io.RandomAccessFile.close(RandomAccessFile.java:617)
        at io.druid.java.util.common.io.smoosh.SmooshedFileMapper.readSizedBytes(SmooshedFileMapper.java:178)
        at io.druid.segment.IndexIO$V9IndexLoader.lambda$load$1(IndexIO.java:1091)
        at io.druid.segment.IndexIO$V9IndexLoader$$Lambda$32/1416567077.call(Unknown Source)
        at io.druid.common.guava.DSuppliers$3.get(DSuppliers.java:150)
        at io.druid.segment.SimpleQueryableIndex.getColumnMeta(SimpleQueryableIndex.java:172)
        at io.druid.segment.SimpleQueryableIndex.asSignature(SimpleQueryableIndex.java:275)
        at io.druid.segment.QueryableIndexSegment.asSignature(QueryableIndexSegment.java:100)
        at io.druid.segment.Segment$Delegated.asSignature(Segment.java:116)
        at io.druid.query.RowResolver.of(RowResolver.java:67)
        at io.druid.query.metadata.SegmentAnalyzer.analyze(SegmentAnalyzer.java:68)
        at io.druid.query.metadata.SegmentMetadataQueryRunnerFactory$1.run(SegmentMetadataQueryRunnerFactory.java:84)
        at io.druid.query.QueryRunnerFactory$1.run(QueryRunnerFactory.java:72)
        at io.druid.query.ReferenceCountingSegmentQueryRunner.run(ReferenceCountingSegmentQueryRunner.java:61)
        at io.druid.query.MetricsEmittingQueryRunner.run(MetricsEmittingQueryRunner.java:95)
        at io.druid.client.CachingQueryRunner.run(CachingQueryRunner.java:159)
        at io.druid.query.BySegmentQueryRunner.run(BySegmentQueryRunner.java:54)
        at io.druid.query.MetricsEmittingQueryRunner.run(MetricsEmittingQueryRunner.java:95)
        at io.druid.query.spec.SpecificSegmentQueryRunner$1.call(SpecificSegmentQueryRunner.java:84)
        at io.druid.query.spec.SpecificSegmentQueryRunner$1.call(SpecificSegmentQueryRunner.java:80)
        at io.druid.query.spec.SpecificSegmentQueryRunner.doNamed(SpecificSegmentQueryRunner.java:185)
        at io.druid.query.spec.SpecificSegmentQueryRunner.run(SpecificSegmentQueryRunner.java:78)
        at io.druid.query.CPUTimeMetricQueryRunner.run(CPUTimeMetricQueryRunner.java:68)
        at io.druid.query.metadata.SegmentMetadataQueryRunnerFactory$2$1$1.call(SegmentMetadataQueryRunnerFactory.java:187)
        at io.druid.query.metadata.SegmentMetadataQueryRunnerFactory$2$1$1.call(SegmentMetadataQueryRunnerFactory.java:183)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at io.druid.query.PrioritizedListenableFutureTask.run(PrioritizedExecutorService.java:273)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
```

**Comment by navis** [comment]
Seemed regression from #3781
