### ISSUE TITLE
Sending-Email function when clicking password reset is not working properly

### ISSUE THREAD

**Issue by Cazen** [metatron-app/metatron-discovery#400]
**Describe the bug**

After setting the SMTP server, I pressed the Password Reset button to check the email sending operation, but E-mail is not sent. It seems that there is no problem with the SMTP server setting because the sending email function when register is normally sent, but there seems to be a problem with the Email-sending function of Password Reset.

**To Reproduce**
1. Go to T-Map Dataplatform PRD Metatron Discovery main page
2. Click on Forgotten password
3. Fill the form(e-mail address) and clicking send button
4. Check e-mail was not sent

**Additional context**
This may be a problem specific to T-map environment. Metatron Discovery log when email is not sent occasionally is as follows

2018-10-10 09:17:56.680  WARN [-] [SimpleAsyncTaskExecutor-1] app.metatron.discovery.common.Mailer     : E-mail could not be sent to user '[]'

org.springframework.mail.MailSendException: Failed messages: java.lang.NullPointerException
    at org.springframework.mail.javamail.JavaMailSenderImpl.doSend(JavaMailSenderImpl.java:474)
    at org.springframework.mail.javamail.JavaMailSenderImpl.send(JavaMailSenderImpl.java:345)
    at org.springframework.mail.javamail.JavaMailSenderImpl.send(JavaMailSenderImpl.java:340)
    at app.metatron.discovery.common.Mailer.sendEmail(Mailer.java:75)
    at app.metatron.discovery.common.Mailer.sendSignUpRequestMail(Mailer.java:127)
    at app.metatron.discovery.common.Mailer$$FastClassBySpringCGLIB$$91aa030a.invoke(<generated>)
    at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:204)
    at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:738)
    at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:157)
    at org.springframework.aop.interceptor.AsyncExecutionInterceptor$1.call(AsyncExecutionInterceptor.java:115)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at java.lang.Thread.run(Thread.java:748)

**Comment by kyungtaak** [comment]
I fixed this problem. :)

Other than smtp setting, The following setting is necessary.
```
mail:
  admin: admin@email.com
  baseUrl: https://base.url
```
