### ISSUE TITLE
Fix fail of BitmapOffsetTest.testSanity

### ISSUE THREAD

**Issue by navis** [metatron-app/metatron-discovery#4077]
```
java.lang.NullPointerException: null
        at org.roaringbitmap.buffer.ArrayBatchIterator.hasNext(ArrayBatchIterator.java:30)
        at org.roaringbitmap.buffer.RoaringBatchIterator.nextBatch(RoaringBatchIterator.java:23)
        at io.druid.segment.bitmap.FromBatchIterator.hasNext(FromBatchIterator.java:63)
        at io.druid.segment.BitmapOffset.increment(BitmapOffset.java:62)
        at io.druid.segment.BitmapOffsetTest.testSanity(BitmapOffsetTest.java:97)
```

Due to bug in RoaringBatchIterator.clone() in roaring bitmap.

**Comment by navis** [comment]
```
@Override
public BatchIterator clone() {
  try {
    RoaringBatchIterator it = (RoaringBatchIterator)super.clone();
    if (null != iterator) {
      it.iterator = iterator.clone();
    }
    if (null != containerPointer) {
      it.containerPointer = containerPointer.clone();
    }
    it.arrayBatchIterator = null;
    it.bitmapBatchIterator = null;
    it.runBatchIterator = null;
    return it;
  } catch (CloneNotSupportedException e) {
    // won't happen
    throw new IllegalStateException();
  }
}
```

**Comment by navis** [comment]
reported https://github.com/RoaringBitmap/RoaringBitmap/issues/574
