### ISSUE TITLE
Invalid default value for 'lastModifiedAt'

### ISSUE THREAD

**Issue by babokim** [metatron-app/metatron-discovery#567]
**Describe the bug**
mysql 환경에서 --init 옵션을 이용하여 metatron 설치 시 다음과 같은 오류 메시지가 나타남
```
Caused by: com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Invalid default value for 'lastModifiedAt'
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:404)
	at com.mysql.jdbc.Util.getInstance(Util.java:387)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:941)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3870)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3806)
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2470)
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2617)
	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2546)
	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2504)
	at com.mysql.jdbc.StatementImpl.executeInternal(StatementImpl.java:840)
	at com.mysql.jdbc.StatementImpl.execute(StatementImpl.java:740)
	at sun.reflect.GeneratedMethodAccessor42.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
```

**To Reproduce**
1. conf/application.yaml에서 mysql 설정 enable
2. conf/metatron-env.sh 에서  export METATRON_DB_TYPE=mysql 설정
3. bin/metatron.sh --init start

**Expected behavior**
정상적으로 관련 테이블이 생성되어야 한다.

**Screenshots**
없음

**Desktop (please complete the following information):**
- MySQL Server version: 5.7.24 MySQL Community Server (GPL)

**Additional context**
없음

**Comment by alchan-lee** [comment]
레포팅 감사드립니다.

mysql 5.7부터 strict mode가 default로 설정됨에 따라 저희가 제공하는 ddl문에 문제가 있는 것으로 보입니다.
빠른 시일내 수정된 ddl을 배포하겠습니다.


---
그 이전에 해결을 위해 제안드릴 수 있는 workaround는 sql_mode를 설정하는 방법입니다.

기본적으로 설정되어 있는 sql_mode 값에서 NO_ZERO_IN_DATE과 NO_ZERO_DATE 값을 빼주시면 정상 동작합니다.

![image](https://user-images.githubusercontent.com/42234141/47632854-21e0ff80-db8f-11e8-8d62-0b942e8eb7c9.png)


✻ 설정법은 my.cnf 파일에 아래 내용을 입력하신 뒤, mysql을 재가동 하시면 됩니다.

[mysqld]
sql_mode = 'ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION'

**Comment by babokim** [comment]
@alchan-lee 감사합니다.
