### ISSUE TITLE
measure 타입 적재시 숫자 포맷이 아닌 컬럼데이터 처리 옵션 추가

### ISSUE THREAD

**Issue by kyungtaak** [metatron-app/metatron-discovery#735]
**Is your feature request related to a problem? Please describe.**
파일(CSV/Excel) 적재 단계에서 measure 타입 적재시  컬럼 데이터 내 숫자 포맷이 아닌 데이터가 존재할때, 아래와 같이 Druid 적재 오류가 발생합니다.  정상적인 작업이지만,  이 오류 메시지를 접한 사용자들은 데이터를 수정하여 적재를 하는 방법 뿐입니다. 

```
Caused by: com.metamx.common.parsers.ParseException: Unable to parse double from value[7.6530)]
	at io.druid.data.Rows.parseDouble(Rows.java:65) ~[druid-api-0.9.1-SNAPSHOT.jar:0.9.1-SNAPSHOT]
	at io.druid.segment.serde.StructMetricSerde$2.extractElement(StructMetricSerde.java:179) ~[druid-processing-0.9.1-SNAPSHOT.jar:0.9.1-SNAPSHOT]
	at io.druid.segment.serde.StructMetricSerde$2.extractValue(StructMetricSerde.java:137) ~[druid-processing-0.9.1-SNAPSHOT.jar:0.9.1-SNAPSHOT]
	at io.druid.segment.ColumnSelectorFactories$FromInputRow$8.get(ColumnSelectorFactories.java:576) ~[druid-processing-0.9.1-SNAPSHOT.jar:0.9.1-SNAPSHOT]
	at io.druid.query.aggregation.Aggregators$3.aggregate(Aggregators.java:245) ~[druid-processing-0.9.1-SNAPSHOT.jar:0.9.1-SNAPSHOT]
	at io.druid.segment.incremental.OnheapIncrementalIndex.aggregate(OnheapIncrementalIndex.java:238) ~[druid-processing-0.9.1-SNAPSHOT.jar:0.9.1-SNAPSHOT]
	... 14 more
Caused by: java.lang.NumberFormatException: For input string: "7.6530)"
	at sun.misc.FloatingDecimal.readJavaFormatString(FloatingDecimal.java:2043) ~[?:1.8.0_171]
	at sun.misc.FloatingDecimal.parseDouble(FloatingDecimal.java:110) ~[?:1.8.0_171]
	at java.lang.Double.parseDouble(Double.java:538) ~[?:1.8.0_171]
	at java.lang.Double.valueOf(Double.java:502) ~[?:1.8.0_171]
	at io.druid.data.Rows.tryParseDouble(Rows.java:185) ~[druid-api-0.9.1-SNAPSHOT.jar:0.9.1-SNAPSHOT]
	at io.druid.data.Rows.parseDouble(Rows.java:62) ~[druid-api-0.9.1-SNAPSHOT.jar:0.9.1-SNAPSHOT]
	at io.druid.segment.serde.StructMetricSerde$2.extractElement(StructMetricSerde.java:179) ~[druid-processing-0.9.1-SNAPSHOT.jar:0.9.1-SNAPSHOT]
	at io.druid.segment.serde.StructMetricSerde$2.extractValue(StructMetricSerde.java:137) ~[druid-processing-0.9.1-SNAPSHOT.jar:0.9.1-SNAPSHOT]
	at io.druid.segment.ColumnSelectorFactories$FromInputRow$8.get(ColumnSelectorFactories.java:576) ~[druid-processing-0.9.1-SNAPSHOT.jar:0.9.1-SNAPSHOT]
	at io.druid.query.aggregation.Aggregators$3.aggregate(Aggregators.java:245) ~[druid-processing-0.9.1-SNAPSHOT.jar:0.9.1-SNAPSHOT]
	at io.druid.segment.incremental.OnheapIncrementalIndex.aggregate(OnheapIncrementalIndex.java:238) ~[druid-processing-0.9.1-SNAPSHOT.jar:0.9.1-SNAPSHOT]
	... 14 more
2018-11-11T07:40:03,057 INFO [task-runner-0-priority-0] io.druid.indexing.overlord.TaskRunnerUtils - Task [index_population_2018-11-11T07:37:07.209Z] status changed to [FAILED].
2018-11-11T07:40:03,061 INFO [task-runner-0-priority-0] io.druid.indexing.worker.executor.ExecutorLifecycle - Task completed with status: {
  "id" : "index_population_2018-11-11T07:37:07.209Z",
  "status" : "FAILED",
  "duration" : 170239,
  "reason" : "Exception: [io.druid.segment.incremental.OnheapIncrementalIndex.aggregate(OnheapIncrementalIndex.java:243), 
```

**Describe the solution you'd like**
- 화면 내에서 숫자 포맷에 대한 Validation 옵션 처리가 있었으면 합니다. (숫자 뿐만 아니라 Logical Type 에 대한 validation 옵션이 필요합니다. 무시하는 방법? @metatron-app/design  검토 부탁드립니다.)
- 별도의 replace 나 다른 옵션에 대한 FAQ 도 마련합니다. 

**Describe alternatives you've considered**
(N/A)

**Additional context**
- 전체 Task Log : [numberformat_error.log](https://github.com/metatron-app/metatron-discovery/files/2569212/numberformat_error.log)

**Comment by navis** [comment]
Evaluation 으로 덮어쓰면 안돼요?

**Comment by kyungtaak** [comment]
@navis 네 위의 전체 Task Log 에 replace 함수를 사용해 보았는데요. 안되더라고요. 
```
{
        "outputName" : "user_cnt",
        "expressions" : [ "replace( user_cnt, ')', '')" ]
} 
```

**Comment by navis** [comment]
@kyungtaak 잘되는데요?

**Comment by kyungtaak** [comment]
ignoreInvalidRows 에 위의 내용의 오류가 포함되도록 구성하였습니다.

@navis ignoreInvalidRows 에서 발생하는 컬럼명을 로그에 명시해주시는것에 검토 부탁드립니다.

**Comment by deidera08** [comment]
@kyungtaak @navis @AnnieHwang 
늦은 답변 드려 죄송합니다.

기본적으로 measure나 integer와 같은 숫자연산을 위한 타입을 지정할때는 최소한의 숫자/문자값을 판별해주는 validation이 필요하다고 생각합니다. 특히나 role은 ingestion 이후에 수정할 수 없기 때문에 꼭 필요할 것 같아요.

때문에 숫자값이 아닐 경우 type/role변경을 불가하게 하거나, 오류메세지 등을 노출시키는 방향으로 정책을 곧 정리하도록 하겠습니다.
