### ISSUE TITLE
Keep/Delete rows by clicking histogram with timestamp values

### ISSUE THREAD

**Issue by mh0203** [metatron-app/metatron-discovery#761]
**Is your feature request related to a problem? Please describe.**
현재 histogram에서 그래프를 선택해서 해당 값을 가지는 row들을 삭제할 수 있습니다.
Timestamp 값에 대해서도 동일한 동작이 가능해야 합니다.

**Describe the solution you'd like**
이를 위해서는 timestamp 값을 비교하는 구문을 작성해야 합니다.
다음과 같은 함수들을 사용합니다.

1. timestamp(value, format): value 값을 format 기준으로 해석하여 timestamp 값을 반환합니다.
   ex) timestamp('2011-01-02', 'yyyy-MM-dd') > 2011-01-02T00:00:00 의 timestamp가 생성됨.
2.time_diff(timestamp1, timstamp2): 두 시간 값을 비교할때 사용합니다. timstamp2-timestamp1 값을 반환합니다. 즉 timestamp1이 timstamp2보다 앞선(과거)시간이면 양수를, timestamp1이 timestamp2보다 나중(미래)시간이면 음수를 반환합니다. 인자로 string이 아닌 timestamp 값을 넣어야 합니다.

두 함수를 조합해서 birth_date가 2013년 1월 1일부터 2013년 2월 10일까지인 사람을 delete할 경우 다음과 같은 조건절을 작성합니다.

time_diff(timestamp('2013-01-01', 'yyy-MM-dd'), birth_date) >= 0 && time_diff(timestamp('2013-02-10', 'yyyy-MM-dd'), birth_date) <=0

**Describe alternatives you've considered**

**Additional context**

**Comment by joohokim1** [comment]
If you select too many histogram bars, then the rule string becomes too long to be a PrepTransformRule entity. If https://github.com/metatron-app/metatron-discovery/issues/908 is resolved, this problem will is resolved as well.

_Histogram bar를 여럿 선택해서 rule string이 너무 길어지면 PrepTransformRule entity를 만들 수 없게 되어서 문제가 발생합니다. https://github.com/metatron-app/metatron-discovery/issues/908 가 해결되면, 이 문제도 같이 해결됩니다._

**Comment by joohokim1** [comment]
https://github.com/metatron-app/metatron-discovery/issues/908 을 처리했음에도 불구하고 문제가 발생합니다. 다만, rule string의 제한이 더 넉넉해졌습니다만, 더 긴 rulestring도 받아줘야할 것 같습니다.
다음과 같은 서버 로그를 내며 에러가 발생합니다.
`Caused by: java.sql.BatchUpdateException: Packet for query is too large (22600794 > 4194304). You can change this value on the server by setting the max_allowed_packet' variable.
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:422)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:404)
	at com.mysql.jdbc.Util.getInstance(Util.java:387)
	at com.mysql.jdbc.SQLError.createBatchUpdateException(SQLError.java:1160)
	at com.mysql.jdbc.PreparedStatement.executeBatchSerially(PreparedStatement.java:1773)
	at com.mysql.jdbc.PreparedStatement.executeBatchInternal(PreparedStatement.java:1257)
	at com.mysql.jdbc.StatementImpl.executeBatch(StatementImpl.java:959)
	at sun.reflect.GeneratedMethodAccessor324.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.apache.tomcat.jdbc.pool.StatementFacade$StatementProxy.invoke(StatementFacade.java:114)
	at com.sun.proxy.$Proxy306.executeBatch(Unknown Source)
	at org.hibernate.engine.jdbc.batch.internal.BatchingBatch.performExecution(BatchingBatch.java:110)
	... 155 common frames omitted
Caused by: com.mysql.jdbc.PacketTooBigException: Packet for query is too large (22600794 > 4194304). You can change this value on the server by setting the max_allowed_packet' variable.
	at com.mysql.jdbc.MysqlIO.send(MysqlIO.java:3575)
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2452)
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2617)
	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2550)
	at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:1861)
	at com.mysql.jdbc.PreparedStatement.executeUpdateInternal(PreparedStatement.java:2073)
	at com.mysql.jdbc.PreparedStatement.executeBatchSerially(PreparedStatement.java:1751)
	... 163 common frames omitted`
